package com.familygrowth.web;
import com.familygrowth.application.FamilyGrowthService.NotFoundException; import com.familygrowth.application.Stage3Service.*; import jakarta.validation.ConstraintViolationException; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.*; import org.springframework.web.bind.MethodArgumentNotValidException; import org.springframework.web.bind.MissingRequestHeaderException; import org.springframework.web.bind.annotation.*;
@RestControllerAdvice public class ApiExceptionHandler {
 @ExceptionHandler(NotFoundException.class) ResponseEntity<ApiResponse<Void>> notFound(){return ResponseEntity.status(404).body(new ApiResponse<>(null,new ApiResponse.ApiError("RESOURCE_NOT_FOUND","Resource not found"),null));}
 @ExceptionHandler(AuthenticationException.class) ResponseEntity<ApiResponse<Void>> unauthorized(){return ResponseEntity.status(401).body(new ApiResponse<>(null,new ApiResponse.ApiError("AUTHENTICATION_FAILED","Authentication failed"),null));}
 @ExceptionHandler(ForbiddenException.class) ResponseEntity<ApiResponse<Void>> forbidden(){return ResponseEntity.status(403).body(new ApiResponse<>(null,new ApiResponse.ApiError("FORBIDDEN","Operation is not allowed"),null));}
 @ExceptionHandler({ConflictException.class,DataIntegrityViolationException.class}) ResponseEntity<ApiResponse<Void>> conflict(){return ResponseEntity.status(409).body(new ApiResponse<>(null,new ApiResponse.ApiError("CONFLICT","Operation conflicts with current state"),null));}
 @ExceptionHandler(PinLockedException.class) ResponseEntity<ApiResponse<Void>> locked(){return ResponseEntity.status(429).body(new ApiResponse<>(null,new ApiResponse.ApiError("PIN_LOCKED","PIN is temporarily locked"),null));}
 @ExceptionHandler({MethodArgumentNotValidException.class,ConstraintViolationException.class,IllegalArgumentException.class,MissingRequestHeaderException.class}) ResponseEntity<ApiResponse<Void>> invalid(Exception e){return ResponseEntity.badRequest().body(new ApiResponse<>(null,new ApiResponse.ApiError("VALIDATION_FAILED","Request validation failed"),null));}
}
