package com.familygrowth.web;
import com.familygrowth.application.Stage27GrowthService;import com.familygrowth.domain.Stage27GrowthModels.*;import com.familygrowth.domain.Stage3Models;import com.familygrowth.domain.Stage3Models.Actor;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.io.IOException;import java.time.LocalDate;import java.util.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/v1/families/{familyId}/children/{childId}/growth-archive") public class Stage27GrowthController{
 private final Stage27GrowthService service;public Stage27GrowthController(Stage27GrowthService service){this.service=service;}
 @GetMapping("/plans")ApiResponse<List<Plan>> plans(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.plans(a,familyId,childId));}
 @PostMapping("/plans")@ResponseStatus(HttpStatus.CREATED)ApiResponse<Plan> createPlan(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody PlanRequest r){return ApiResponse.ok(service.createPlan(a,familyId,childId,r.title(),r.description(),r.category(),r.ageStage(),r.target(),r.startDate(),r.endDate(),r.status(),key));}
 @PostMapping("/plans/{planId}/transition")ApiResponse<Plan> transitionPlan(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID planId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody PlanTransition r){return ApiResponse.ok(service.transitionPlan(a,familyId,childId,planId,r.status(),r.expectedRevision(),r.reason(),key));}
 @GetMapping("/plans/{planId}/goals")ApiResponse<List<Goal>> goals(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID planId){return ApiResponse.ok(service.goals(a,familyId,childId,planId));}
 @PostMapping("/plans/{planId}/goals")@ResponseStatus(HttpStatus.CREATED)ApiResponse<Goal> createGoal(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID planId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody GoalRequest r){return ApiResponse.ok(service.createGoal(a,familyId,childId,planId,r.title(),r.description(),r.target(),key));}
 @PostMapping("/goals/{goalId}/transition")ApiResponse<Goal> transitionGoal(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID goalId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody GoalTransition r){return ApiResponse.ok(service.transitionGoal(a,familyId,childId,goalId,r.status(),r.expectedRevision(),r.reason(),key));}
 @GetMapping("/milestones")ApiResponse<List<Milestone>> milestones(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.milestones(a,familyId,childId));}
 @PostMapping("/milestones")@ResponseStatus(HttpStatus.CREATED)ApiResponse<Milestone> createMilestone(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody MilestoneRequest r){return ApiResponse.ok(service.createMilestone(a,familyId,childId,r.planId(),r.goalId(),r.occurredOn(),r.category(),r.title(),r.observation(),key));}
 @PutMapping("/milestones/{milestoneId}")ApiResponse<Milestone> updateMilestone(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID milestoneId,@RequestHeader("Idempotency-Key")String key,@Valid @RequestBody MilestoneUpdate r){return ApiResponse.ok(service.updateMilestone(a,familyId,childId,milestoneId,r.occurredOn(),r.category(),r.title(),r.observation(),r.expectedRevision(),key));}
 @PostMapping(value="/milestones/{milestoneId}/artifacts",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)@ResponseStatus(HttpStatus.CREATED)ApiResponse<ArtifactMetadata> artifact(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID milestoneId,@RequestHeader("Idempotency-Key")String key,@RequestPart("file")MultipartFile file,@RequestParam("altText")String alt)throws IOException{return ApiResponse.ok(service.addArtifact(a,familyId,childId,milestoneId,file.getContentType(),file.getBytes(),alt,key));}
 @GetMapping("/artifacts/{artifactId}")ResponseEntity<byte[]> artifact(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID artifactId){Artifact v=service.artifact(a,familyId,childId,artifactId);return ResponseEntity.ok().cacheControl(CacheControl.noStore()).contentType(MediaType.parseMediaType(v.metadata().contentType())).contentLength(v.metadata().byteSize()).header("X-Content-Type-Options","nosniff").body(v.content());}
 @GetMapping("/parent-record-templates")ApiResponse<List<ParentRecordTemplate>> templates(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.templates(a,familyId,childId));}
 @GetMapping("/report")ApiResponse<GrowthReport> report(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.report(a,familyId,childId));}
 record PlanRequest(@NotBlank@Size(max=120)String title,@Size(max=1000)String description,@NotNull GrowthCategory category,@NotBlank@Size(max=32)String ageStage,@Size(max=500)String target,@NotNull LocalDate startDate,LocalDate endDate,PlanStatus status){}
 record PlanTransition(@NotNull PlanStatus status,@Min(0)long expectedRevision,@NotBlank@Size(max=500)String reason){}
 record GoalRequest(@NotBlank@Size(max=120)String title,@Size(max=1000)String description,@Size(max=500)String target){}
 record GoalTransition(@NotNull GoalStatus status,@Min(0)long expectedRevision,@NotBlank@Size(max=500)String reason){}
 record MilestoneRequest(UUID planId,UUID goalId,@NotNull@PastOrPresent LocalDate occurredOn,@NotNull MilestoneCategory category,@NotBlank@Size(max=160)String title,@NotBlank@Size(max=1500)String observation){}
 record MilestoneUpdate(@NotNull@PastOrPresent LocalDate occurredOn,@NotNull MilestoneCategory category,@NotBlank@Size(max=160)String title,@NotBlank@Size(max=1500)String observation,@Min(0)long expectedRevision){}
}
