package com.familygrowth.web;
import com.familygrowth.application.Stage7Service;import com.familygrowth.domain.Stage3Models;import com.familygrowth.domain.Stage3Models.Actor;import com.familygrowth.domain.Stage7Models.*;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/families/{familyId}") class Stage7Controller{
 private final Stage7Service service;Stage7Controller(Stage7Service service){this.service=service;}
 @PostMapping("/funds") @ResponseStatus(HttpStatus.CREATED) ApiResponse<VirtualFund> fund(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId,@Valid @RequestBody FundRequest r){return ApiResponse.ok(service.createFund(actor,familyId,r.name(),r.riskLabel()));}
 @GetMapping("/funds") ApiResponse<List<VirtualFund>> funds(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId){return ApiResponse.ok(service.funds(actor,familyId));}
 @PostMapping("/funds/{fundId}/nav") @ResponseStatus(HttpStatus.CREATED) ApiResponse<FundNav> nav(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId,@PathVariable UUID fundId,@Valid @RequestBody NavRequest r){return ApiResponse.ok(service.addNav(actor,familyId,fundId,r.navDate(),r.nav()));}
 @PostMapping("/funds/{fundId}/fee-rules") @ResponseStatus(HttpStatus.CREATED) ApiResponse<FundFeeRule> rule(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId,@PathVariable UUID fundId,@Valid @RequestBody FeeRequest r){return ApiResponse.ok(service.createRule(actor,familyId,fundId,r.buyFeeRate(),r.sellFeeRate()));}
 @PostMapping("/children/{childId}/funds/{fundId}/trade-previews") @ResponseStatus(HttpStatus.CREATED) ApiResponse<TradePreview> preview(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID fundId,@Valid @RequestBody PreviewRequest r){return ApiResponse.ok(service.preview(actor,familyId,childId,fundId,r.side(),r.inputAmount()));}
 @PostMapping("/fund-trade-previews/{previewId}/confirm") ApiResponse<FundTradeOrder> confirm(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId,@PathVariable UUID previewId,@RequestHeader("Idempotency-Key")String key){return ApiResponse.ok(service.confirm(actor,familyId,previewId,key));}
 @GetMapping("/children/{childId}/funds/{fundId}/position") ApiResponse<FundPosition> position(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor actor,@PathVariable UUID familyId,@PathVariable UUID childId,@PathVariable UUID fundId){return ApiResponse.ok(service.position(actor,familyId,childId,fundId));}
 record FundRequest(@NotBlank @Size(max=120)String name,@NotBlank @Size(max=80)String riskLabel){} record NavRequest(@NotNull LocalDate navDate,@NotNull @DecimalMin("0.000001")BigDecimal nav){} record FeeRequest(@NotNull @DecimalMin("0") @DecimalMax("0.999999")BigDecimal buyFeeRate,@NotNull @DecimalMin("0") @DecimalMax("0.999999")BigDecimal sellFeeRate){} record PreviewRequest(@NotNull TradeSide side,@NotNull @DecimalMin("0.00000001")BigDecimal inputAmount){}
}
