package com.familygrowth.web;
import static com.familygrowth.domain.Stage31EconomyModels.*;import com.familygrowth.application.Stage31EconomyService;import com.familygrowth.domain.Stage3Models;import com.familygrowth.domain.Stage3Models.Actor;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.UUID;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/v1/families/{familyId}/economy-lab")class Stage31EconomyController{private final Stage31EconomyService service;Stage31EconomyController(Stage31EconomyService s){service=s;}
 @GetMapping ApiResponse<EconomyLabSnapshot> snapshot(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId){return ApiResponse.ok(service.snapshot(a,familyId));}
 @PutMapping("/saving-rule")ApiResponse<SavingRewardRule> saving(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@Valid@RequestBody SavingRuleRequest r){return ApiResponse.ok(service.configureSaving(a,familyId,r.periodicRate(),r.minimumBalance()));}
 @PostMapping("/children/{childId}/saving-awards")@ResponseStatus(HttpStatus.CREATED)ApiResponse<SavingRewardAward> settle(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody AwardRequest r){return ApiResponse.ok(service.settleSaving(a,familyId,childId,r.cycleKey(),key));}
 @PutMapping("/funds/{fundId}/market-rule")ApiResponse<SimulatedMarketRule> market(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID fundId,@Valid@RequestBody MarketRequest r){return ApiResponse.ok(service.configureMarket(a,familyId,fundId,r.seedLabel(),r.maximumDailyBps()));}
 @PostMapping("/funds/{fundId}/ticks")@ResponseStatus(HttpStatus.CREATED)ApiResponse<SimulatedMarketTick> tick(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID fundId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody TickRequest r){return ApiResponse.ok(service.tick(a,familyId,fundId,r.tickDate(),key));}
 @PutMapping("/funds/{fundId}/holding-fee-rule")ApiResponse<HoldingFeeRule> holding(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID fundId,@Valid@RequestBody HoldingRequest r){return ApiResponse.ok(service.configureHolding(a,familyId,fundId,r.minimumHoldingDays(),r.earlyFeeRate()));}
 @PostMapping("/cosmetics")@ResponseStatus(HttpStatus.CREATED)ApiResponse<UUID> cosmetic(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@Valid@RequestBody CosmeticRequest r){return ApiResponse.ok(service.createCosmetic(a,familyId,r.title(),r.coinCost(),r.stockCount()));}
 record SavingRuleRequest(@NotNull@DecimalMin("0")@DecimalMax("0.100000")BigDecimal periodicRate,@NotNull@DecimalMin("0")BigDecimal minimumBalance){}record AwardRequest(@NotBlank String cycleKey){}record MarketRequest(@NotBlank@Size(min=4,max=80)String seedLabel,@Min(0)@Max(2000)int maximumDailyBps){}record TickRequest(@NotNull LocalDate tickDate){}record HoldingRequest(@Min(0)@Max(3650)int minimumHoldingDays,@NotNull@DecimalMin("0")@DecimalMax("0.500000")BigDecimal earlyFeeRate){}record CosmeticRequest(@NotBlank@Size(max=120)String title,@Min(1)long coinCost,@Min(1)@Max(999)int stockCount){}
}
