package com.familygrowth.web;
import com.familygrowth.application.Stage28RewardService;import com.familygrowth.domain.Stage28RewardModels.*;import com.familygrowth.domain.Stage3Models;import com.familygrowth.domain.Stage3Models.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/families/{familyId}")class Stage28RewardController{
 private final Stage28RewardService service;Stage28RewardController(Stage28RewardService service){this.service=service;}
 @PostMapping("/children/{childId}/reward-budget-rules")@ResponseStatus(HttpStatus.CREATED)ApiResponse<BudgetRule> budget(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody BudgetRuleRequest r){return ApiResponse.ok(service.createBudgetRule(a,familyId,childId,r.zoneId(),r.dailyMoneyLimit(),r.weeklyMoneyLimit(),r.monthlyMoneyLimit(),r.overflowPolicy(),r.excessCoinPerMoney(),r.excessXpPerMoney(),key));}
 @GetMapping("/children/{childId}/reward-budget-rules/active")ApiResponse<BudgetRule> activeBudget(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.activeBudgetRule(a,familyId,childId).orElse(null));}
 @GetMapping("/children/{childId}/reward-budget-summary")ApiResponse<BudgetSummary> budgetSummary(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.budgetSummary(a,familyId,childId));}
 @PostMapping("/children/{childId}/reward-budget-overrides")@ResponseStatus(HttpStatus.CREATED)ApiResponse<BudgetOverride> override(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody OverrideRequest r){return ApiResponse.ok(service.createOverride(a,familyId,childId,r.completionId(),new RewardGrant(r.xp(),r.coin(),r.money()),r.reason(),key));}
 @PostMapping("/exchange-control-rules")@ResponseStatus(HttpStatus.CREATED)ApiResponse<ExchangeControlRule> exchangeControl(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody ExchangeControlRequest r){return ApiResponse.ok(service.createExchangeControl(a,familyId,r.moneyToCoinEnabled(),r.coinToMoneyEnabled(),r.moneyToCoinDailyLimit(),r.moneyToCoinMonthlyLimit(),r.coinToMoneyDailyLimit(),r.coinToMoneyMonthlyLimit(),r.childRequiresParentApproval(),r.zoneId(),key));}
 @GetMapping("/exchange-control-rules/active")ApiResponse<ExchangeControlRule> activeExchangeControl(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId){return ApiResponse.ok(service.activeExchangeControl(a,familyId).orElse(null));}
 @PostMapping("/children/{childId}/exchange-approval-requests")@ResponseStatus(HttpStatus.CREATED)ApiResponse<ExchangeApproval> approval(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody ApprovalRequest r){return ApiResponse.ok(service.requestExchangeApproval(a,familyId,childId,r.previewId(),key));}
 @GetMapping("/children/{childId}/exchange-approval-requests")ApiResponse<List<ExchangeApproval>> approvals(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID childId){return ApiResponse.ok(service.exchangeApprovals(a,familyId,childId));}
 @PostMapping("/exchange-approval-requests/{requestId}/review")ApiResponse<ExchangeApproval> reviewApproval(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID requestId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody ApprovalReview r){return ApiResponse.ok(service.reviewExchangeApproval(a,familyId,requestId,r.approved(),r.note(),key));}
 @PostMapping("/reward-orders/{orderId}/fulfill")ApiResponse<Fulfillment> fulfill(@RequestAttribute(Stage3Models.ACTOR_REQUEST_ATTRIBUTE)Actor a,@PathVariable UUID familyId,@PathVariable UUID orderId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody FulfillRequest r){return ApiResponse.ok(service.fulfill(a,familyId,orderId,r.note(),key));}
 record BudgetRuleRequest(@NotBlank@Size(max=64)String zoneId,@NotNull@DecimalMin("0.00")BigDecimal dailyMoneyLimit,@NotNull@DecimalMin("0.00")BigDecimal weeklyMoneyLimit,@NotNull@DecimalMin("0.00")BigDecimal monthlyMoneyLimit,@NotNull OverflowPolicy overflowPolicy,@NotNull@DecimalMin("0.000000")BigDecimal excessCoinPerMoney,@NotNull@DecimalMin("0.000000")BigDecimal excessXpPerMoney){}
 record OverrideRequest(@NotNull UUID completionId,@Min(0)long xp,@Min(0)long coin,@NotNull@DecimalMin("0.00")BigDecimal money,@NotBlank@Size(max=500)String reason){}
 record ExchangeControlRequest(boolean moneyToCoinEnabled,boolean coinToMoneyEnabled,@NotNull@DecimalMin("0.00")BigDecimal moneyToCoinDailyLimit,@NotNull@DecimalMin("0.00")BigDecimal moneyToCoinMonthlyLimit,@NotNull@DecimalMin("0.00")BigDecimal coinToMoneyDailyLimit,@NotNull@DecimalMin("0.00")BigDecimal coinToMoneyMonthlyLimit,boolean childRequiresParentApproval,@NotBlank@Size(max=64)String zoneId){}
 record ApprovalRequest(@NotNull UUID previewId){}record ApprovalReview(boolean approved,@Size(max=500)String note){}record FulfillRequest(@NotBlank@Size(max=500)String note){}
}
