package com.familygrowth;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.mock.web.MockMultipartFile;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;
@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage27growth;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate"})@AutoConfigureMockMvc@ActiveProfiles("test")class Stage27GrowthArchiveApiTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @Test void parentOwnsGrowthArchiveWithIdempotentStatesAndControlledImages()throws Exception{Session p=bootstrap("成长年轮家庭","583924"),other=bootstrap("另一个成长家庭","583925");UUID child=child(p,"小树","2021-05-02"),otherChild=child(other,"另一棵树","2021-04-02");String childToken=childToken(p,child),base=base(p.family,child);
  mvc.perform(post(base+"/plans").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-plan-invalid-terminal").contentType(MediaType.APPLICATION_JSON).content("{\"title\":\"伪造完成\",\"category\":\"OTHER\",\"ageStage\":\"FAMILY\",\"startDate\":\"2026-08-01\",\"status\":\"COMPLETED\"}")).andExpect(status().isBadRequest());
  String planBody="{\"title\":\"现实成长计划\",\"description\":\"把真实行动记下来\",\"category\":\"HABITS\",\"ageStage\":\"KINDERGARTEN\",\"target\":\"能够参与一次整理\",\"startDate\":\"2026-08-01\",\"status\":\"DRAFT\"}";
  JsonNode plan=data(mvc.perform(post(base+"/plans").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-plan-1").contentType(MediaType.APPLICATION_JSON).content(planBody)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("DRAFT")).andReturn());UUID planId=UUID.fromString(plan.path("id").asText());
  mvc.perform(post(base+"/plans").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-plan-1").contentType(MediaType.APPLICATION_JSON).content(planBody)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.id").value(planId.toString()));
  mvc.perform(post(base+"/plans/"+planId+"/transition").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-plan-active").contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"ACTIVE\",\"expectedRevision\":0,\"reason\":\"现在开始记录\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.revision").value(1));
  mvc.perform(post(base+"/plans/"+planId+"/transition").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-plan-stale").contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"PAUSED\",\"expectedRevision\":0,\"reason\":\"旧页面尝试覆盖\"}")).andExpect(status().isConflict());
  JsonNode goal=data(mvc.perform(post(base+"/plans/"+planId+"/goals").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-goal-1").contentType(MediaType.APPLICATION_JSON).content("{\"title\":\"一起整理\",\"description\":\"家长陪伴\",\"target\":\"自己放回一件物品\"}")).andExpect(status().isCreated()).andReturn());UUID goalId=UUID.fromString(goal.path("id").asText());
  String milestoneBody="{\"planId\":\""+planId+"\",\"goalId\":\""+goalId+"\",\"occurredOn\":\"2026-08-30\",\"category\":\"SELF_CARE\",\"title\":\"自己放回画笔\",\"observation\":\"提醒一次后，把一支画笔放回原处\"}";
  JsonNode milestone=data(mvc.perform(post(base+"/milestones").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-milestone-1").contentType(MediaType.APPLICATION_JSON).content(milestoneBody)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.revision").value(0)).andReturn());UUID milestoneId=UUID.fromString(milestone.path("id").asText());
  byte[] png=new byte[]{(byte)137,80,78,71,13,10,26,10,0,0,0,0};MockMultipartFile file=new MockMultipartFile("file","moment.png","image/png",png);
  JsonNode artifact=data(mvc.perform(multipart(base+"/milestones/"+milestoneId+"/artifacts").file(file).param("altText","孩子把画笔放回盒子").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-artifact-1")).andExpect(status().isCreated()).andExpect(jsonPath("$.data.contentType").value("image/png")).andExpect(jsonPath("$.data.byteSize").value(png.length)).andReturn());UUID artifactId=UUID.fromString(artifact.path("id").asText());
  mvc.perform(get(base+"/artifacts/"+artifactId).header("Authorization",bearer(p.token))).andExpect(status().isOk()).andExpect(header().string("Cache-Control",org.hamcrest.Matchers.containsString("no-store"))).andExpect(content().bytes(png));
  MockMultipartFile fake=new MockMultipartFile("file","fake.png","image/png","<svg/>".getBytes(StandardCharsets.UTF_8));mvc.perform(multipart(base+"/milestones/"+milestoneId+"/artifacts").file(fake).param("altText","伪造文件").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-artifact-fake")).andExpect(status().isBadRequest());
  mvc.perform(get(base+"/report").header("Authorization",bearer(p.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.activePlans").value(1)).andExpect(jsonPath("$.data.milestones").value(1)).andExpect(jsonPath("$.data.artifacts").value(1));
  mvc.perform(get(base+"/parent-record-templates").header("Authorization",bearer(p.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(5));
  mvc.perform(get(base+"/plans").header("Authorization",bearer(childToken))).andExpect(status().isForbidden());mvc.perform(get(base(other.family,otherChild)+"/plans").header("Authorization",bearer(p.token))).andExpect(status().isNotFound());
  mvc.perform(post(base+"/goals/"+goalId+"/transition").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-goal-complete").contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"COMPLETED\",\"expectedRevision\":0,\"reason\":\"目标事实已完成\"}")).andExpect(status().isOk());
  mvc.perform(post(base+"/goals/"+goalId+"/transition").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-goal-reopen").contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"ACTIVE\",\"expectedRevision\":1,\"reason\":\"尝试重开\"}")).andExpect(status().isBadRequest());
  String rights="/api/v1/families/"+p.family+"/children/"+child+"/data-rights";String exported=mvc.perform(post(rights+"/exports").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-export")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(exported).contains("growthArtifacts",artifactId.toString(),"image/png").doesNotContain(Base64.getEncoder().encodeToString(png));JsonNode preview=data(mvc.perform(post(rights+"/erasure-preview").header("Authorization",bearer(p.token)).header("Idempotency-Key","growth-erasure")).andExpect(status().isOk()).andReturn());mvc.perform(post(rights+"/erasures/"+preview.path("requestId").asText()+"/confirm").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"confirmationToken\":\""+preview.path("confirmationToken").asText()+"\",\"pin\":\"583924\"}")).andExpect(status().isOk());
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM growth_artifact WHERE family_id=? AND child_id=?",Integer.class,p.family,child)).isZero();assertThat(jdbc.queryForObject("SELECT observation FROM growth_milestone WHERE family_id=? AND child_id=?",String.class,p.family,child)).isEqualTo("[已删除]");assertThat(jdbc.queryForObject("SELECT target FROM growth_plan WHERE family_id=? AND child_id=?",String.class,p.family,child)).isEqualTo("[已删除]");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM growth_plan_action WHERE family_id=?",Integer.class,p.family)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM growth_milestone_action WHERE family_id=?",Integer.class,p.family)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_entry WHERE family_id=?",Integer.class,p.family)).isZero();
 }
 private Session bootstrap(String n,String pin)throws Exception{JsonNode d=data(mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\""+n+"\",\"parentName\":\"家长\",\"pin\":\""+pin+"\"}")).andExpect(status().isCreated()).andReturn());return new Session(UUID.fromString(d.path("familyId").asText()),d.path("session").path("token").asText());}
 private UUID child(Session p,String n,String birth)throws Exception{return UUID.fromString(data(mvc.perform(post("/api/v1/families/"+p.family+"/children").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\""+n+"\",\"birthDate\":\""+birth+"\",\"ageStage\":\"EARLY_CHILDHOOD_2_5\"}")).andExpect(status().isCreated()).andReturn()).path("id").asText());}
 private String childToken(Session p,UUID c)throws Exception{return data(mvc.perform(post("/api/v1/auth/child-sessions").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"childId\":\""+c+"\"}")).andExpect(status().isCreated()).andReturn()).path("token").asText();}private JsonNode data(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString()).path("data");}private String base(UUID f,UUID c){return "/api/v1/families/"+f+"/children/"+c+"/growth-archive";}private static String bearer(String v){return "Bearer "+v;}private record Session(UUID family,String token){}
}
