package com.familygrowth;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.util.UUID;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;
@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage31economy;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate"})@AutoConfigureMockMvc@ActiveProfiles("test")class Stage31EconomyLabApiTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @Test void rewardsMarketHoldingCostsAndCosmeticsStayTransparentAndIdempotent()throws Exception{Session s=bootstrap();UUID child=child(s);String base="/api/v1/families/"+s.family,lab=base+"/economy-lab";adjust(s,child,"MONEY","100.00","money-seed");adjust(s,child,"COIN","50","coin-seed");postJson(base+"/children/"+child+"/saving/transfers",s.token,"saving-seed","{\"direction\":\"DEPOSIT\",\"amount\":40.00}",201);
  putJson(lab+"/saving-rule",s.token,"{\"periodicRate\":0.050000,\"minimumBalance\":10.00}",200);Session other=bootstrap();UUID foreignChild=child(other);mvc.perform(post(lab+"/children/"+foreignChild+"/saving-awards").header("Authorization",bearer(s.token)).header("Idempotency-Key","foreign-award").contentType(MediaType.APPLICATION_JSON).content("{\"cycleKey\":\"2026-09\"}")).andExpect(status().isNotFound());JsonNode award=data(postJson(lab+"/children/"+child+"/saving-awards",s.token,"saving-award-1","{\"cycleKey\":\"2026-09\"}",201));assertThat(award.path("rewardAmount").decimalValue()).isEqualByComparingTo("2.00");postJson(lab+"/children/"+child+"/saving-awards",s.token,"saving-award-1","{\"cycleKey\":\"2026-09\"}",201);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM saving_reward_award WHERE family_id=?",Integer.class,s.family)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_entry WHERE family_id=? AND business_type LIKE 'SAVING_REWARD%'",Integer.class,s.family)).isEqualTo(2);
  UUID fund=id(postJson(base+"/funds",s.token,null,"{\"name\":\"可复现模拟池\",\"riskLabel\":\"只用于练习涨跌\"}",201));postJson(base+"/funds/"+fund+"/nav",s.token,null,"{\"navDate\":\"2026-08-31\",\"nav\":1.000000}",201);postJson(base+"/funds/"+fund+"/fee-rules",s.token,null,"{\"buyFeeRate\":0.010000,\"sellFeeRate\":0.020000}",201);putJson(lab+"/funds/"+fund+"/market-rule",s.token,"{\"seedLabel\":\"家庭练习种子\",\"maximumDailyBps\":300}",200);JsonNode tick=data(postJson(lab+"/funds/"+fund+"/ticks",s.token,"tick-one","{\"tickDate\":\"2026-09-01\"}",201));JsonNode tickAgain=data(postJson(lab+"/funds/"+fund+"/ticks",s.token,"tick-two","{\"tickDate\":\"2026-09-01\"}",201));assertThat(tickAgain.path("navAfter").decimalValue()).isEqualByComparingTo(tick.path("navAfter").decimalValue());
  putJson(lab+"/funds/"+fund+"/holding-fee-rule",s.token,"{\"minimumHoldingDays\":30,\"earlyFeeRate\":0.100000}",200);UUID buy=id(postJson(base+"/children/"+child+"/funds/"+fund+"/trade-previews",s.token,null,"{\"side\":\"BUY\",\"inputAmount\":20.00}",201));postJson(base+"/fund-trade-previews/"+buy+"/confirm",s.token,"buy-one","",200);JsonNode sell=data(postJson(base+"/children/"+child+"/funds/"+fund+"/trade-previews",s.token,null,"{\"side\":\"SELL\",\"inputAmount\":1.00000000}",201));assertThat(sell.path("holdingDays").asInt()).isZero();assertThat(sell.path("earlyFeeRate").decimalValue()).isEqualByComparingTo("0.100000");assertThat(sell.path("feeAmount").decimalValue()).isGreaterThan(sell.path("earlyFeeAmount").decimalValue());
  UUID cosmetic=UUID.fromString(data(postJson(lab+"/cosmetics",s.token,null,"{\"title\":\"星空书桌主题\",\"coinCost\":12,\"stockCount\":20}",201)).asText());assertThat(jdbc.queryForObject("SELECT product_kind FROM reward_product WHERE id=?",String.class,cosmetic)).isEqualTo("COSMETIC");mvc.perform(get(lab).header("Authorization",bearer(s.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.notice").isNotEmpty());
 }
 private Session bootstrap()throws Exception{JsonNode d=data(mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\"经济实验家庭\",\"parentName\":\"家长\",\"pin\":\"731946\"}")).andExpect(status().isCreated()).andReturn());return new Session(UUID.fromString(d.path("familyId").asText()),d.path("session").path("token").asText());}private UUID child(Session s)throws Exception{return id(postJson("/api/v1/families/"+s.family+"/children",s.token,null,"{\"displayName\":\"小禾\",\"birthDate\":\"2014-01-01\",\"ageStage\":\"PRETEEN_10_12\"}",201));}private void adjust(Session s,UUID c,String asset,String delta,String key)throws Exception{postJson("/api/v1/families/"+s.family+"/children/"+c+"/wallet/adjustments",s.token,key,"{\"assetType\":\""+asset+"\",\"delta\":"+delta+",\"reason\":\"经济实验初始值\"}",200);}private MvcResult postJson(String path,String token,String key,String body,int status)throws Exception{var b=post(path).header("Authorization",bearer(token));if(key!=null)b.header("Idempotency-Key",key);if(!body.isEmpty())b.contentType(MediaType.APPLICATION_JSON).content(body);return mvc.perform(b).andExpect(status().is(status)).andReturn();}private void putJson(String path,String token,String body,int status)throws Exception{mvc.perform(put(path).header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().is(status));}private JsonNode data(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString()).path("data");}private UUID id(MvcResult r)throws Exception{return UUID.fromString(data(r).path("id").asText());}private static String bearer(String t){return "Bearer "+t;}private record Session(UUID family,String token){}
}
