package com.familygrowth;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.*;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;
@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage7api;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate"}) @AutoConfigureMockMvc @ActiveProfiles("test") class Stage7ApiTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @Test void simulatedFundSupportsAgeGateFeesDriftConcurrencyAndPnl()throws Exception{
  Session p=bootstrap();UUID child=child(p,"大树","2016-01-01","CHILD_6_9"),young=child(p,"小芽","2022-01-01","EARLY_CHILDHOOD_2_5");String ct=childToken(p,child),yt=childToken(p,young);adjust(p,child,100);
  String funds="/api/v1/families/"+p.family+"/funds";UUID fund=id(mvc.perform(post(funds).header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"家庭成长模拟池\",\"riskLabel\":\"会涨也会跌\"}")) .andExpect(status().isCreated()).andExpect(jsonPath("$.data.notice").isNotEmpty()).andReturn());
  addNav(p,fund,"2026-08-25","1.000000",201);rule(p,fund,"0.050000","0.020000",201);
  String youngPreview=previewUrl(p,young,fund);mvc.perform(post(youngPreview).header("Authorization",bearer(yt)).contentType(MediaType.APPLICATION_JSON).content("{\"side\":\"BUY\",\"inputAmount\":20.00}")) .andExpect(status().isForbidden());
  String previews=previewUrl(p,child,fund);UUID buy=preview(ct,previews,"BUY","20.00",20,1,19);String buyConfirm=confirmUrl(p,buy);mvc.perform(post(buyConfirm).header("Authorization",bearer(ct)).header("Idempotency-Key","fund-buy-1")) .andExpect(status().isOk());mvc.perform(post(buyConfirm).header("Authorization",bearer(ct)).header("Idempotency-Key","fund-buy-1")) .andExpect(status().isOk());
  mvc.perform(get(positionUrl(p,child,fund)).header("Authorization",bearer(ct))).andExpect(status().isOk()).andExpect(jsonPath("$.data.shares").value(19.0)).andExpect(jsonPath("$.data.totalCost").value(20.0)).andExpect(jsonPath("$.data.unrealizedPnl").value(-1.0));
  UUID raced=preview(ct,previews,"BUY","10.00",10,.5,9.5);String raceUrl=confirmUrl(p,raced);var pool=Executors.newFixedThreadPool(2);var start=new CountDownLatch(1);try{var a=pool.submit(()->{start.await();return confirmStatus(raceUrl,ct,"fund-race-a");});var b=pool.submit(()->{start.await();return confirmStatus(raceUrl,ct,"fund-race-b");});start.countDown();assertThat(Set.of(a.get(),b.get())).containsExactlyInAnyOrder(200,409);}finally{pool.shutdownNow();}
  UUID staleNav=preview(ct,previews,"SELL","1.00000000",1,.02,1);addNav(p,fund,"2026-08-26","1.100000",201);mvc.perform(post(confirmUrl(p,staleNav)).header("Authorization",bearer(ct)).header("Idempotency-Key","stale-nav")) .andExpect(status().isConflict());
  UUID staleRule=preview(ct,previews,"BUY","1.00",1,.05,.86363636);rule(p,fund,"0.040000","0.010000",201);mvc.perform(post(confirmUrl(p,staleRule)).header("Authorization",bearer(ct)).header("Idempotency-Key","stale-rule")) .andExpect(status().isConflict());
  UUID sell=preview(ct,previews,"SELL","5.00000000",5.5,.06,5);mvc.perform(post(confirmUrl(p,sell)).header("Authorization",bearer(ct)).header("Idempotency-Key","fund-sell-1")) .andExpect(status().isOk()).andExpect(jsonPath("$.data.netMoney").value(5.44));
  UUID over=preview(ct,previews,"SELL","999.00000000",1098.9,10.99,999);mvc.perform(post(confirmUrl(p,over)).header("Authorization",bearer(ct)).header("Idempotency-Key","fund-oversell")) .andExpect(status().isConflict());
  addNav(p,fund,"2026-08-27","0.990000",201);addNav(p,fund,"2026-08-27","0.990000",409);mvc.perform(get(positionUrl(p,child,fund)).header("Authorization",bearer(p.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.shares").value(23.5)).andExpect(jsonPath("$.data.unrealizedPnl").value(-1.48)).andExpect(jsonPath("$.data.realizedPnl").value(.18));
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM fund_trade_order WHERE family_id=?",Integer.class,p.family)).isEqualTo(3);
 }
 private UUID preview(String token,String url,String side,String input,double gross,double fee,double shares)throws Exception{return id(mvc.perform(post(url).header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content("{\"side\":\""+side+"\",\"inputAmount\":"+input+"}")) .andExpect(status().isCreated()).andExpect(jsonPath("$.data.grossMoney").value(gross)).andExpect(jsonPath("$.data.feeAmount").value(fee)).andExpect(jsonPath("$.data.shares").value(shares)).andExpect(jsonPath("$.data.notice").isNotEmpty()).andReturn());}
 private void addNav(Session p,UUID fund,String date,String nav,int status)throws Exception{mvc.perform(post("/api/v1/families/"+p.family+"/funds/"+fund+"/nav").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"navDate\":\""+date+"\",\"nav\":"+nav+"}")) .andExpect(status==201?status().isCreated():status().isConflict());}
 private void rule(Session p,UUID fund,String buy,String sell,int expected)throws Exception{mvc.perform(post("/api/v1/families/"+p.family+"/funds/"+fund+"/fee-rules").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"buyFeeRate\":"+buy+",\"sellFeeRate\":"+sell+"}")) .andExpect(expected==201?status().isCreated():status().isConflict());}
 private UUID child(Session p,String name,String birth,String age)throws Exception{return id(mvc.perform(post("/api/v1/families/"+p.family+"/children").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\""+name+"\",\"birthDate\":\""+birth+"\",\"ageStage\":\""+age+"\"}")) .andExpect(status().isCreated()).andReturn());}
 private String childToken(Session p,UUID child)throws Exception{return text(mvc.perform(post("/api/v1/auth/child-sessions").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"childId\":\""+child+"\"}")) .andExpect(status().isCreated()).andReturn(),"data","token");}
 private void adjust(Session p,UUID child,int amount)throws Exception{mvc.perform(post("/api/v1/families/"+p.family+"/children/"+child+"/wallet/adjustments").header("Authorization",bearer(p.token)).header("Idempotency-Key","stage7-money").contentType(MediaType.APPLICATION_JSON).content("{\"assetType\":\"MONEY\",\"delta\":"+amount+",\"reason\":\"Stage7 fixture\"}")) .andExpect(status().isOk());}
 private int confirmStatus(String url,String token,String key)throws Exception{return mvc.perform(post(url).header("Authorization",bearer(token)).header("Idempotency-Key",key)).andReturn().getResponse().getStatus();}private String previewUrl(Session p,UUID c,UUID f){return "/api/v1/families/"+p.family+"/children/"+c+"/funds/"+f+"/trade-previews";}private String confirmUrl(Session p,UUID id){return "/api/v1/families/"+p.family+"/fund-trade-previews/"+id+"/confirm";}private String positionUrl(Session p,UUID c,UUID f){return "/api/v1/families/"+p.family+"/children/"+c+"/funds/"+f+"/position";}
 private Session bootstrap()throws Exception{MvcResult r=mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\"Stage7家庭\",\"parentName\":\"家长\",\"pin\":\"357913\"}")) .andExpect(status().isCreated()).andReturn();return new Session(UUID.fromString(text(r,"data","familyId")),text(r,"data","session","token"));}private UUID id(MvcResult r)throws Exception{return UUID.fromString(text(r,"data","id"));}private String text(MvcResult r,String...path)throws Exception{JsonNode n=json.readTree(r.getResponse().getContentAsString());for(String x:path)n=n.path(x);return n.asText();}private static String bearer(String t){return "Bearer "+t;}private record Session(UUID family,String token){}
}
