package com.familygrowth;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.*;
import java.time.temporal.TemporalAdjusters;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.*;

@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage25senior;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate"})
@AutoConfigureMockMvc @ActiveProfiles("test")
class Stage25SeniorLearningApiTest {
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @Test void familyConfiguresModulesWhileChildOwnsGoalsAndImmutableReflections()throws Exception{
  Session parent=bootstrap("高中研究家庭","852741"),other=bootstrap("高中隔离家庭","852742");UUID child=child(parent,"研究同学","2010-03-02"),otherChild=child(other,"另一同学","2010-02-02");String childToken=childToken(parent,child);
  String base="/api/v1/families/"+parent.family+"/children/"+child+"/senior-learning";
  String modules="{\"selections\":[{\"subjectCode\":\"MATH\",\"moduleType\":\"REQUIRED\"},{\"subjectCode\":\"PHYSICS\",\"moduleType\":\"SELECTIVE_REQUIRED\"}],\"expectedRevision\":0,\"reason\":\"按当前真实课程组合配置\"}";
  mvc.perform(put(base+"/modules").header("Authorization",bearer(parent.token)).header("Idempotency-Key","senior-modules").contentType(MediaType.APPLICATION_JSON).content(modules)).andExpect(status().isOk()).andExpect(jsonPath("$.data.revision").value(1)).andExpect(jsonPath("$.data.selections.length()").value(2));
  mvc.perform(put(base+"/modules").header("Authorization",bearer(parent.token)).header("Idempotency-Key","senior-modules").contentType(MediaType.APPLICATION_JSON).content(modules)).andExpect(status().isOk()).andExpect(jsonPath("$.data.revision").value(1));
  mvc.perform(put(base+"/modules").header("Authorization",bearer(parent.token)).header("Idempotency-Key","senior-modules-stale").contentType(MediaType.APPLICATION_JSON).content(modules)).andExpect(status().isConflict());
  mvc.perform(put(base+"/modules").header("Authorization",bearer(childToken)).header("Idempotency-Key","child-modules").contentType(MediaType.APPLICATION_JSON).content(modules)).andExpect(status().isForbidden());
  JsonNode version=publish(parent);mvc.perform(post("/api/v1/families/"+parent.family+"/children/"+child+"/autonomous-learning/sync").header("Authorization",bearer(childToken)).header("Idempotency-Key","senior-sync")).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].seniorMetadata.moduleType").value("REQUIRED")).andExpect(jsonPath("$.data[0].seniorMetadata.topicTitle").value("变化率专题"));
  UUID assignment=jdbc.queryForObject("SELECT id FROM lesson_assignment WHERE family_id=? AND child_id=?",UUID.class,parent.family,child);String monday=LocalDate.now().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)).toString();
  String create="{\"assignmentId\":\""+assignment+"\",\"module\":{\"subjectCode\":\"MATH\",\"moduleType\":\"REQUIRED\"},\"weekStart\":\""+monday+"\",\"title\":\"解释变化率\",\"evidenceTarget\":\"一张数据表和一段解释\",\"nextAction\":\"先整理四组数据\"}";
  JsonNode goal=data(mvc.perform(post(base+"/goals").header("Authorization",bearer(childToken)).header("Idempotency-Key","senior-goal").contentType(MediaType.APPLICATION_JSON).content(create)).andExpect(status().isOk()).andExpect(jsonPath("$.data.revision").value(0)).andReturn());UUID goalId=UUID.fromString(goal.path("id").asText());
  mvc.perform(post(base+"/goals").header("Authorization",bearer(childToken)).header("Idempotency-Key","senior-goal").contentType(MediaType.APPLICATION_JSON).content(create)).andExpect(status().isOk()).andExpect(jsonPath("$.data.id").value(goalId.toString()));
  mvc.perform(post(base+"/goals").header("Authorization",bearer(parent.token)).header("Idempotency-Key","parent-goal").contentType(MediaType.APPLICATION_JSON).content(create)).andExpect(status().isForbidden());
  String update="{\"title\":\"解释变化率与误差\",\"evidenceTarget\":\"数据表、图像和解释\",\"nextAction\":\"比较两种表示\",\"expectedRevision\":0}";
  mvc.perform(put(base+"/goals/"+goalId).header("Authorization",bearer(childToken)).header("Idempotency-Key","goal-update").contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isOk()).andExpect(jsonPath("$.data.revision").value(1));
  mvc.perform(put(base+"/goals/"+goalId).header("Authorization",bearer(childToken)).header("Idempotency-Key","goal-stale").contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isConflict());
  String reflect="{\"goalId\":\""+goalId+"\",\"assignmentId\":\""+assignment+"\",\"evidenceSummary\":\"已经整理四组数据，图像仍需补充单位\",\"strategy\":\"ASK_FOR_SUPPORT\",\"nextAction\":\"请家长一起检查坐标单位\",\"supportRequested\":true}";
  mvc.perform(post(base+"/reflections").header("Authorization",bearer(childToken)).header("Idempotency-Key","senior-reflect").contentType(MediaType.APPLICATION_JSON).content(reflect)).andExpect(status().isOk()).andExpect(jsonPath("$.data.supportRequested").value(true));
  mvc.perform(post(base+"/reflections").header("Authorization",bearer(childToken)).header("Idempotency-Key","senior-reflect").contentType(MediaType.APPLICATION_JSON).content(reflect)).andExpect(status().isOk());
  mvc.perform(post(base+"/goals/"+goalId+"/archive").header("Authorization",bearer(childToken)).header("Idempotency-Key","goal-archive").contentType(MediaType.APPLICATION_JSON).content("{\"expectedRevision\":1}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("ARCHIVED"));
  mvc.perform(get(base+"/report").header("Authorization",bearer(parent.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.archivedGoals").value(1)).andExpect(jsonPath("$.data.reflections").value(1)).andExpect(jsonPath("$.data.supportRequests").value(1));
  mvc.perform(get(base+"/report").header("Authorization",bearer(childToken))).andExpect(status().isForbidden());
  mvc.perform(get(base.replace(parent.family.toString(),other.family.toString()).replace(child.toString(),otherChild.toString())+"/goals").header("Authorization",bearer(parent.token))).andExpect(status().isNotFound());
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM senior_module_action WHERE family_id=?",Integer.class,parent.family)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM senior_goal_action WHERE family_id=?",Integer.class,parent.family)).isEqualTo(3);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM senior_reflection WHERE family_id=?",Integer.class,parent.family)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_entry WHERE family_id=?",Integer.class,parent.family)).isZero();assertThat(version.path("status").asText()).isEqualTo("PUBLISHED");
 }
 @Test void concurrentGoalUpdatesCommitExactlyOneRevision()throws Exception{Session p=bootstrap("高中目标并发家庭","951753");UUID child=child(p,"并发同学","2010-04-02");String token=childToken(p,child),base="/api/v1/families/"+p.family+"/children/"+child+"/senior-learning";String modules="{\"selections\":[{\"subjectCode\":\"MATH\",\"moduleType\":\"REQUIRED\"}],\"expectedRevision\":0,\"reason\":\"并发测试配置\"}";mvc.perform(put(base+"/modules").header("Authorization",bearer(p.token)).header("Idempotency-Key","race-modules").contentType(MediaType.APPLICATION_JSON).content(modules)).andExpect(status().isOk());String monday=LocalDate.now().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)).toString();String create="{\"module\":{\"subjectCode\":\"MATH\",\"moduleType\":\"REQUIRED\"},\"weekStart\":\""+monday+"\",\"title\":\"并发目标\",\"evidenceTarget\":\"一份过程记录\",\"nextAction\":\"开始第一步\"}";UUID goal=UUID.fromString(data(mvc.perform(post(base+"/goals").header("Authorization",bearer(token)).header("Idempotency-Key","race-goal").contentType(MediaType.APPLICATION_JSON).content(create)).andExpect(status().isOk()).andReturn()).path("id").asText());var pool=Executors.newFixedThreadPool(2);try{Callable<Integer>a=()->updateStatus(base,goal,token,"race-a","方法一");Callable<Integer>b=()->updateStatus(base,goal,token,"race-b","方法二");var statuses=pool.invokeAll(java.util.List.of(a,b)).stream().map(v->{try{return v.get();}catch(Exception e){throw new RuntimeException(e);}}).toList();assertThat(statuses).containsExactlyInAnyOrder(200,409);}finally{pool.shutdownNow();}assertThat(jdbc.queryForObject("SELECT revision FROM senior_weekly_goal WHERE id=?",Long.class,goal)).isEqualTo(1L);}
 private int updateStatus(String base,UUID goal,String token,String key,String next)throws Exception{return mvc.perform(put(base+"/goals/"+goal).header("Authorization",bearer(token)).header("Idempotency-Key",key).contentType(MediaType.APPLICATION_JSON).content("{\"title\":\"并发目标\",\"evidenceTarget\":\"一份过程记录\",\"nextAction\":\""+next+"\",\"expectedRevision\":0}")).andReturn().getResponse().getStatus();}
 private JsonNode publish(Session p)throws Exception{String body="{\"schoolStage\":\"SENIOR_HIGH\",\"subjectCode\":\"MATH\",\"title\":\"变化率研究\",\"version\":{\"summary\":\"从数据建立解释\",\"rightsBasis\":\"Family Growth 原创高中活动\",\"units\":[{\"title\":\"函数模块\",\"lessons\":[{\"title\":\"变化率与证据\",\"summary\":\"用数据和图像解释\",\"moduleType\":\"REQUIRED\",\"topicTitle\":\"变化率专题\",\"inquiryQuestion\":\"怎样用数据解释变化快慢\",\"expectedEvidence\":\"数据表、图像和文字解释\",\"seniorSafetyNote\":\"只使用纸笔或安全的日常测量\",\"activities\":[{\"type\":\"OFFLINE_PRACTICE\",\"title\":\"整理证据\",\"instruction\":\"记录安全日常情境的四组数据并解释\",\"expectedMinutes\":25}]}]}]}}";JsonNode created=data(mvc.perform(post("/api/v1/families/"+p.family+"/teaching/courses").header("Authorization",bearer(p.token)).header("Idempotency-Key","senior-course").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andReturn());return data(mvc.perform(post("/api/v1/families/"+p.family+"/teaching/course-versions/"+created.path("versionId").asText()+"/publish").header("Authorization",bearer(p.token)).header("Idempotency-Key","senior-publish")).andExpect(status().isOk()).andReturn());}
 private Session bootstrap(String name,String pin)throws Exception{JsonNode d=data(mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\""+name+"\",\"parentName\":\"家长\",\"pin\":\""+pin+"\"}")).andExpect(status().isCreated()).andReturn());return new Session(UUID.fromString(d.path("familyId").asText()),d.path("session").path("token").asText());}
 private UUID child(Session p,String name,String birth)throws Exception{return UUID.fromString(data(mvc.perform(post("/api/v1/families/"+p.family+"/children").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\""+name+"\",\"birthDate\":\""+birth+"\",\"ageStage\":\"TEEN_13_PLUS\"}")).andExpect(status().isCreated()).andReturn()).path("id").asText());}
 private String childToken(Session p,UUID child)throws Exception{return data(mvc.perform(post("/api/v1/auth/child-sessions").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"childId\":\""+child+"\"}")).andExpect(status().isCreated()).andReturn()).path("token").asText();}
 private JsonNode data(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString()).path("data");}private static String bearer(String v){return "Bearer "+v;}private record Session(UUID family,String token){}
}
