package com.familygrowth;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import com.familygrowth.application.Stage26RetentionService;import java.time.*;import java.util.UUID;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage26retention;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate","family-growth.retention.initial-delay-ms=86400000"})@AutoConfigureMockMvc@ActiveProfiles("test")class Stage26RetentionApiTest{@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;@Autowired Stage26RetentionService retention;
 @Test void parentConfiguresAndSchedulerDeletesOnlyExpiredNonFinancialDetail()throws Exception{Session p=bootstrap("保留家庭","741852");UUID child=id(call(post("/api/v1/families/"+p.family+"/children"),p.token,"{\"displayName\":\"保留孩子\",\"birthDate\":\"2015-01-01\",\"ageStage\":\"CHILD_6_9\"}",null,201));String childToken=text(call(post("/api/v1/auth/child-sessions"),p.token,"{\"childId\":\""+child+"\"}",null,201),"data","token");String base="/api/v1/families/"+p.family+"/children/"+child+"/data-rights";
  mvc.perform(get(base+"/retention-policy").header("Authorization",bearer(p.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.usageDetailDays").value(90)).andExpect(jsonPath("$.data.version").value(0));call(put(base+"/retention-policy"),p.token,"{\"usageDetailDays\":30,\"expectedVersion\":0,\"reason\":\"家庭选择最短允许保留期\"}",null,200);mvc.perform(get(base+"/retention-policy").header("Authorization",bearer(childToken))).andExpect(status().isForbidden());
  UUID old=usage(p.family,child,Instant.now().minus(Duration.ofDays(40)),"old-usage"),recent=usage(p.family,child,Instant.now().minus(Duration.ofDays(2)),"recent-usage");int ledgerBefore=count("SELECT COUNT(*) FROM ledger_entry WHERE family_id=? AND child_id=?",p.family,child);retention.scheduled();assertThat(count("SELECT COUNT(*) FROM usage_event WHERE id=?",old)).isZero();assertThat(count("SELECT COUNT(*) FROM usage_event WHERE id=?",recent)).isOne();assertThat(count("SELECT COUNT(*) FROM ledger_entry WHERE family_id=? AND child_id=?",p.family,child)).isEqualTo(ledgerBefore);assertThat(count("SELECT COUNT(*) FROM child_data_retention_run WHERE family_id=? AND child_id=? AND trigger_type='SCHEDULED'",p.family,child)).isOne();assertThat(count("SELECT COUNT(*) FROM child_data_retention_policy_action WHERE family_id=? AND child_id=?",p.family,child)).isOne();
 }
 private UUID usage(UUID family,UUID child,Instant at,String key){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO usage_event(id,family_id,child_id,event_type,minutes,occurred_at,idempotency_key,actor_id,created_at) VALUES(?,?,?,'APP_ACTIVE',1,?,?,?,CURRENT_TIMESTAMP)",id,family,child,java.sql.Timestamp.from(at),key,child);return id;}private int count(String q,Object...a){return jdbc.queryForObject(q,Integer.class,a);}private Session bootstrap(String n,String pin)throws Exception{MvcResult r=mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\""+n+"\",\"parentName\":\"家长\",\"pin\":\""+pin+"\"}")).andExpect(status().isCreated()).andReturn();return new Session(UUID.fromString(text(r,"data","familyId")),text(r,"data","session","token"));}private MvcResult call(MockHttpServletRequestBuilder r,String token,String body,String key,int status)throws Exception{r.header("Authorization",bearer(token));if(key!=null)r.header("Idempotency-Key",key);if(!body.isEmpty())r.contentType(MediaType.APPLICATION_JSON).content(body);return mvc.perform(r).andExpect(status().is(status)).andReturn();}private UUID id(MvcResult r)throws Exception{return UUID.fromString(text(r,"data","id"));}private String text(MvcResult r,String...p)throws Exception{JsonNode n=json.readTree(r.getResponse().getContentAsString());for(String s:p)n=n.path(s);return n.asText();}private static String bearer(String t){return"Bearer "+t;}private record Session(UUID family,String token){}
}
