package com.familygrowth;
import static org.assertj.core.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;
@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage28reward;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate"})@AutoConfigureMockMvc@ActiveProfiles("test")class Stage28RewardGovernanceApiTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @Test void budgetsExchangeApprovalsAndFulfillmentStayExplicitAndAtomic()throws Exception{Session p=bootstrap("奖励治理家庭","731946"),other=bootstrap("隔离家庭","731947");UUID child=child(p,"小约定"),otherChild=child(other,"另一孩子");String ct=childToken(p,child),budget=base(p,child)+"/reward-budget-rules";
  String coinRule="{\"zoneId\":\"Asia/Shanghai\",\"dailyMoneyLimit\":5.00,\"weeklyMoneyLimit\":5.00,\"monthlyMoneyLimit\":5.00,\"overflowPolicy\":\"CONVERT_TO_COIN\",\"excessCoinPerMoney\":2.000000,\"excessXpPerMoney\":0.000000}";
  mvc.perform(post(budget).header("Authorization",bearer(p.token)).header("Idempotency-Key","budget-coin-1").contentType(MediaType.APPLICATION_JSON).content(coinRule)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.version").value(1));
  mvc.perform(post(budget).header("Authorization",bearer(p.token)).header("Idempotency-Key","budget-coin-1").contentType(MediaType.APPLICATION_JSON).content(coinRule)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.id").exists());
  UUID first=completion(p,child,ct,"budget-task-a");review(p,first,"budget-review-a","{\"approved\":true,\"xpReward\":0,\"coinReward\":1,\"moneyReward\":8.00,\"reviewNote\":\"按家庭预算结算\"}",200);
  mvc.perform(get(base(p,child)+"/reward-budget-summary").header("Authorization",bearer(p.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.spentToday").value(5.00)).andExpect(jsonPath("$.data.remainingMoney").value(0.00));
  mvc.perform(get(base(p,child)+"/reward-budget-summary").header("Authorization",bearer(ct))).andExpect(status().isForbidden());mvc.perform(get(base(other,otherChild)+"/reward-budget-summary").header("Authorization",bearer(p.token))).andExpect(status().isNotFound());
  assertThat(jdbc.queryForObject("SELECT actual_money FROM reward_budget_decision WHERE completion_id=?",java.math.BigDecimal.class,first)).isEqualByComparingTo("5.00");assertThat(jdbc.queryForObject("SELECT actual_coin FROM reward_budget_decision WHERE completion_id=?",Long.class,first)).isEqualTo(7L);
  String holdRule="{\"zoneId\":\"Asia/Shanghai\",\"dailyMoneyLimit\":5.00,\"weeklyMoneyLimit\":5.00,\"monthlyMoneyLimit\":5.00,\"overflowPolicy\":\"HOLD_FOR_PARENT\",\"excessCoinPerMoney\":0.000000,\"excessXpPerMoney\":0.000000}";mvc.perform(post(budget).header("Authorization",bearer(p.token)).header("Idempotency-Key","budget-hold-1").contentType(MediaType.APPLICATION_JSON).content(holdRule)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.version").value(2));
  UUID held=completion(p,child,ct,"budget-task-b");String heldReward="{\"approved\":true,\"xpReward\":0,\"coinReward\":0,\"moneyReward\":2.00,\"reviewNote\":\"需要明确覆盖\"}";review(p,held,"budget-review-held",heldReward,409);
  mvc.perform(post(base(p,child)+"/reward-budget-overrides").header("Authorization",bearer(p.token)).header("Idempotency-Key","budget-override-1").contentType(MediaType.APPLICATION_JSON).content("{\"completionId\":\""+held+"\",\"xp\":0,\"coin\":0,\"money\":2.00,\"reason\":\"本次家庭共同约定的特别奖励\"}")).andExpect(status().isCreated());review(p,held,"budget-review-held-2",heldReward,200);assertThat(jdbc.queryForObject("SELECT consumed_at IS NOT NULL FROM reward_budget_override WHERE completion_id=?",Boolean.class,held)).isTrue();
  adjust(p,child,"MONEY",50,"stage28-money");adjust(p,child,"COIN",100,"stage28-coin");mvc.perform(post("/api/v1/families/"+p.family+"/exchange-rules").header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"moneyToCoinRate\":10,\"coinToMoneyRate\":10,\"moneyToCoinFeeRate\":0,\"coinToMoneyFeeRate\":0,\"maxSourceAmount\":1000.00}")).andExpect(status().isCreated());
  String control="/api/v1/families/"+p.family+"/exchange-control-rules",controlBody="{\"moneyToCoinEnabled\":true,\"coinToMoneyEnabled\":false,\"moneyToCoinDailyLimit\":10.00,\"moneyToCoinMonthlyLimit\":20.00,\"coinToMoneyDailyLimit\":0.00,\"coinToMoneyMonthlyLimit\":0.00,\"childRequiresParentApproval\":true,\"zoneId\":\"Asia/Shanghai\"}";mvc.perform(post(control).header("Authorization",bearer(p.token)).header("Idempotency-Key","exchange-control-1").contentType(MediaType.APPLICATION_JSON).content(controlBody)).andExpect(status().isCreated());mvc.perform(get(control+"/active").header("Authorization",bearer(ct))).andExpect(status().isOk()).andExpect(jsonPath("$.data.childRequiresParentApproval").value(true));
  String previews=base(p,child)+"/exchange-previews";UUID preview=id(mvc.perform(post(previews).header("Authorization",bearer(ct)).contentType(MediaType.APPLICATION_JSON).content("{\"direction\":\"MONEY_TO_COIN\",\"sourceAmount\":6.00}")).andExpect(status().isCreated()).andReturn());String confirm="/api/v1/families/"+p.family+"/exchange-previews/"+preview+"/confirm";mvc.perform(post(confirm).header("Authorization",bearer(ct)).header("Idempotency-Key","child-direct-denied")).andExpect(status().isForbidden());
  UUID approval=id(mvc.perform(post(base(p,child)+"/exchange-approval-requests").header("Authorization",bearer(ct)).header("Idempotency-Key","exchange-request-1").contentType(MediaType.APPLICATION_JSON).content("{\"previewId\":\""+preview+"\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("PENDING")).andReturn());mvc.perform(get(base(p,child)+"/exchange-approval-requests").header("Authorization",bearer(ct))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].id").value(approval.toString()));mvc.perform(get(base(other,otherChild)+"/exchange-approval-requests").header("Authorization",bearer(p.token))).andExpect(status().isNotFound());assertThat(exchangeOrders(p)).isZero();
  String approvalReview="/api/v1/families/"+p.family+"/exchange-approval-requests/"+approval+"/review";mvc.perform(post(approvalReview).header("Authorization",bearer(p.token)).header("Idempotency-Key","exchange-approve-1").contentType(MediaType.APPLICATION_JSON).content("{\"approved\":true,\"note\":\"一起确认兑换用途\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("APPROVED"));assertThat(exchangeOrders(p)).isOne();
  mvc.perform(post(previews).header("Authorization",bearer(ct)).contentType(MediaType.APPLICATION_JSON).content("{\"direction\":\"MONEY_TO_COIN\",\"sourceAmount\":5.00}")).andExpect(status().isConflict());mvc.perform(post(previews).header("Authorization",bearer(ct)).contentType(MediaType.APPLICATION_JSON).content("{\"direction\":\"COIN_TO_MONEY\",\"sourceAmount\":1.00}")).andExpect(status().isConflict());
  UUID rejectedPreview=id(mvc.perform(post(previews).header("Authorization",bearer(ct)).contentType(MediaType.APPLICATION_JSON).content("{\"direction\":\"MONEY_TO_COIN\",\"sourceAmount\":2.00}")).andExpect(status().isCreated()).andReturn());UUID rejectedRequest=id(mvc.perform(post(base(p,child)+"/exchange-approval-requests").header("Authorization",bearer(ct)).header("Idempotency-Key","exchange-request-2").contentType(MediaType.APPLICATION_JSON).content("{\"previewId\":\""+rejectedPreview+"\"}")).andExpect(status().isCreated()).andReturn());mvc.perform(post("/api/v1/families/"+p.family+"/exchange-approval-requests/"+rejectedRequest+"/review").header("Authorization",bearer(p.token)).header("Idempotency-Key","exchange-reject-1").contentType(MediaType.APPLICATION_JSON).content("{\"approved\":false,\"note\":\"这次先不兑换\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("REJECTED"));assertThat(exchangeOrders(p)).isOne();
  UUID raceA=id(mvc.perform(post(previews).header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"direction\":\"MONEY_TO_COIN\",\"sourceAmount\":4.00}")).andExpect(status().isCreated()).andReturn()),raceB=id(mvc.perform(post(previews).header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"direction\":\"MONEY_TO_COIN\",\"sourceAmount\":4.00}")).andExpect(status().isCreated()).andReturn());var pool=Executors.newFixedThreadPool(2);var start=new CountDownLatch(1);try{var a=pool.submit(()->{start.await();return confirmStatus(p,raceA,"quota-race-a");});var b=pool.submit(()->{start.await();return confirmStatus(p,raceB,"quota-race-b");});start.countDown();assertThat(Set.of(a.get(),b.get())).containsExactlyInAnyOrder(200,409);}finally{pool.shutdownNow();}assertThat(exchangeOrders(p)).isEqualTo(2);
  String products="/api/v1/families/"+p.family+"/reward-products";UUID product=id(mvc.perform(post(products).header("Authorization",bearer(p.token)).contentType(MediaType.APPLICATION_JSON).content("{\"title\":\"周末一起搭帐篷\",\"coinCost\":20,\"stockCount\":2,\"active\":true}")).andExpect(status().isCreated()).andReturn());UUID order=id(mvc.perform(post(base(p,child)+"/reward-orders").header("Authorization",bearer(ct)).header("Idempotency-Key","fulfill-order-1").contentType(MediaType.APPLICATION_JSON).content("{\"productId\":\""+product+"\"}")).andExpect(status().isCreated()).andReturn());mvc.perform(post("/api/v1/families/"+p.family+"/reward-orders/"+order+"/review").header("Authorization",bearer(p.token)).header("Idempotency-Key","fulfill-review-1").contentType(MediaType.APPLICATION_JSON).content("{\"approved\":true}")).andExpect(status().isOk());int ledgers=ledgerCount(p,child);String fulfill="/api/v1/families/"+p.family+"/reward-orders/"+order+"/fulfill";mvc.perform(post(fulfill).header("Authorization",bearer(ct)).header("Idempotency-Key","fulfill-denied").contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"孩子不能自行确认\"}")).andExpect(status().isForbidden());mvc.perform(post(fulfill).header("Authorization",bearer(p.token)).header("Idempotency-Key","fulfill-1").contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"周六全家已经一起完成\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.note").value("周六全家已经一起完成"));mvc.perform(post(fulfill).header("Authorization",bearer(p.token)).header("Idempotency-Key","fulfill-1").contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"周六全家已经一起完成\"}")).andExpect(status().isOk());assertThat(ledgerCount(p,child)).isEqualTo(ledgers);assertThat(jdbc.queryForObject("SELECT status FROM reward_order WHERE id=?",String.class,order)).isEqualTo("FULFILLED");
 }
 private UUID completion(Session p,UUID child,String ct,String key)throws Exception{UUID plan=id(postJson("/api/v1/families/"+p.family+"/children/"+child+"/plans",p.token,null,"{\"title\":\""+key+"计划\",\"startDate\":\"2026-08-31\"}",201));UUID goal=id(postJson("/api/v1/families/"+p.family+"/plans/"+plan+"/goals",p.token,null,"{\"title\":\""+key+"目标\"}",201));UUID task=id(postJson("/api/v1/families/"+p.family+"/goals/"+goal+"/tasks",p.token,null,"{\"title\":\""+key+"任务\",\"category\":\"CHORE\",\"difficulty\":\"NORMAL\",\"expectedMinutes\":5}",201));return id(postJson("/api/v1/families/"+p.family+"/children/"+child+"/tasks/"+task+"/completions",ct,key+"-submit","{\"evidenceNote\":\"完成一个现实行动\"}",201));}
 private void review(Session p,UUID completion,String key,String body,int expected)throws Exception{postJson("/api/v1/families/"+p.family+"/completions/"+completion+"/review",p.token,key,body,expected);}private MvcResult postJson(String url,String token,String key,String body,int expected)throws Exception{var b=post(url).header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content(body);if(key!=null)b.header("Idempotency-Key",key);return mvc.perform(b).andExpect(status().is(expected)).andReturn();}
 private void adjust(Session p,UUID c,String asset,int amount,String key)throws Exception{postJson(base(p,c)+"/wallet/adjustments",p.token,key,"{\"assetType\":\""+asset+"\",\"delta\":"+amount+",\"reason\":\"Stage28 fixture\"}",200);}private int confirmStatus(Session p,UUID preview,String key)throws Exception{return mvc.perform(post("/api/v1/families/"+p.family+"/exchange-previews/"+preview+"/confirm").header("Authorization",bearer(p.token)).header("Idempotency-Key",key)).andReturn().getResponse().getStatus();}private int exchangeOrders(Session p){return jdbc.queryForObject("SELECT COUNT(*) FROM exchange_order WHERE family_id=?",Integer.class,p.family);}private int ledgerCount(Session p,UUID c){return jdbc.queryForObject("SELECT COUNT(*) FROM ledger_entry WHERE family_id=? AND child_id=?",Integer.class,p.family,c);}
 private Session bootstrap(String name,String pin)throws Exception{JsonNode d=data(mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\""+name+"\",\"parentName\":\"家长\",\"pin\":\""+pin+"\"}")).andExpect(status().isCreated()).andReturn());return new Session(UUID.fromString(d.path("familyId").asText()),d.path("session").path("token").asText());}private UUID child(Session p,String name)throws Exception{return id(postJson("/api/v1/families/"+p.family+"/children",p.token,null,"{\"displayName\":\""+name+"\",\"birthDate\":\"2018-01-01\",\"ageStage\":\"CHILD_6_9\"}",201));}private String childToken(Session p,UUID c)throws Exception{return data(postJson("/api/v1/auth/child-sessions",p.token,null,"{\"childId\":\""+c+"\"}",201)).path("token").asText();}private JsonNode data(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString()).path("data");}private UUID id(MvcResult r)throws Exception{return UUID.fromString(data(r).path("id").asText());}private String base(Session p,UUID c){return "/api/v1/families/"+p.family+"/children/"+c;}private static String bearer(String t){return "Bearer "+t;}private record Session(UUID family,String token){}
}
