package com.familygrowth;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.*;

@SpringBootTest(properties={"spring.datasource.url=${FAMILY_GROWTH_TEST_POSTGRES_URL:jdbc:h2:mem:stage29collaboration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}","spring.datasource.username=${FAMILY_GROWTH_TEST_POSTGRES_USER:sa}","spring.datasource.password=${FAMILY_GROWTH_TEST_POSTGRES_PASSWORD:}","spring.jpa.hibernate.ddl-auto=validate"}) @AutoConfigureMockMvc @ActiveProfiles("test")
class Stage29CollaborationApiTest {
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @Test void invitationsPairingRevocationChildSwitchingAndInboxStayScoped()throws Exception{
  Session owner=bootstrap("协作家庭","881946"),other=bootstrap("其他家庭","881947");UUID child=child(owner,"小禾"),otherChild=child(other,"其他孩子");String childToken=childToken(owner,child);
  mvc.perform(get(family(owner)+"/members").header("Authorization",bearer(owner.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].role").value("OWNER"));
  MvcResult made=postJson(family(owner)+"/parent-invitations",owner.token,"invite-guardian","{\"invitedName\":\"另一位家长\"}",201);JsonNode invitation=data(made);UUID invitationId=UUID.fromString(invitation.path("invitation").path("id").asText());String invitationCode=invitation.path("oneTimeCode").asText();assertThat(invitationCode).isNotBlank();
  mvc.perform(post(family(owner)+"/parent-invitations").header("Authorization",bearer(owner.token)).header("Idempotency-Key","invite-guardian").contentType(MediaType.APPLICATION_JSON).content("{\"invitedName\":\"另一位家长\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.data.oneTimeCode").isEmpty());
  JsonNode accepted=data(mvc.perform(post("/api/v1/auth/parent-invitations/accept").contentType(MediaType.APPLICATION_JSON).content("{\"code\":\""+invitationCode+"\",\"pin\":\"551946\"}")).andExpect(status().isOk()).andReturn());String guardianToken=accepted.path("token").asText();UUID guardian=UUID.fromString(accepted.path("actor").path("actorId").asText());
  mvc.perform(post("/api/v1/auth/parent-invitations/accept").contentType(MediaType.APPLICATION_JSON).content("{\"code\":\""+invitationCode+"\",\"pin\":\"551946\"}")).andExpect(status().isUnauthorized());
  mvc.perform(post(family(owner)+"/parent-invitations").header("Authorization",bearer(guardianToken)).header("Idempotency-Key","guardian-cannot-invite").contentType(MediaType.APPLICATION_JSON).content("{\"invitedName\":\"不允许\"}")).andExpect(status().isForbidden());
  mvc.perform(get(family(owner)+"/children").header("Authorization",bearer(guardianToken))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].id").value(child.toString()));mvc.perform(get(family(other)+"/children").header("Authorization",bearer(guardianToken))).andExpect(status().isNotFound());
  mvc.perform(post(family(owner)+"/members/"+guardian+"/reset-pin").header("Authorization",bearer(owner.token)).contentType(MediaType.APPLICATION_JSON).content("{\"pin\":\"661946\"}")).andExpect(status().isOk());mvc.perform(get(family(owner)+"/members").header("Authorization",bearer(guardianToken))).andExpect(status().isUnauthorized());login(owner.family,guardian,"551946",401);String guardian2=login(owner.family,guardian,"661946",200);
  mvc.perform(post(family(owner)+"/members/"+owner.parent+"/revoke").header("Authorization",bearer(owner.token))).andExpect(status().isConflict());mvc.perform(post(family(owner)+"/members/"+guardian+"/revoke").header("Authorization",bearer(guardian2))).andExpect(status().isForbidden());
  String parentPair=pair(owner,"PARENT",null,"pair-parent");JsonNode parentPaired=data(mvc.perform(post("/api/v1/auth/device-pairings/accept").contentType(MediaType.APPLICATION_JSON).content("{\"code\":\""+parentPair+"\",\"deviceName\":\"客厅平板\"}")).andExpect(status().isOk()).andReturn());String pairedParentToken=parentPaired.path("session").path("token").asText();UUID parentDevice=UUID.fromString(parentPaired.path("device").path("id").asText());assertThat(parentPaired.path("children").get(0).path("id").asText()).isEqualTo(child.toString());
  mvc.perform(get(family(owner)+"/devices").header("Authorization",bearer(owner.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].deviceName").value("客厅平板"));mvc.perform(post(family(owner)+"/devices/"+parentDevice+"/revoke").header("Authorization",bearer(owner.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("REVOKED"));mvc.perform(get(family(owner)+"/members").header("Authorization",bearer(pairedParentToken))).andExpect(status().isUnauthorized());
  String childPair=pair(owner,"CHILD",child,"pair-child");JsonNode childPaired=data(mvc.perform(post("/api/v1/auth/device-pairings/accept").contentType(MediaType.APPLICATION_JSON).content("{\"code\":\""+childPair+"\",\"deviceName\":\"孩子平板\"}")).andExpect(status().isOk()).andReturn());String pairedChildToken=childPaired.path("session").path("token").asText();mvc.perform(get(family(owner)+"/children").header("Authorization",bearer(pairedChildToken))).andExpect(status().isForbidden());mvc.perform(get(family(owner)+"/notifications").header("Authorization",bearer(pairedChildToken))).andExpect(status().isOk());
  String concurrent=pair(owner,"CHILD",child,"pair-race");ExecutorService pool=Executors.newFixedThreadPool(2);try{var tasks=List.of(callPair(pool,concurrent,"竞态一"),callPair(pool,concurrent,"竞态二"));Set<Integer> statuses=new HashSet<>();for(Future<Integer> result:tasks)statuses.add(result.get(20,TimeUnit.SECONDS));assertThat(statuses).containsExactlyInAnyOrder(200,401);}finally{pool.shutdownNow();}
  UUID completion=completion(owner,child,childToken,"collab-task");postJson(family(owner)+"/completions/"+completion+"/review",owner.token,"collab-review","{\"approved\":true,\"xpReward\":0,\"coinReward\":20,\"moneyReward\":0.00,\"reviewNote\":\"确认现实行动\"}",200);postJson(family(owner)+"/children/"+child+"/tasks/"+taskFor(owner,child,"replay-task")+"/completions",childToken,"replay-submit","{\"evidenceNote\":\"做完了\"}",201);int taskNotices=count(owner,"TASK_REVIEW");assertThat(taskNotices).isGreaterThanOrEqualTo(2);
  UUID product=id(postJson(family(owner)+"/reward-products",owner.token,null,"{\"title\":\"一起去公园\",\"coinCost\":10,\"stockCount\":3,\"active\":true}",201));UUID order=id(postJson(family(owner)+"/children/"+child+"/reward-orders",childToken,"reward-request","{\"productId\":\""+product+"\"}",201));postJson(family(owner)+"/reward-orders/"+order+"/review",owner.token,"reward-review","{\"approved\":true}",200);assertThat(count(owner,"REWARD_REVIEW")).isOne();assertThat(count(owner,"REWARD_FULFILL")).isOne();
  int ledgers=jdbc.queryForObject("SELECT COUNT(*) FROM ledger_entry WHERE family_id=? AND child_id=?",Integer.class,owner.family,child);JsonNode inbox=data(mvc.perform(get(family(owner)+"/notifications").header("Authorization",bearer(owner.token))).andExpect(status().isOk()).andReturn());UUID notice=UUID.fromString(inbox.get(0).path("id").asText());mvc.perform(post(family(owner)+"/notifications/"+notice+"/read").header("Authorization",bearer(owner.token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("READ"));mvc.perform(post(family(other)+"/notifications/"+notice+"/read").header("Authorization",bearer(other.token))).andExpect(status().isNotFound());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_entry WHERE family_id=? AND child_id=?",Integer.class,owner.family,child)).isEqualTo(ledgers);
  mvc.perform(post(family(owner)+"/members/"+guardian+"/revoke").header("Authorization",bearer(owner.token))).andExpect(status().isOk());mvc.perform(get(family(owner)+"/members").header("Authorization",bearer(guardian2))).andExpect(status().isUnauthorized());login(owner.family,guardian,"661946",401);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM family_collaboration_action WHERE family_id=?",Integer.class,owner.family)).isGreaterThan(5);assertThat(completion).isNotNull();assertThat(invitationId).isNotNull();assertThat(otherChild).isNotNull();
 }
 private Future<Integer> callPair(ExecutorService pool,String code,String name){return pool.submit(()->mvc.perform(post("/api/v1/auth/device-pairings/accept").contentType(MediaType.APPLICATION_JSON).content("{\"code\":\""+code+"\",\"deviceName\":\""+name+"\"}")).andReturn().getResponse().getStatus());}
 private String pair(Session s,String role,UUID child,String key)throws Exception{String body="{\"role\":\""+role+"\",\"childId\":"+(child==null?"null":"\""+child+"\"")+"}";JsonNode d=data(postJson(family(s)+"/device-pairings",s.token,key,body,201));assertThat(d.path("trustedHttpsRequired").asBoolean()).isTrue();return d.path("oneTimeCode").asText();}
 private int count(Session s,String type){return jdbc.queryForObject("SELECT COUNT(*) FROM family_notification WHERE family_id=? AND recipient_actor_id=? AND notification_type=?",Integer.class,s.family,s.parent,type);}
 private UUID completion(Session s,UUID child,String token,String key)throws Exception{UUID task=taskFor(s,child,key);return id(postJson(family(s)+"/children/"+child+"/tasks/"+task+"/completions",token,key+"-submit","{\"evidenceNote\":\"完成现实行动\"}",201));}
 private UUID taskFor(Session s,UUID child,String key)throws Exception{UUID plan=id(postJson(family(s)+"/children/"+child+"/plans",s.token,null,"{\"title\":\""+key+"计划\",\"startDate\":\"2026-09-01\"}",201));UUID goal=id(postJson(family(s)+"/plans/"+plan+"/goals",s.token,null,"{\"title\":\""+key+"目标\"}",201));return id(postJson(family(s)+"/goals/"+goal+"/tasks",s.token,null,"{\"title\":\""+key+"任务\",\"category\":\"CHORE\",\"difficulty\":\"NORMAL\",\"expectedMinutes\":5}",201));}
 private Session bootstrap(String name,String pin)throws Exception{JsonNode d=data(mvc.perform(post("/api/v1/auth/bootstrap").contentType(MediaType.APPLICATION_JSON).content("{\"familyName\":\""+name+"\",\"parentName\":\"创建者\",\"pin\":\""+pin+"\"}")).andExpect(status().isCreated()).andReturn());return new Session(UUID.fromString(d.path("familyId").asText()),UUID.fromString(d.path("parentId").asText()),d.path("session").path("token").asText());}
 private UUID child(Session s,String name)throws Exception{return id(postJson(family(s)+"/children",s.token,null,"{\"displayName\":\""+name+"\",\"birthDate\":\"2018-01-01\",\"ageStage\":\"CHILD_6_9\"}",201));}private String childToken(Session s,UUID child)throws Exception{return data(postJson("/api/v1/auth/child-sessions",s.token,null,"{\"childId\":\""+child+"\"}",201)).path("token").asText();}
 private String login(UUID family,UUID parent,String pin,int status)throws Exception{MvcResult r=mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"familyId\":\""+family+"\",\"parentId\":\""+parent+"\",\"pin\":\""+pin+"\"}")).andExpect(status().is(status)).andReturn();return status==200?data(r).path("token").asText():"";}
 private MvcResult postJson(String path,String token,String key,String body,int status)throws Exception{var b=post(path).contentType(MediaType.APPLICATION_JSON).content(body);if(token!=null)b.header("Authorization",bearer(token));if(key!=null)b.header("Idempotency-Key",key);return mvc.perform(b).andExpect(status().is(status)).andReturn();}private JsonNode data(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString()).path("data");}private UUID id(MvcResult r)throws Exception{return UUID.fromString(data(r).path("id").asText());}private String family(Session s){return "/api/v1/families/"+s.family;}private static String bearer(String token){return "Bearer "+token;}private record Session(UUID family,UUID parent,String token){}
}
