package com.familygrowth.domain;

import com.familygrowth.domain.Stage3Models.RewardGrant;import com.familygrowth.domain.Stage5Models.ExchangeDirection;import java.math.*;import java.time.*;import java.util.*;

public final class Stage28RewardModels{
 private Stage28RewardModels(){}
 public enum OverflowPolicy{HOLD_FOR_PARENT,CONVERT_TO_COIN,CONVERT_TO_XP}
 public enum ApprovalStatus{PENDING,APPROVED,REJECTED}
 public record BudgetRule(UUID id,UUID childId,long version,String zoneId,BigDecimal dailyMoneyLimit,BigDecimal weeklyMoneyLimit,BigDecimal monthlyMoneyLimit,OverflowPolicy overflowPolicy,BigDecimal excessCoinPerMoney,BigDecimal excessXpPerMoney,boolean active,Instant createdAt){public BudgetRule{Objects.requireNonNull(id);Objects.requireNonNull(childId);Objects.requireNonNull(ZoneId.of(zoneId));Objects.requireNonNull(overflowPolicy);dailyMoneyLimit=money(dailyMoneyLimit);weeklyMoneyLimit=money(weeklyMoneyLimit);monthlyMoneyLimit=money(monthlyMoneyLimit);excessCoinPerMoney=rate(excessCoinPerMoney);excessXpPerMoney=rate(excessXpPerMoney);if(version<1||dailyMoneyLimit.signum()<0||weeklyMoneyLimit.compareTo(dailyMoneyLimit)<0||monthlyMoneyLimit.compareTo(weeklyMoneyLimit)<0||excessCoinPerMoney.signum()<0||excessXpPerMoney.signum()<0)throw new IllegalArgumentException("Invalid reward budget rule");}}
 public record BudgetSummary(BudgetRule rule,BigDecimal spentToday,BigDecimal spentThisWeek,BigDecimal spentThisMonth,BigDecimal remainingMoney){public BudgetSummary{Objects.requireNonNull(rule);spentToday=money(spentToday);spentThisWeek=money(spentThisWeek);spentThisMonth=money(spentThisMonth);remainingMoney=money(remainingMoney.max(BigDecimal.ZERO));}}
 public record BudgetOverride(UUID id,UUID childId,UUID completionId,RewardGrant proposed,String reason,Instant createdAt,Instant consumedAt){public BudgetOverride{Objects.requireNonNull(id);Objects.requireNonNull(childId);Objects.requireNonNull(completionId);Objects.requireNonNull(proposed);if(reason==null||reason.isBlank()||reason.length()>500)throw new IllegalArgumentException("Override reason is required");}}
 public record BudgetDecision(UUID id,UUID completionId,long ruleVersion,OverflowPolicy policy,RewardGrant proposed,RewardGrant actual,BigDecimal overflowMoney,UUID overrideId,Instant createdAt){public BudgetDecision{Objects.requireNonNull(id);Objects.requireNonNull(completionId);Objects.requireNonNull(policy);Objects.requireNonNull(proposed);Objects.requireNonNull(actual);overflowMoney=money(overflowMoney);}}
 public record ExchangeControlRule(UUID id,UUID familyId,long version,boolean moneyToCoinEnabled,boolean coinToMoneyEnabled,BigDecimal moneyToCoinDailyLimit,BigDecimal moneyToCoinMonthlyLimit,BigDecimal coinToMoneyDailyLimit,BigDecimal coinToMoneyMonthlyLimit,boolean childRequiresParentApproval,String zoneId,boolean active,Instant createdAt){public ExchangeControlRule{Objects.requireNonNull(id);Objects.requireNonNull(familyId);Objects.requireNonNull(ZoneId.of(zoneId));moneyToCoinDailyLimit=money(moneyToCoinDailyLimit);moneyToCoinMonthlyLimit=money(moneyToCoinMonthlyLimit);coinToMoneyDailyLimit=money(coinToMoneyDailyLimit);coinToMoneyMonthlyLimit=money(coinToMoneyMonthlyLimit);if(version<1||moneyToCoinDailyLimit.signum()<0||moneyToCoinMonthlyLimit.compareTo(moneyToCoinDailyLimit)<0||coinToMoneyDailyLimit.signum()<0||coinToMoneyMonthlyLimit.compareTo(coinToMoneyDailyLimit)<0)throw new IllegalArgumentException("Invalid exchange control rule");}public boolean enabled(ExchangeDirection d){return d==ExchangeDirection.MONEY_TO_COIN?moneyToCoinEnabled:coinToMoneyEnabled;}public BigDecimal daily(ExchangeDirection d){return d==ExchangeDirection.MONEY_TO_COIN?moneyToCoinDailyLimit:coinToMoneyDailyLimit;}public BigDecimal monthly(ExchangeDirection d){return d==ExchangeDirection.MONEY_TO_COIN?moneyToCoinMonthlyLimit:coinToMoneyMonthlyLimit;}}
 public record ExchangeApproval(UUID id,UUID childId,UUID previewId,ApprovalStatus status,String submitKey,String reviewKey,String reviewNote,UUID orderId,Instant createdAt,Instant reviewedAt){public ExchangeApproval{Objects.requireNonNull(id);Objects.requireNonNull(childId);Objects.requireNonNull(previewId);Objects.requireNonNull(status);reviewNote=reviewNote==null?"":reviewNote;}}
 public record Fulfillment(UUID orderId,UUID childId,String productTitle,String note,UUID fulfilledBy,Instant fulfilledAt){public Fulfillment{Objects.requireNonNull(orderId);Objects.requireNonNull(childId);if(productTitle==null||productTitle.isBlank()||note==null||note.isBlank()||note.length()>500||fulfilledBy==null||fulfilledAt==null)throw new IllegalArgumentException("Invalid reward fulfillment");}}
 public static RewardGrant convert(RewardGrant proposed,BigDecimal remaining,OverflowPolicy policy,BigDecimal coinRate,BigDecimal xpRate){BigDecimal actualMoney=proposed.money().min(remaining.max(BigDecimal.ZERO)).setScale(2,RoundingMode.DOWN),overflow=proposed.money().subtract(actualMoney);long coin=proposed.coin(),xp=proposed.xp();if(overflow.signum()>0){if(policy==OverflowPolicy.HOLD_FOR_PARENT)throw new IllegalStateException("Parent override required");if(policy==OverflowPolicy.CONVERT_TO_COIN)coin=Math.addExact(coin,overflow.multiply(coinRate).setScale(0,RoundingMode.DOWN).longValueExact());else xp=Math.addExact(xp,overflow.multiply(xpRate).setScale(0,RoundingMode.DOWN).longValueExact());}return new RewardGrant(xp,coin,actualMoney);}
 private static BigDecimal money(BigDecimal v){return Objects.requireNonNull(v).setScale(2,RoundingMode.UNNECESSARY);}private static BigDecimal rate(BigDecimal v){return Objects.requireNonNull(v).setScale(6,RoundingMode.UNNECESSARY);}
}
