package com.familygrowth.infrastructure;

import com.familygrowth.application.*;
import com.familygrowth.domain.Stage20Models.SchoolStage;
import com.familygrowth.domain.Stage29CollaborationModels.*;
import java.sql.*;
import java.time.*;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
class JdbcStage29CollaborationStore implements Stage29CollaborationStore {
    private final JdbcTemplate jdbc; JdbcStage29CollaborationStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
    @Override public boolean isOwner(UUID f,UUID p){return jdbc.queryForObject("SELECT COUNT(*) FROM parent_profile WHERE family_id=? AND id=? AND member_role='OWNER' AND member_status='ACTIVE'",Integer.class,f,p)==1;}
    @Override public List<Member> members(UUID f){family(f);return jdbc.query("SELECT * FROM parent_profile WHERE family_id=? ORDER BY created_at",this::memberRow,f);}
    @Override public Optional<Member> member(UUID f,UUID p){return jdbc.query("SELECT * FROM parent_profile WHERE family_id=? AND id=?",this::memberRow,f,p).stream().findFirst();}
    @Override public Optional<Invitation> invitationReplay(UUID f,String key){return jdbc.query("SELECT * FROM family_parent_invitation WHERE family_id=? AND idempotency_key=?",this::inviteRow,f,key).stream().findFirst();}
    @Override public Invitation createInvitation(UUID f,String name,String codeHash,UUID actor,String key,String payload,Instant expires,Instant now){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO family_parent_invitation(id,family_id,invited_name,member_role,code_hash,status,expires_at,created_by,idempotency_key,payload_hash,created_at) VALUES(?,?,?,'GUARDIAN',?,'OPEN',?,?,?,?,?)",id,f,name,codeHash,ts(expires),actor,key,payload,ts(now));action(f,actor,"INVITATION_CREATED","INVITATION",id,"expires="+expires,key,now);return invitation(f,id,false).orElseThrow();}
    @Override public Optional<Invitation> invitationByCode(String hash,boolean lock){return jdbc.query("SELECT * FROM family_parent_invitation WHERE code_hash=?"+(lock?" FOR UPDATE":""),this::inviteRow,hash).stream().findFirst();}
    @Override public Member acceptInvitation(UUID invitation,String pinHash,Instant now){Invitation i=jdbc.query("SELECT * FROM family_parent_invitation WHERE id=? FOR UPDATE",this::inviteRow,invitation).stream().findFirst().orElseThrow(Stage3Service.AuthenticationException::new);if(i.status()!=InvitationStatus.OPEN||!i.expiresAt().isAfter(now))throw new Stage3Service.AuthenticationException();UUID parent=UUID.randomUUID();jdbc.update("INSERT INTO parent_profile(id,family_id,display_name,version,created_at,member_role,member_status,updated_at) VALUES(?,?,?,0,?,'GUARDIAN','ACTIVE',?)",parent,i.familyId(),i.invitedName(),ts(now),ts(now));jdbc.update("INSERT INTO parent_pin_credential(parent_id,family_id,pin_hash,failed_attempts,version,created_at,updated_at) VALUES(?,?,?,0,0,?,?)",parent,i.familyId(),pinHash,ts(now),ts(now));jdbc.update("UPDATE family_parent_invitation SET status='ACCEPTED',accepted_parent_id=?,accepted_at=? WHERE id=? AND status='OPEN'",parent,ts(now),invitation);action(i.familyId(),parent,"INVITATION_ACCEPTED","PARENT",parent,"invitation="+invitation,null,now);return member(i.familyId(),parent).orElseThrow();}
    @Override public Invitation revokeInvitation(UUID f,UUID id,UUID actor,Instant now){Invitation i=invitation(f,id,true).orElseThrow(FamilyGrowthService.NotFoundException::new);if(i.status()==InvitationStatus.ACCEPTED)throw new Stage3Service.ConflictException("Accepted invitation cannot be revoked");if(i.status()==InvitationStatus.OPEN){jdbc.update("UPDATE family_parent_invitation SET status='REVOKED',revoked_by=?,revoked_at=? WHERE family_id=? AND id=? AND status='OPEN'",actor,ts(now),f,id);action(f,actor,"INVITATION_REVOKED","INVITATION",id,"revoked",null,now);}return invitation(f,id,false).orElseThrow();}
    @Override public void resetParentPin(UUID f,UUID p,String hash,UUID actor,Instant now){if(jdbc.update("UPDATE parent_pin_credential SET pin_hash=?,failed_attempts=0,locked_until=NULL,version=version+1,updated_at=? WHERE family_id=? AND parent_id=?",hash,ts(now),f,p)!=1)throw new FamilyGrowthService.NotFoundException();action(f,actor,"PARENT_PIN_RESET","PARENT",p,"sessions revoked",null,now);}
    @Override public void revokeMember(UUID f,UUID p,UUID actor,Instant now){if(jdbc.update("UPDATE parent_profile SET member_status='REVOKED',version=version+1,updated_at=? WHERE family_id=? AND id=? AND member_status='ACTIVE'",ts(now),f,p)!=1)throw new FamilyGrowthService.NotFoundException();action(f,actor,"MEMBER_REVOKED","PARENT",p,"sessions revoked",null,now);}
    @Override public List<ChildChoice> children(UUID f){family(f);return jdbc.query("SELECT c.id,c.display_name,c.birth_date,x.stage_override FROM child_profile c LEFT JOIN child_experience_profile x ON x.family_id=c.family_id AND x.child_id=c.id WHERE c.family_id=? ORDER BY c.created_at",(r,n)->{LocalDate birth=r.getDate(3).toLocalDate();String override=r.getString(4);String stage=override!=null?override:SchoolStage.recommended(birth,LocalDate.now()).name();return new ChildChoice(uuid(r,1),r.getString(2),birth,stage);},f);}
    @Override public Optional<PairingCode> pairingReplay(UUID f,String key){return jdbc.query("SELECT * FROM device_pairing_code WHERE family_id=? AND idempotency_key=?",this::pairingRow,f,key).stream().findFirst();}
    @Override public PairingCode createPairing(UUID f,PairingRole role,UUID actorId,UUID child,String hash,UUID createdBy,String key,String payload,Instant expires,Instant now){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO device_pairing_code(id,family_id,requested_role,actor_id,child_id,code_hash,status,expires_at,created_by,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,'OPEN',?,?,?,?,?)",id,f,role.name(),actorId,child,hash,ts(expires),createdBy,key,payload,ts(now));action(f,createdBy,"PAIRING_CREATED","PAIRING",id,role.name(),key,now);return pairing(f,id,false).orElseThrow();}
    @Override public Optional<PairingCode> pairingByCode(String hash,boolean lock){return jdbc.query("SELECT * FROM device_pairing_code WHERE code_hash=?"+(lock?" FOR UPDATE":""),this::pairingRow,hash).stream().findFirst();}
    @Override public Device consumePairing(UUID id,String name,Instant now){PairingCode p=jdbc.query("SELECT * FROM device_pairing_code WHERE id=? FOR UPDATE",this::pairingRow,id).stream().findFirst().orElseThrow(Stage3Service.AuthenticationException::new);if(!p.expiresAt().isAfter(now))throw new Stage3Service.AuthenticationException();UUID device=UUID.randomUUID();jdbc.update("INSERT INTO paired_device(id,family_id,actor_id,actor_role,child_id,device_name,status,created_by,created_at,last_seen_at) SELECT ?,?,?,?,?,?,'ACTIVE',created_by,?,? FROM device_pairing_code WHERE id=? AND status='OPEN'",device,p.familyId(),p.actorId(),p.role().name(),p.childId(),name,ts(now),ts(now),id);if(jdbc.update("UPDATE device_pairing_code SET status='CONSUMED',paired_device_id=?,consumed_at=? WHERE id=? AND status='OPEN'",device,ts(now),id)!=1)throw new Stage3Service.AuthenticationException();action(p.familyId(),p.actorId(),"PAIRING_CONSUMED","DEVICE",device,p.role().name(),null,now);return device(p.familyId(),device,false).orElseThrow();}
    @Override public List<Device> devices(UUID f){family(f);return jdbc.query("SELECT * FROM paired_device WHERE family_id=? ORDER BY created_at DESC",this::deviceRow,f);}
    @Override public Device revokeDevice(UUID f,UUID id,UUID actor,Instant now){Device d=device(f,id,true).orElseThrow(FamilyGrowthService.NotFoundException::new);if(d.status()==DeviceStatus.ACTIVE){jdbc.update("UPDATE paired_device SET status='REVOKED',revoked_at=? WHERE family_id=? AND id=? AND status='ACTIVE'",ts(now),f,id);action(f,actor,"DEVICE_REVOKED","DEVICE",id,"sessions revoked",null,now);}return device(f,id,false).orElseThrow();}
    @Override public void revokeDeviceSessions(UUID f,UUID d,Instant now){jdbc.update("UPDATE auth_session SET revoked_at=? WHERE family_id=? AND device_id=? AND revoked_at IS NULL",ts(now),f,d);}
    @Override public void revokeActorSessions(UUID f,UUID a,Instant now){jdbc.update("UPDATE auth_session SET revoked_at=? WHERE family_id=? AND actor_id=? AND revoked_at IS NULL",ts(now),f,a);}
    @Override public void resetPinCredential(UUID f,UUID p,String hash,Instant now){jdbc.update("UPDATE parent_pin_credential SET pin_hash=?,failed_attempts=0,locked_until=NULL,version=version+1,updated_at=? WHERE family_id=? AND parent_id=?",hash,ts(now),f,p);}
    @Override public void emitToParents(UUID f,UUID child,NotificationType type,String title,String body,String sourceType,UUID source,Instant now){List<UUID> parents=jdbc.query("SELECT id FROM parent_profile WHERE family_id=? AND member_status='ACTIVE'",(r,n)->uuid(r,1),f);for(UUID parent:parents)try{jdbc.update("INSERT INTO family_notification(id,family_id,recipient_actor_id,recipient_role,child_id,notification_type,title,body,source_type,source_id,status,created_at) VALUES(?,?,?,'PARENT',?,?,?,?,?,?,'UNREAD',?)",UUID.randomUUID(),f,parent,child,type.name(),title,body,sourceType,source,ts(now));}catch(DuplicateKeyException ignored){}}
    @Override public List<Notification> notifications(UUID f,UUID actor){return jdbc.query("SELECT * FROM family_notification WHERE family_id=? AND recipient_actor_id=? ORDER BY created_at DESC",this::notificationRow,f,actor);}
    @Override public Notification markRead(UUID f,UUID actor,UUID id,Instant now){if(jdbc.update("UPDATE family_notification SET status='READ',read_at=COALESCE(read_at,?) WHERE family_id=? AND recipient_actor_id=? AND id=?",ts(now),f,actor,id)!=1)throw new FamilyGrowthService.NotFoundException();return jdbc.query("SELECT * FROM family_notification WHERE family_id=? AND recipient_actor_id=? AND id=?",this::notificationRow,f,actor,id).stream().findFirst().orElseThrow();}
    @Override public void redactChildFreeText(UUID f,UUID child){
        jdbc.update("UPDATE family_notification SET title='儿童事项已去标识化',body='相关儿童资料已按家长请求删除或去标识化' WHERE family_id=? AND child_id=?",f,child);
        jdbc.update("UPDATE paired_device SET device_name='已去标识化儿童设备' WHERE family_id=? AND child_id=?",f,child);
    }
    private Optional<Invitation> invitation(UUID f,UUID id,boolean lock){return jdbc.query("SELECT * FROM family_parent_invitation WHERE family_id=? AND id=?"+(lock?" FOR UPDATE":""),this::inviteRow,f,id).stream().findFirst();}
    private Optional<PairingCode> pairing(UUID f,UUID id,boolean lock){return jdbc.query("SELECT * FROM device_pairing_code WHERE family_id=? AND id=?"+(lock?" FOR UPDATE":""),this::pairingRow,f,id).stream().findFirst();}
    private Optional<Device> device(UUID f,UUID id,boolean lock){return jdbc.query("SELECT * FROM paired_device WHERE family_id=? AND id=?"+(lock?" FOR UPDATE":""),this::deviceRow,f,id).stream().findFirst();}
    private Member memberRow(ResultSet r,int n)throws SQLException{return new Member(uuid(r,"id"),uuid(r,"family_id"),r.getString("display_name"),MemberRole.valueOf(r.getString("member_role")),MemberStatus.valueOf(r.getString("member_status")),instant(r,"created_at"),instant(r,"updated_at"));}
    private Invitation inviteRow(ResultSet r,int n)throws SQLException{return new Invitation(uuid(r,"id"),uuid(r,"family_id"),r.getString("invited_name"),MemberRole.valueOf(r.getString("member_role")),InvitationStatus.valueOf(r.getString("status")),instant(r,"expires_at"),uuid(r,"accepted_parent_id"),instant(r,"created_at"),instant(r,"accepted_at"));}
    private PairingCode pairingRow(ResultSet r,int n)throws SQLException{return new PairingCode(uuid(r,"id"),uuid(r,"family_id"),PairingRole.valueOf(r.getString("requested_role")),uuid(r,"actor_id"),uuid(r,"child_id"),instant(r,"expires_at"),instant(r,"created_at"));}
    private Device deviceRow(ResultSet r,int n)throws SQLException{return new Device(uuid(r,"id"),uuid(r,"family_id"),uuid(r,"actor_id"),PairingRole.valueOf(r.getString("actor_role")),uuid(r,"child_id"),r.getString("device_name"),DeviceStatus.valueOf(r.getString("status")),instant(r,"created_at"),instant(r,"last_seen_at"),instant(r,"revoked_at"));}
    private Notification notificationRow(ResultSet r,int n)throws SQLException{return new Notification(uuid(r,"id"),uuid(r,"child_id"),NotificationType.valueOf(r.getString("notification_type")),r.getString("title"),r.getString("body"),r.getString("source_type"),uuid(r,"source_id"),NotificationStatus.valueOf(r.getString("status")),instant(r,"created_at"),instant(r,"read_at"));}
    private void action(UUID f,UUID actor,String type,String target,UUID targetId,String detail,String key,Instant now){jdbc.update("INSERT INTO family_collaboration_action(id,family_id,actor_id,action_type,target_type,target_id,detail,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),f,actor,type,target,targetId,detail,key,ts(now));}
    private void family(UUID f){if(jdbc.queryForObject("SELECT COUNT(*) FROM family WHERE id=?",Integer.class,f)!=1)throw new FamilyGrowthService.NotFoundException();}
    private static UUID uuid(ResultSet r,String n)throws SQLException{return r.getObject(n,UUID.class);}private static UUID uuid(ResultSet r,int n)throws SQLException{return r.getObject(n,UUID.class);}private static Instant instant(ResultSet r,String n)throws SQLException{Timestamp t=r.getTimestamp(n);return t==null?null:t.toInstant();}private static Timestamp ts(Instant i){return Timestamp.from(i);}
}
