package com.familygrowth.infrastructure;
import com.familygrowth.application.*;import com.familygrowth.domain.Stage27GrowthModels.*;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository class JdbcStage27GrowthStore implements Stage27GrowthStore{
 private final JdbcTemplate jdbc;JdbcStage27GrowthStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @Override public List<Plan> plans(UUID f,UUID c){child(f,c);return jdbc.query("SELECT * FROM growth_plan WHERE family_id=? AND child_id=? ORDER BY start_date DESC,created_at DESC",this::planRow,f,c);}
 @Override public Optional<Plan> plan(UUID f,UUID c,UUID id){child(f,c);return jdbc.query("SELECT * FROM growth_plan WHERE family_id=? AND child_id=? AND id=?",this::planRow,f,c,id).stream().findFirst();}
 @Override public Optional<Replay> planReplay(UUID f,String key){return replay("growth_plan_action","plan_id",f,key);}
 @Override public Plan createPlan(UUID f,UUID c,String title,String desc,GrowthCategory cat,String age,String target,LocalDate start,LocalDate end,PlanStatus status,UUID actor,String key,String hash,Instant now){child(f,c);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO growth_plan(id,family_id,child_id,title,description,start_date,end_date,active,version,created_at,category,age_stage,target,status,updated_at) VALUES(?,?,?,?,?,?,?,?,0,?,?,?,?,?,?)",id,f,c,title,desc,start,end,status==PlanStatus.ACTIVE,Timestamp.from(now),cat.name(),age,target,status.name(),Timestamp.from(now));planAction(f,c,id,actor,"CREATE",null,status,-1,0,"",key,hash,now);return plan(f,c,id).orElseThrow();}
 @Override public Plan transitionPlan(UUID f,UUID c,UUID id,PlanStatus from,PlanStatus to,long rev,String reason,UUID actor,String key,String hash,Instant now){int n=jdbc.update("UPDATE growth_plan SET status=?,active=?,version=version+1,updated_at=? WHERE family_id=? AND child_id=? AND id=? AND status=? AND version=?",to.name(),to==PlanStatus.ACTIVE,Timestamp.from(now),f,c,id,from.name(),rev);changed(n,f,c,id);planAction(f,c,id,actor,"TRANSITION",from,to,rev,rev+1,reason,key,hash,now);return plan(f,c,id).orElseThrow();}
 @Override public List<Goal> goals(UUID f,UUID c,UUID p){if(plan(f,c,p).isEmpty())throw new FamilyGrowthService.NotFoundException();return jdbc.query("SELECT g.* FROM growth_goal g JOIN growth_plan p ON p.id=g.plan_id AND p.family_id=g.family_id WHERE g.family_id=? AND p.child_id=? AND g.plan_id=? ORDER BY g.created_at",this::goalRow,f,c,p);}
 @Override public Optional<Goal> goal(UUID f,UUID c,UUID id){child(f,c);return jdbc.query("SELECT g.* FROM growth_goal g JOIN growth_plan p ON p.id=g.plan_id AND p.family_id=g.family_id WHERE g.family_id=? AND p.child_id=? AND g.id=?",this::goalRow,f,c,id).stream().findFirst();}
 @Override public Optional<Replay> goalReplay(UUID f,String key){return replay("growth_goal_action","goal_id",f,key);}
 @Override public Goal createGoal(UUID f,UUID c,UUID p,String title,String desc,String target,UUID actor,String key,String hash,Instant now){if(plan(f,c,p).isEmpty())throw new FamilyGrowthService.NotFoundException();UUID id=UUID.randomUUID();jdbc.update("INSERT INTO growth_goal(id,family_id,plan_id,title,description,version,created_at,target,status,updated_at) VALUES(?,?,?,?,?,0,?,?,'ACTIVE',?)",id,f,p,title,desc,Timestamp.from(now),target,Timestamp.from(now));goalAction(f,c,p,id,actor,"CREATE",null,GoalStatus.ACTIVE,-1,0,"",key,hash,now);return goal(f,c,id).orElseThrow();}
 @Override public Goal transitionGoal(UUID f,UUID c,UUID id,GoalStatus from,GoalStatus to,long rev,String reason,UUID actor,String key,String hash,Instant now){Goal current=goal(f,c,id).orElseThrow(FamilyGrowthService.NotFoundException::new);int n=jdbc.update("UPDATE growth_goal SET status=?,version=version+1,updated_at=? WHERE family_id=? AND id=? AND status=? AND version=?",to.name(),Timestamp.from(now),f,id,from.name(),rev);changed(n,f,c,id);goalAction(f,c,current.planId(),id,actor,"TRANSITION",from,to,rev,rev+1,reason,key,hash,now);return goal(f,c,id).orElseThrow();}
 @Override public List<Milestone> milestones(UUID f,UUID c){child(f,c);return jdbc.query("SELECT * FROM growth_milestone WHERE family_id=? AND child_id=? ORDER BY occurred_on DESC,created_at DESC",(r,n)->milestoneRow(r,f,c),f,c);}
 @Override public Optional<Milestone> milestone(UUID f,UUID c,UUID id){child(f,c);return jdbc.query("SELECT * FROM growth_milestone WHERE family_id=? AND child_id=? AND id=?",(r,n)->milestoneRow(r,f,c),f,c,id).stream().findFirst();}
 @Override public Optional<Replay> milestoneReplay(UUID f,String key){return replay("growth_milestone_action","milestone_id",f,key);}
 @Override public Milestone createMilestone(UUID f,UUID c,UUID p,UUID g,LocalDate day,MilestoneCategory cat,String title,String obs,UUID actor,String key,String hash,Instant now){child(f,c);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO growth_milestone(id,family_id,child_id,plan_id,goal_id,occurred_on,category,title,observation,actor_id,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,0,?,?)",id,f,c,p,g,day,cat.name(),title,obs,actor,Timestamp.from(now),Timestamp.from(now));milestoneAction(f,c,id,actor,"CREATE",-1,0,key,hash,now);return milestone(f,c,id).orElseThrow();}
 @Override public Milestone updateMilestone(UUID f,UUID c,UUID id,LocalDate day,MilestoneCategory cat,String title,String obs,long rev,UUID actor,String key,String hash,Instant now){int n=jdbc.update("UPDATE growth_milestone SET occurred_on=?,category=?,title=?,observation=?,revision=revision+1,updated_at=? WHERE family_id=? AND child_id=? AND id=? AND revision=?",day,cat.name(),title,obs,Timestamp.from(now),f,c,id,rev);changed(n,f,c,id);milestoneAction(f,c,id,actor,"UPDATE",rev,rev+1,key,hash,now);return milestone(f,c,id).orElseThrow();}
 @Override public Optional<Replay> artifactReplay(UUID f,String key){return jdbc.query("SELECT child_id,id,payload_hash FROM growth_artifact WHERE family_id=? AND idempotency_key=?",(r,n)->new Replay(r.getObject(1,UUID.class),r.getObject(2,UUID.class),"CREATE",r.getString(3)),f,key).stream().findFirst();}
 @Override public ArtifactMetadata createArtifact(UUID f,UUID c,UUID m,String type,byte[] bytes,String sha,String alt,UUID actor,String key,String hash,Instant now){if(milestone(f,c,m).isEmpty())throw new FamilyGrowthService.NotFoundException();UUID id=UUID.randomUUID();jdbc.update("INSERT INTO growth_artifact(id,family_id,child_id,milestone_id,actor_id,content_type,byte_size,sha256,alt_text,content,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,f,c,m,actor,type,bytes.length,sha,alt,bytes,key,hash,Timestamp.from(now));return artifactMeta(f,c,id).orElseThrow();}
 @Override public Optional<Artifact> artifact(UUID f,UUID c,UUID id){child(f,c);return jdbc.query("SELECT * FROM growth_artifact WHERE family_id=? AND child_id=? AND id=?",(r,n)->{ArtifactMetadata m=artifactMetaRow(r);return new Artifact(m,r.getBytes("content"));},f,c,id).stream().findFirst();}
 @Override public GrowthReport report(UUID f,UUID c,Instant now){child(f,c);EnumMap<PlanStatus,Long> states=new EnumMap<>(PlanStatus.class);for(PlanStatus s:PlanStatus.values())states.put(s,count("SELECT COUNT(*) FROM growth_plan WHERE family_id=? AND child_id=? AND status=?",f,c,s.name()));long ms=count("SELECT COUNT(*) FROM growth_milestone WHERE family_id=? AND child_id=?",f,c),art=count("SELECT COUNT(*) FROM growth_artifact WHERE family_id=? AND child_id=?",f,c);Map<GrowthCategory,Long> milestoneCounts=new EnumMap<>(GrowthCategory.class);for(Milestone m:milestones(f,c))milestoneCounts.merge(map(m.category()),1L,Long::sum);List<CategoryFacts> facts=new ArrayList<>();for(GrowthCategory cat:GrowthCategory.values()){long plans=count("SELECT COUNT(*) FROM growth_plan WHERE family_id=? AND child_id=? AND category=?",f,c,cat.name()),active=count("SELECT COUNT(*) FROM growth_plan WHERE family_id=? AND child_id=? AND category=? AND status='ACTIVE'",f,c,cat.name()),approved=countTasks(f,c,cat,"APPROVED"),rejected=countTasks(f,c,cat,"REJECTED");facts.add(new CategoryFacts(cat,plans,active,milestoneCounts.getOrDefault(cat,0L),approved,rejected));}return new GrowthReport(c,states.get(PlanStatus.DRAFT),states.get(PlanStatus.ACTIVE),states.get(PlanStatus.PAUSED),states.get(PlanStatus.COMPLETED),states.get(PlanStatus.CANCELED),ms,art,facts,now);}
 private long countTasks(UUID f,UUID c,GrowthCategory cat,String status){return count("SELECT COUNT(*) FROM task_completion tc JOIN growth_task t ON t.id=tc.task_id JOIN growth_goal g ON g.id=t.goal_id JOIN growth_plan p ON p.id=g.plan_id WHERE tc.family_id=? AND tc.child_id=? AND p.category=? AND tc.status=?",f,c,cat.name(),status);}
 private long count(String sql,Object... a){return jdbc.queryForObject(sql,Long.class,a);}
 private Optional<Replay> replay(String table,String result,UUID f,String key){return jdbc.query("SELECT child_id,"+result+",action_type,payload_hash FROM "+table+" WHERE family_id=? AND idempotency_key=?",(r,n)->new Replay(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getString(3),r.getString(4)),f,key).stream().findFirst();}
 private void planAction(UUID f,UUID c,UUID id,UUID actor,String type,PlanStatus old,PlanStatus next,long oldRev,long newRev,String reason,String key,String hash,Instant now){jdbc.update("INSERT INTO growth_plan_action(id,family_id,child_id,plan_id,actor_id,action_type,old_status,new_status,old_revision,new_revision,reason,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),f,c,id,actor,type,old==null?null:old.name(),next.name(),oldRev,newRev,reason,key,hash,Timestamp.from(now));}
 private void goalAction(UUID f,UUID c,UUID p,UUID id,UUID actor,String type,GoalStatus old,GoalStatus next,long oldRev,long newRev,String reason,String key,String hash,Instant now){jdbc.update("INSERT INTO growth_goal_action(id,family_id,child_id,plan_id,goal_id,actor_id,action_type,old_status,new_status,old_revision,new_revision,reason,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),f,c,p,id,actor,type,old==null?null:old.name(),next.name(),oldRev,newRev,reason,key,hash,Timestamp.from(now));}
 private void milestoneAction(UUID f,UUID c,UUID id,UUID actor,String type,long oldRev,long newRev,String key,String hash,Instant now){jdbc.update("INSERT INTO growth_milestone_action(id,family_id,child_id,milestone_id,actor_id,action_type,old_revision,new_revision,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),f,c,id,actor,type,oldRev,newRev,key,hash,Timestamp.from(now));}
 private Plan planRow(ResultSet r,int n)throws SQLException{return new Plan(r.getObject("id",UUID.class),r.getObject("child_id",UUID.class),r.getString("title"),r.getString("description"),GrowthCategory.valueOf(r.getString("category")),r.getString("age_stage"),r.getString("target"),r.getObject("start_date",LocalDate.class),r.getObject("end_date",LocalDate.class),PlanStatus.valueOf(r.getString("status")),r.getLong("version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
 private Goal goalRow(ResultSet r,int n)throws SQLException{return new Goal(r.getObject("id",UUID.class),r.getObject("plan_id",UUID.class),r.getString("title"),r.getString("description"),r.getString("target"),GoalStatus.valueOf(r.getString("status")),r.getLong("version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
 private Milestone milestoneRow(ResultSet r,UUID f,UUID c)throws SQLException{UUID id=r.getObject("id",UUID.class);return new Milestone(id,c,r.getObject("plan_id",UUID.class),r.getObject("goal_id",UUID.class),r.getObject("occurred_on",LocalDate.class),MilestoneCategory.valueOf(r.getString("category")),r.getString("title"),r.getString("observation"),r.getLong("revision"),artifacts(f,c,id),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
 private List<ArtifactMetadata> artifacts(UUID f,UUID c,UUID m){return jdbc.query("SELECT * FROM growth_artifact WHERE family_id=? AND child_id=? AND milestone_id=? ORDER BY created_at",(r,n)->artifactMetaRow(r),f,c,m);}private Optional<ArtifactMetadata> artifactMeta(UUID f,UUID c,UUID id){return jdbc.query("SELECT * FROM growth_artifact WHERE family_id=? AND child_id=? AND id=?",(r,n)->artifactMetaRow(r),f,c,id).stream().findFirst();}
 private ArtifactMetadata artifactMetaRow(ResultSet r)throws SQLException{return new ArtifactMetadata(r.getObject("id",UUID.class),r.getObject("milestone_id",UUID.class),r.getString("content_type"),r.getLong("byte_size"),r.getString("sha256"),r.getString("alt_text"),r.getTimestamp("created_at").toInstant());}
 private GrowthCategory map(MilestoneCategory c){return switch(c){case LEARNING,LANGUAGE,PARENT_CHILD_READING->GrowthCategory.LEARNING;case MOVEMENT->GrowthCategory.HEALTH;case SELF_CARE->GrowthCategory.LIFE_SKILLS;case EMOTIONAL_CONNECTION->GrowthCategory.RELATIONSHIP;case CREATIVITY->GrowthCategory.CREATIVITY;case OTHER->GrowthCategory.OTHER;};}
 private void child(UUID f,UUID c){if(jdbc.queryForObject("SELECT COUNT(*) FROM child_profile WHERE family_id=? AND id=?",Integer.class,f,c)!=1)throw new FamilyGrowthService.NotFoundException();}private void changed(int n,UUID f,UUID c,UUID id){if(n==1)return;if(jdbc.queryForObject("SELECT COUNT(*) FROM growth_plan WHERE family_id=? AND child_id=? AND id=?",Integer.class,f,c,id)==0&&jdbc.queryForObject("SELECT COUNT(*) FROM growth_milestone WHERE family_id=? AND child_id=? AND id=?",Integer.class,f,c,id)==0&&jdbc.queryForObject("SELECT COUNT(*) FROM growth_goal g JOIN growth_plan p ON p.id=g.plan_id WHERE g.family_id=? AND p.child_id=? AND g.id=?",Integer.class,f,c,id)==0)throw new FamilyGrowthService.NotFoundException();throw new Stage3Service.ConflictException("Growth record revision or status conflict");}
}
