package com.familygrowth.infrastructure;
import com.familygrowth.application.*;import com.familygrowth.domain.Stage26RetentionModels.*;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository class JdbcStage26RetentionStore implements Stage26RetentionStore {private final JdbcTemplate jdbc;JdbcStage26RetentionStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @Override public RetentionPolicy policy(UUID family,UUID child){requireChild(family,child);return jdbc.query("SELECT family_id,child_id,usage_detail_days,version,updated_at FROM child_data_retention_policy WHERE family_id=? AND child_id=?",this::policyRow,family,child).stream().findFirst().orElse(new RetentionPolicy(family,child,90,0,Instant.EPOCH));}
 @Override public RetentionPolicy updatePolicy(UUID family,UUID child,UUID actor,int days,long expected,String reason,Instant now){RetentionPolicy old=policy(family,child);if(old.version()!=expected)throw new Stage3Service.ConflictException("Retention policy was changed concurrently");if(old.updatedAt().equals(Instant.EPOCH)){int inserted=jdbc.update("INSERT INTO child_data_retention_policy(child_id,family_id,usage_detail_days,version,updated_by,created_at,updated_at) SELECT ?,?,?,1,?,?,? WHERE NOT EXISTS(SELECT 1 FROM child_data_retention_policy WHERE child_id=?)",child,family,days,actor,ts(now),ts(now),child);if(inserted!=1)throw new Stage3Service.ConflictException("Retention policy was changed concurrently");}else{int changed=jdbc.update("UPDATE child_data_retention_policy SET usage_detail_days=?,version=version+1,updated_by=?,updated_at=? WHERE family_id=? AND child_id=? AND version=?",days,actor,ts(now),family,child,expected);if(changed!=1)throw new Stage3Service.ConflictException("Retention policy was changed concurrently");}jdbc.update("INSERT INTO child_data_retention_policy_action(id,family_id,child_id,actor_id,old_usage_detail_days,new_usage_detail_days,reason,created_at) VALUES(?,?,?,?,?,?,?,?)",UUID.randomUUID(),family,child,actor,old.usageDetailDays(),days,reason,ts(now));return policy(family,child);}
 @Override public RetentionRun run(UUID family,UUID child,int days,String trigger,UUID actor,Instant now){requireChild(family,child);Instant cutoff=now.minus(Duration.ofDays(days));int usage=jdbc.update("DELETE FROM usage_event WHERE family_id=? AND child_id=? AND occurred_at<?",family,child,ts(cutoff));int allowances=jdbc.update("UPDATE usage_temporary_allowance SET reason='[已过期并清理]' WHERE family_id=? AND child_id=? AND expires_at<? AND reason<>'[已过期并清理]'",family,child,ts(now));int tokens=jdbc.update("UPDATE child_data_request SET confirmation_token_hash=NULL WHERE family_id=? AND child_id=? AND confirmation_expires_at<? AND confirmation_token_hash IS NOT NULL",family,child,ts(now));UUID id=UUID.randomUUID();jdbc.update("INSERT INTO child_data_retention_run(id,family_id,child_id,trigger_type,actor_id,usage_events_deleted,allowances_redacted,expired_tokens_cleared,cutoff_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",id,family,child,trigger,actor,usage,allowances,tokens,ts(cutoff),ts(now));return new RetentionRun(id,family,child,trigger,usage,allowances,tokens,cutoff,now);}
 @Override public List<RetentionTarget> targets(){return jdbc.query("SELECT c.family_id,c.id,COALESCE(p.usage_detail_days,90) FROM child_profile c LEFT JOIN child_data_retention_policy p ON p.child_id=c.id",(r,n)->new RetentionTarget(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getInt(3)));}
 private RetentionPolicy policyRow(ResultSet r,int n)throws SQLException{return new RetentionPolicy(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getInt(3),r.getLong(4),r.getTimestamp(5).toInstant());}private void requireChild(UUID family,UUID child){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM child_profile WHERE family_id=? AND id=?",Integer.class,family,child);if(n==null||n!=1)throw new FamilyGrowthService.NotFoundException();}private static Timestamp ts(Instant value){return Timestamp.from(value);}
}
