package com.familygrowth.infrastructure;
import com.familygrowth.application.*;import com.familygrowth.domain.Stage28RewardModels;import com.familygrowth.domain.Stage28RewardModels.*;import com.familygrowth.domain.Stage3Models.RewardGrant;import com.familygrowth.domain.Stage5Models.ExchangeDirection;import java.math.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.sql.*;import java.time.*;import java.time.temporal.TemporalAdjusters;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;

@Repository class JdbcStage28RewardStore implements Stage28RewardStore{
 private final JdbcTemplate jdbc;JdbcStage28RewardStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @Override public BudgetRule createBudgetRule(UUID f,UUID c,String zone,BigDecimal daily,BigDecimal weekly,BigDecimal monthly,OverflowPolicy policy,BigDecimal coinRate,BigDecimal xpRate,UUID actor,String key,String hash,Instant now){lockChild(f,c);Long v=jdbc.queryForObject("SELECT COALESCE(MAX(rule_version),0)+1 FROM reward_budget_rule WHERE family_id=? AND child_id=?",Long.class,f,c);jdbc.update("UPDATE reward_budget_rule SET active=FALSE WHERE family_id=? AND child_id=? AND active=TRUE",f,c);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO reward_budget_rule(id,family_id,child_id,rule_version,zone_id,daily_money_limit,weekly_money_limit,monthly_money_limit,overflow_policy,excess_coin_per_money,excess_xp_per_money,active,actor_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,TRUE,?,?)",id,f,c,v,zone,daily,weekly,monthly,policy.name(),coinRate,xpRate,actor,ts(now));jdbc.update("INSERT INTO reward_budget_rule_action(id,family_id,child_id,rule_id,actor_id,action_type,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,'ACTIVATE',?,?,?)",UUID.randomUUID(),f,c,id,actor,key,hash,ts(now));return budget(f,c,id,false).orElseThrow();}
 @Override public Optional<BudgetRule> budgetRuleReplay(UUID f,String key){return jdbc.query("SELECT r.* FROM reward_budget_rule_action a JOIN reward_budget_rule r ON r.id=a.rule_id WHERE a.family_id=? AND a.idempotency_key=?",this::budgetRow,f,key).stream().findFirst();}
 @Override public Optional<BudgetRule> activeBudgetRule(UUID f,UUID c){lockExists(f,c);return jdbc.query("SELECT * FROM reward_budget_rule WHERE family_id=? AND child_id=? AND active=TRUE",this::budgetRow,f,c).stream().findFirst();}
 @Override public BudgetSummary budgetSummary(UUID f,UUID c,Instant now){BudgetRule r=activeBudgetRule(f,c).orElseThrow(()->new Stage3Service.ConflictException("No active reward budget rule"));Bounds b=bounds(r.zoneId(),now);BigDecimal d=spentRewards(f,c,b.day(),now),w=spentRewards(f,c,b.week(),now),m=spentRewards(f,c,b.month(),now),remaining=min(r.dailyMoneyLimit().subtract(d),r.weeklyMoneyLimit().subtract(w),r.monthlyMoneyLimit().subtract(m)).max(BigDecimal.ZERO);return new BudgetSummary(r,d,w,m,remaining);}
 @Override public Optional<BudgetOverride> overrideReplay(UUID f,String key){return jdbc.query("SELECT * FROM reward_budget_override WHERE family_id=? AND idempotency_key=?",this::overrideRow,f,key).stream().findFirst();}
 @Override public BudgetOverride createOverride(UUID f,UUID c,UUID completion,RewardGrant p,String reason,UUID actor,String key,String hash,Instant now){lockCompletion(f,c,completion);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO reward_budget_override(id,family_id,child_id,completion_id,proposed_money,proposed_coin,proposed_xp,reward_hash,reason,actor_id,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",id,f,c,completion,p.money(),p.coin(),p.xp(),rewardHash(p),reason,actor,key,ts(now));return overrideReplay(f,key).orElseThrow();}
 @Override public RewardGrant governReward(UUID f,UUID c,UUID completion,RewardGrant proposed,UUID actor,String reviewKey,Instant now){Optional<BudgetRule> maybe=jdbc.query("SELECT * FROM reward_budget_rule WHERE family_id=? AND child_id=? AND active=TRUE FOR UPDATE",this::budgetRow,f,c).stream().findFirst();if(maybe.isEmpty())return proposed;BudgetRule r=maybe.get();Bounds b=bounds(r.zoneId(),now);BigDecimal remaining=min(r.dailyMoneyLimit().subtract(spentRewards(f,c,b.day(),now)),r.weeklyMoneyLimit().subtract(spentRewards(f,c,b.week(),now)),r.monthlyMoneyLimit().subtract(spentRewards(f,c,b.month(),now))).max(BigDecimal.ZERO),overflow=proposed.money().subtract(proposed.money().min(remaining)).max(BigDecimal.ZERO);UUID override=null;RewardGrant actual=proposed;if(overflow.signum()>0&&r.overflowPolicy()==OverflowPolicy.HOLD_FOR_PARENT){var rows=jdbc.query("SELECT * FROM reward_budget_override WHERE family_id=? AND child_id=? AND completion_id=? AND reward_hash=? AND consumed_at IS NULL ORDER BY created_at FOR UPDATE",this::overrideRow,f,c,completion,rewardHash(proposed));if(rows.isEmpty())throw new Stage3Service.ConflictException("Reward exceeds budget; parent override is required");override=rows.get(0).id();}else if(overflow.signum()>0)actual=Stage28RewardModels.convert(proposed,remaining,r.overflowPolicy(),r.excessCoinPerMoney(),r.excessXpPerMoney());UUID decision=UUID.randomUUID();jdbc.update("INSERT INTO reward_budget_decision(id,family_id,child_id,completion_id,rule_id,rule_version,overflow_policy,proposed_money,proposed_coin,proposed_xp,actual_money,actual_coin,actual_xp,overflow_money,override_id,actor_id,review_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",decision,f,c,completion,r.id(),r.version(),r.overflowPolicy().name(),proposed.money(),proposed.coin(),proposed.xp(),actual.money(),actual.coin(),actual.xp(),overflow,override,actor,reviewKey,ts(now));if(override!=null)jdbc.update("UPDATE reward_budget_override SET consumed_at=?,decision_id=? WHERE family_id=? AND id=? AND consumed_at IS NULL",ts(now),decision,f,override);return actual;}
 @Override public ExchangeControlRule createExchangeControl(UUID f,boolean m2c,boolean c2m,BigDecimal md,BigDecimal mm,BigDecimal cd,BigDecimal cm,boolean approval,String zone,UUID actor,String key,String hash,Instant now){jdbc.queryForObject("SELECT id FROM family WHERE id=? FOR UPDATE",UUID.class,f);Long v=jdbc.queryForObject("SELECT COALESCE(MAX(rule_version),0)+1 FROM exchange_control_rule WHERE family_id=?",Long.class,f);jdbc.update("UPDATE exchange_control_rule SET active=FALSE WHERE family_id=? AND active=TRUE",f);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO exchange_control_rule(id,family_id,rule_version,money_to_coin_enabled,coin_to_money_enabled,money_to_coin_daily_limit,money_to_coin_monthly_limit,coin_to_money_daily_limit,coin_to_money_monthly_limit,child_requires_parent_approval,zone_id,active,actor_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,TRUE,?,?)",id,f,v,m2c,c2m,md,mm,cd,cm,approval,zone,actor,ts(now));jdbc.update("INSERT INTO exchange_control_action(id,family_id,rule_id,actor_id,action_type,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?, 'ACTIVATE',?,?,?)",UUID.randomUUID(),f,id,actor,key,hash,ts(now));return exchange(f,id,false).orElseThrow();}
 @Override public Optional<ExchangeControlRule> exchangeControlReplay(UUID f,String key){return jdbc.query("SELECT r.* FROM exchange_control_action a JOIN exchange_control_rule r ON r.id=a.rule_id WHERE a.family_id=? AND a.idempotency_key=?",this::exchangeRow,f,key).stream().findFirst();}
 @Override public Optional<ExchangeControlRule> activeExchangeControl(UUID f){return jdbc.query("SELECT * FROM exchange_control_rule WHERE family_id=? AND active=TRUE",this::exchangeRow,f).stream().findFirst();}
 @Override public void validateAndBindPreview(UUID f,UUID c,ExchangeDirection d,BigDecimal source,UUID preview,Instant now){Optional<ExchangeControlRule> maybe=activeExchangeControl(f);if(maybe.isEmpty())return;ExchangeControlRule r=maybe.get();requireDirection(r,d);ensureQuotaRows(r,f,c,d,now);checkQuota(r,f,c,d,source,now);jdbc.update("UPDATE exchange_preview SET control_rule_id=?,control_rule_version=? WHERE family_id=? AND child_id=? AND id=?",r.id(),r.version(),f,c,preview);}
 @Override public void validateExchangeConfirm(UUID f,UUID preview,boolean childActor,Instant now){PreviewControl p=jdbc.query("SELECT child_id,direction,source_amount,control_rule_id,control_rule_version FROM exchange_preview WHERE family_id=? AND id=?",(rs,n)->new PreviewControl(uuid(rs,"child_id"),ExchangeDirection.valueOf(rs.getString("direction")),rs.getBigDecimal("source_amount"),uuid(rs,"control_rule_id"),nullableLong(rs,"control_rule_version")),f,preview).stream().findFirst().orElseThrow(FamilyGrowthService.NotFoundException::new);if(p.rule()==null)return;ExchangeControlRule r=exchange(f,p.rule(),true).orElseThrow(()->new Stage3Service.ConflictException("Exchange control changed; preview again"));if(!r.active()||r.version()!=p.version())throw new Stage3Service.ConflictException("Exchange control changed; preview again");if(childActor&&r.childRequiresParentApproval())throw new Stage3Service.ForbiddenException();requireDirection(r,p.direction());ensureQuotaRows(r,f,p.child(),p.direction(),now);reserveQuota(r,f,p.child(),p.direction(),p.source(),now);}
 @Override public Optional<ExchangeApproval> approvalReplay(UUID f,String key){return jdbc.query("SELECT * FROM exchange_approval_request WHERE family_id=? AND submit_key=?",this::approvalRow,f,key).stream().findFirst();}
 @Override public Optional<ExchangeApproval> approval(UUID f,UUID id){return jdbc.query("SELECT * FROM exchange_approval_request WHERE family_id=? AND id=?",this::approvalRow,f,id).stream().findFirst();}
 @Override public List<ExchangeApproval> approvals(UUID f,UUID c){lockExists(f,c);return jdbc.query("SELECT * FROM exchange_approval_request WHERE family_id=? AND child_id=? ORDER BY created_at DESC",this::approvalRow,f,c);}
 @Override public ExchangeApproval submitApproval(UUID f,UUID c,UUID preview,UUID actor,String key,Instant now){int valid=jdbc.queryForObject("SELECT COUNT(*) FROM exchange_preview p JOIN exchange_control_rule r ON r.id=p.control_rule_id WHERE p.family_id=? AND p.child_id=? AND p.id=? AND p.status='OPEN' AND p.expires_at>? AND r.active=TRUE AND r.child_requires_parent_approval=TRUE",Integer.class,f,c,preview,ts(now));if(valid!=1)throw new Stage3Service.ConflictException("Exchange preview is not eligible for parent approval");UUID id=UUID.randomUUID();jdbc.update("INSERT INTO exchange_approval_request(id,family_id,child_id,preview_id,status,submit_key,submitted_by,created_at) VALUES(?,?,?,?,'PENDING',?,?,?)",id,f,c,preview,key,actor,ts(now));return approval(f,id).orElseThrow();}
 @Override public ExchangeApproval finishApproval(UUID f,UUID id,boolean approved,String note,UUID order,UUID actor,String key,Instant now){ExchangeApproval old=jdbc.query("SELECT * FROM exchange_approval_request WHERE family_id=? AND id=? FOR UPDATE",this::approvalRow,f,id).stream().findFirst().orElseThrow(FamilyGrowthService.NotFoundException::new);ApprovalStatus target=approved?ApprovalStatus.APPROVED:ApprovalStatus.REJECTED;if(old.status()!=ApprovalStatus.PENDING){if(old.status()==target&&Objects.equals(old.reviewKey(),key))return old;throw new Stage3Service.ConflictException("Exchange approval was already reviewed");}jdbc.update("UPDATE exchange_approval_request SET status=?,review_key=?,reviewed_by=?,review_note=?,order_id=?,reviewed_at=? WHERE family_id=? AND id=? AND status='PENDING'",target.name(),key,actor,note,order,ts(now),f,id);return approval(f,id).orElseThrow();}
 @Override public Optional<Fulfillment> fulfillmentReplay(UUID f,String key){return jdbc.query("SELECT id,child_id,product_title,fulfillment_note,fulfilled_by,fulfilled_at FROM reward_order WHERE family_id=? AND fulfill_key=?",this::fulfillmentRow,f,key).stream().findFirst();}
 @Override public Fulfillment fulfill(UUID f,UUID order,String note,UUID actor,String key,Instant now){var row=jdbc.query("SELECT status,fulfill_key,child_id,product_title FROM reward_order WHERE family_id=? AND id=? FOR UPDATE",(rs,n)->new OrderLock(rs.getString(1),rs.getString(2),uuid(rs,"child_id"),rs.getString("product_title")),f,order).stream().findFirst().orElseThrow(FamilyGrowthService.NotFoundException::new);if(row.status().equals("FULFILLED")){if(Objects.equals(row.key(),key))return fulfillmentReplay(f,key).orElseThrow();throw new Stage3Service.ConflictException("Reward order is already fulfilled");}if(!row.status().equals("APPROVED"))throw new Stage3Service.ConflictException("Only an approved reward can be fulfilled");jdbc.update("UPDATE reward_order SET status='FULFILLED',fulfillment_note=?,fulfill_key=?,fulfilled_by=?,fulfilled_at=? WHERE family_id=? AND id=? AND status='APPROVED'",note,key,actor,ts(now),f,order);jdbc.update("INSERT INTO reward_order_action(id,family_id,child_id,order_id,actor_id,action_type,old_status,new_status,note,idempotency_key,created_at) VALUES(?,?,?,?,?,'FULFILL','APPROVED','FULFILLED',?,?,?)",UUID.randomUUID(),f,row.child(),order,actor,note,key,ts(now));return fulfillmentReplay(f,key).orElseThrow();}
 @Override public void redactChildFreeText(UUID f,UUID c){jdbc.update("UPDATE reward_budget_override SET reason='[已删除]' WHERE family_id=? AND child_id=?",f,c);jdbc.update("UPDATE exchange_approval_request SET review_note='[已删除]' WHERE family_id=? AND child_id=?",f,c);jdbc.update("UPDATE reward_order SET fulfillment_note='[已删除]' WHERE family_id=? AND child_id=? AND fulfillment_note IS NOT NULL",f,c);jdbc.update("UPDATE reward_order_action SET note='[已删除]' WHERE family_id=? AND child_id=?",f,c);}
 private void requireDirection(ExchangeControlRule r,ExchangeDirection d){if(!r.enabled(d))throw new Stage3Service.ConflictException("This exchange direction is disabled");}
 private void ensureQuotaRows(ExchangeControlRule r,UUID f,UUID c,ExchangeDirection d,Instant now){Bounds b=bounds(r.zoneId(),now);ensureQuotaRow(f,c,d,"DAY",r.zoneId(),b.day(),now);ensureQuotaRow(f,c,d,"MONTH",r.zoneId(),b.month(),now);}
 private void ensureQuotaRow(UUID f,UUID c,ExchangeDirection d,String type,String zone,Instant start,Instant now){java.sql.Date date=periodDate(zone,start);if(jdbc.queryForObject("SELECT COUNT(*) FROM exchange_quota_usage WHERE family_id=? AND child_id=? AND direction=? AND period_type=? AND period_start=?",Integer.class,f,c,d.name(),type,date)>0)return;BigDecimal initial=spentExchange(f,c,d,start,now);try{jdbc.update("INSERT INTO exchange_quota_usage(family_id,child_id,direction,period_type,period_start,used_source,updated_at) VALUES(?,?,?,?,?,?,?)",f,c,d.name(),type,date,initial,ts(now));}catch(org.springframework.dao.DuplicateKeyException ignored){/* another preview initialized the same bucket */}}
 private void checkQuota(ExchangeControlRule r,UUID f,UUID c,ExchangeDirection d,BigDecimal source,Instant now){Bounds b=bounds(r.zoneId(),now);BigDecimal day=quotaUsed(f,c,d,"DAY",r.zoneId(),b.day()),month=quotaUsed(f,c,d,"MONTH",r.zoneId(),b.month());if(day.add(source).compareTo(r.daily(d))>0||month.add(source).compareTo(r.monthly(d))>0)throw new Stage3Service.ConflictException("Exchange quota would be exceeded");}
 private void reserveQuota(ExchangeControlRule r,UUID f,UUID c,ExchangeDirection d,BigDecimal source,Instant now){Bounds b=bounds(r.zoneId(),now);if(incrementQuota(f,c,d,"DAY",r.zoneId(),b.day(),source,r.daily(d),now)!=1)throw new Stage3Service.ConflictException("Exchange quota would be exceeded");if(incrementQuota(f,c,d,"MONTH",r.zoneId(),b.month(),source,r.monthly(d),now)!=1)throw new Stage3Service.ConflictException("Exchange quota would be exceeded");}
 private BigDecimal quotaUsed(UUID f,UUID c,ExchangeDirection d,String type,String zone,Instant start){return jdbc.queryForObject("SELECT used_source FROM exchange_quota_usage WHERE family_id=? AND child_id=? AND direction=? AND period_type=? AND period_start=?",BigDecimal.class,f,c,d.name(),type,periodDate(zone,start)).setScale(2);}
 private int incrementQuota(UUID f,UUID c,ExchangeDirection d,String type,String zone,Instant start,BigDecimal source,BigDecimal limit,Instant now){return jdbc.update("UPDATE exchange_quota_usage SET used_source=used_source+?,updated_at=? WHERE family_id=? AND child_id=? AND direction=? AND period_type=? AND period_start=? AND used_source+?<=?",source,ts(now),f,c,d.name(),type,periodDate(zone,start),source,limit);}
 private static java.sql.Date periodDate(String zone,Instant start){return java.sql.Date.valueOf(start.atZone(ZoneId.of(zone)).toLocalDate());}
 private BigDecimal spentRewards(UUID f,UUID c,Instant from,Instant to){return jdbc.queryForObject("SELECT COALESCE(SUM(money_reward),0) FROM task_completion WHERE family_id=? AND child_id=? AND status='APPROVED' AND reviewed_at>=? AND reviewed_at<?",BigDecimal.class,f,c,ts(from),ts(to)).setScale(2);}
 private BigDecimal spentExchange(UUID f,UUID c,ExchangeDirection d,Instant from,Instant to){return jdbc.queryForObject("SELECT COALESCE(SUM(source_amount),0) FROM exchange_order WHERE family_id=? AND child_id=? AND direction=? AND created_at>=? AND created_at<?",BigDecimal.class,f,c,d.name(),ts(from),ts(to)).setScale(2);}
 private Optional<BudgetRule> budget(UUID f,UUID c,UUID id,boolean lock){return jdbc.query("SELECT * FROM reward_budget_rule WHERE family_id=? AND child_id=? AND id=?"+(lock?" FOR UPDATE":""),this::budgetRow,f,c,id).stream().findFirst();}private Optional<ExchangeControlRule> exchange(UUID f,UUID id,boolean lock){return jdbc.query("SELECT * FROM exchange_control_rule WHERE family_id=? AND id=?"+(lock?" FOR UPDATE":""),this::exchangeRow,f,id).stream().findFirst();}
 private BudgetRule budgetRow(ResultSet r,int n)throws SQLException{return new BudgetRule(uuid(r,"id"),uuid(r,"child_id"),r.getLong("rule_version"),r.getString("zone_id"),r.getBigDecimal("daily_money_limit"),r.getBigDecimal("weekly_money_limit"),r.getBigDecimal("monthly_money_limit"),OverflowPolicy.valueOf(r.getString("overflow_policy")),r.getBigDecimal("excess_coin_per_money"),r.getBigDecimal("excess_xp_per_money"),r.getBoolean("active"),instant(r,"created_at"));}
 private BudgetOverride overrideRow(ResultSet r,int n)throws SQLException{return new BudgetOverride(uuid(r,"id"),uuid(r,"child_id"),uuid(r,"completion_id"),new RewardGrant(r.getLong("proposed_xp"),r.getLong("proposed_coin"),r.getBigDecimal("proposed_money")),r.getString("reason"),instant(r,"created_at"),instant(r,"consumed_at"));}
 private ExchangeControlRule exchangeRow(ResultSet r,int n)throws SQLException{return new ExchangeControlRule(uuid(r,"id"),uuid(r,"family_id"),r.getLong("rule_version"),r.getBoolean("money_to_coin_enabled"),r.getBoolean("coin_to_money_enabled"),r.getBigDecimal("money_to_coin_daily_limit"),r.getBigDecimal("money_to_coin_monthly_limit"),r.getBigDecimal("coin_to_money_daily_limit"),r.getBigDecimal("coin_to_money_monthly_limit"),r.getBoolean("child_requires_parent_approval"),r.getString("zone_id"),r.getBoolean("active"),instant(r,"created_at"));}
 private ExchangeApproval approvalRow(ResultSet r,int n)throws SQLException{return new ExchangeApproval(uuid(r,"id"),uuid(r,"child_id"),uuid(r,"preview_id"),ApprovalStatus.valueOf(r.getString("status")),r.getString("submit_key"),r.getString("review_key"),r.getString("review_note"),uuid(r,"order_id"),instant(r,"created_at"),instant(r,"reviewed_at"));}
 private Fulfillment fulfillmentRow(ResultSet r,int n)throws SQLException{return new Fulfillment(uuid(r,"id"),uuid(r,"child_id"),r.getString("product_title"),r.getString("fulfillment_note"),uuid(r,"fulfilled_by"),instant(r,"fulfilled_at"));}
 private void lockChild(UUID f,UUID c){if(jdbc.query("SELECT id FROM child_profile WHERE family_id=? AND id=? FOR UPDATE",(r,n)->uuid(r,"id"),f,c).isEmpty())throw new FamilyGrowthService.NotFoundException();}private void lockExists(UUID f,UUID c){if(jdbc.queryForObject("SELECT COUNT(*) FROM child_profile WHERE family_id=? AND id=?",Integer.class,f,c)!=1)throw new FamilyGrowthService.NotFoundException();}private void lockCompletion(UUID f,UUID c,UUID id){List<String> rows=jdbc.query("SELECT status FROM task_completion WHERE family_id=? AND child_id=? AND id=? FOR UPDATE",(r,n)->r.getString(1),f,c,id);if(rows.isEmpty())throw new FamilyGrowthService.NotFoundException();if(!rows.get(0).equals("SUBMITTED"))throw new Stage3Service.ConflictException("Only a submitted completion can receive a budget override");}
 private static Bounds bounds(String zone,Instant now){ZoneId z=ZoneId.of(zone);ZonedDateTime n=now.atZone(z),day=n.toLocalDate().atStartOfDay(z),week=n.toLocalDate().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)).atStartOfDay(z),month=n.toLocalDate().withDayOfMonth(1).atStartOfDay(z);return new Bounds(day.toInstant(),week.toInstant(),month.toInstant());}private static BigDecimal min(BigDecimal...v){return Arrays.stream(v).min(BigDecimal::compareTo).orElse(BigDecimal.ZERO);}private static String rewardHash(RewardGrant p){return hash(p.money().toPlainString()+"|"+p.coin()+"|"+p.xp());}private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static UUID uuid(ResultSet r,String n)throws SQLException{return r.getObject(n,UUID.class);}private static Long nullableLong(ResultSet r,String n)throws SQLException{long v=r.getLong(n);return r.wasNull()?null:v;}private static Instant instant(ResultSet r,String n)throws SQLException{Timestamp v=r.getTimestamp(n);return v==null?null:v.toInstant();}private static Timestamp ts(Instant v){return Timestamp.from(v);}private record Bounds(Instant day,Instant week,Instant month){}private record PreviewControl(UUID child,ExchangeDirection direction,BigDecimal source,UUID rule,Long version){}private record OrderLock(String status,String key,UUID child,String title){}
}
