package com.familygrowth.infrastructure;

import com.familygrowth.application.FamilyGrowthService;
import com.familygrowth.application.Stage25SeniorStore;
import com.familygrowth.application.Stage3Service;
import com.familygrowth.domain.Stage21TeachingModels.AssignmentStatus;
import com.familygrowth.domain.Stage23LearningModels.SubjectLearningFacts;
import com.familygrowth.domain.Stage25SeniorModels.*;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
class JdbcStage25SeniorStore implements Stage25SeniorStore {
    private final JdbcTemplate jdbc;JdbcStage25SeniorStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
    @Override public ModuleConfiguration modules(UUID familyId,UUID childId,Instant now){requireChild(familyId,childId);ensureConfig(familyId,childId,now);return readModules(familyId,childId);}
    @Override public ModuleConfiguration updateModules(UUID familyId,UUID childId,List<ModuleSelection> selections,long expected,String reason,UUID actor,String key,String hash,Instant now){
        modules(familyId,childId,now);long revision=lockConfig(familyId,childId);if(revision!=expected)throw new Stage3Service.ConflictException("Senior module revision conflict");String old=snapshot(readSelections(familyId,childId));
        jdbc.update("DELETE FROM senior_module_selection WHERE family_id=? AND child_id=?",familyId,childId);
        for(ModuleSelection value:selections)jdbc.update("INSERT INTO senior_module_selection(id,family_id,child_id,subject_code,module_type,created_at) VALUES(?,?,?,?,?,?)",UUID.randomUUID(),familyId,childId,value.subjectCode(),value.moduleType().name(),Timestamp.from(now));
        jdbc.update("UPDATE senior_module_config SET revision=revision+1,updated_at=? WHERE family_id=? AND child_id=?",Timestamp.from(now),familyId,childId);
        jdbc.update("INSERT INTO senior_module_action(id,family_id,child_id,actor_id,old_revision,new_revision,old_snapshot,new_snapshot,reason,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),familyId,childId,actor,revision,revision+1,old,snapshot(selections),reason,key,hash,Timestamp.from(now));return readModules(familyId,childId);
    }
    @Override public Optional<ModuleReplay> moduleReplay(UUID familyId,String key){return jdbc.query("SELECT child_id,payload_hash FROM senior_module_action WHERE family_id=? AND idempotency_key=?",(rs,row)->new ModuleReplay(rs.getObject(1,UUID.class),rs.getString(2)),familyId,key).stream().findFirst();}
    @Override public boolean moduleEnabled(UUID familyId,UUID childId,ModuleSelection value){return jdbc.queryForObject("SELECT COUNT(*) FROM senior_module_selection WHERE family_id=? AND child_id=? AND subject_code=? AND module_type=?",Integer.class,familyId,childId,value.subjectCode(),value.moduleType().name())==1;}
    @Override public List<WeeklyGoal> goals(UUID familyId,UUID childId){requireChild(familyId,childId);return jdbc.query("SELECT * FROM senior_weekly_goal WHERE family_id=? AND child_id=? ORDER BY week_start DESC,created_at,id",(rs,row)->new WeeklyGoal(rs.getObject("id",UUID.class),childId,rs.getObject("assignment_id",UUID.class),new ModuleSelection(rs.getString("subject_code"),ModuleType.valueOf(rs.getString("module_type"))),rs.getObject("week_start",LocalDate.class),rs.getString("title"),rs.getString("evidence_target"),rs.getString("next_action"),GoalStatus.valueOf(rs.getString("status")),rs.getLong("revision"),rs.getTimestamp("created_at").toInstant(),rs.getTimestamp("updated_at").toInstant()),familyId,childId);}
    @Override public WeeklyGoal createGoal(UUID familyId,UUID childId,UUID assignmentId,ModuleSelection module,LocalDate week,String title,String evidence,String next,UUID actor,String key,String hash,Instant now){
        requireChild(familyId,childId);requireAssignment(familyId,childId,assignmentId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO senior_weekly_goal(id,family_id,child_id,assignment_id,subject_code,module_type,week_start,title,evidence_target,next_action,status,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'ACTIVE',0,?,?)",id,familyId,childId,assignmentId,module.subjectCode(),module.moduleType().name(),week,title,evidence,next,Timestamp.from(now),Timestamp.from(now));goalAction(familyId,childId,id,actor,"CREATE",0,0,key,hash,now);return goal(familyId,childId,id);}
    @Override public WeeklyGoal updateGoal(UUID familyId,UUID childId,UUID id,String title,String evidence,String next,long expected,UUID actor,String key,String hash,Instant now){int changed=jdbc.update("UPDATE senior_weekly_goal SET title=?,evidence_target=?,next_action=?,revision=revision+1,updated_at=? WHERE family_id=? AND child_id=? AND id=? AND status='ACTIVE' AND revision=?",title,evidence,next,Timestamp.from(now),familyId,childId,id,expected);requireChanged(changed,familyId,childId,id);goalAction(familyId,childId,id,actor,"UPDATE",expected,expected+1,key,hash,now);return goal(familyId,childId,id);}
    @Override public WeeklyGoal archiveGoal(UUID familyId,UUID childId,UUID id,long expected,UUID actor,String key,String hash,Instant now){int changed=jdbc.update("UPDATE senior_weekly_goal SET status='ARCHIVED',revision=revision+1,updated_at=? WHERE family_id=? AND child_id=? AND id=? AND status='ACTIVE' AND revision=?",Timestamp.from(now),familyId,childId,id,expected);requireChanged(changed,familyId,childId,id);goalAction(familyId,childId,id,actor,"ARCHIVE",expected,expected+1,key,hash,now);return goal(familyId,childId,id);}
    @Override public Optional<GoalReplay> goalReplay(UUID familyId,String key){return jdbc.query("SELECT child_id,goal_id,action_type,payload_hash FROM senior_goal_action WHERE family_id=? AND idempotency_key=?",(rs,row)->new GoalReplay(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getString(3),rs.getString(4)),familyId,key).stream().findFirst();}
    @Override public List<Reflection> reflections(UUID familyId,UUID childId){requireChild(familyId,childId);return jdbc.query("SELECT * FROM senior_reflection WHERE family_id=? AND child_id=? ORDER BY created_at DESC,id",(rs,row)->new Reflection(rs.getObject("id",UUID.class),childId,rs.getObject("goal_id",UUID.class),rs.getObject("assignment_id",UUID.class),rs.getString("evidence_summary"),ReflectionStrategy.valueOf(rs.getString("strategy")),rs.getString("next_action"),rs.getBoolean("support_requested"),rs.getTimestamp("created_at").toInstant()),familyId,childId);}
    @Override public Reflection reflect(UUID familyId,UUID childId,UUID goalId,UUID assignmentId,String evidence,ReflectionStrategy strategy,String next,boolean support,UUID actor,String key,String hash,Instant now){requireChild(familyId,childId);if(goalId!=null&&jdbc.queryForObject("SELECT COUNT(*) FROM senior_weekly_goal WHERE family_id=? AND child_id=? AND id=?",Integer.class,familyId,childId,goalId)!=1)throw new FamilyGrowthService.NotFoundException();requireAssignment(familyId,childId,assignmentId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO senior_reflection(id,family_id,child_id,goal_id,assignment_id,evidence_summary,strategy,next_action,support_requested,actor_id,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,familyId,childId,goalId,assignmentId,evidence,strategy.name(),next,support,actor,key,hash,Timestamp.from(now));return reflections(familyId,childId).stream().filter(v->v.id().equals(id)).findFirst().orElseThrow();}
    @Override public Optional<ReflectionReplay> reflectionReplay(UUID familyId,String key){return jdbc.query("SELECT child_id,id,payload_hash FROM senior_reflection WHERE family_id=? AND idempotency_key=?",(rs,row)->new ReflectionReplay(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getString(3)),familyId,key).stream().findFirst();}
    @Override public List<SubjectLearningFacts> facts(UUID familyId,UUID childId,Instant now){requireChild(familyId,childId);Map<String,long[]> out=new LinkedHashMap<>();jdbc.query("SELECT c.subject_code,a.status,COUNT(*) FROM lesson_assignment a JOIN teaching_course_version v ON v.id=a.course_version_id JOIN teaching_course c ON c.id=v.course_id WHERE a.family_id=? AND a.child_id=? AND c.school_stage='SENIOR_HIGH' GROUP BY c.subject_code,a.status ORDER BY c.subject_code,a.status",rs->{long[] x=out.computeIfAbsent(rs.getString(1),v->new long[8]);long n=rs.getLong(3);switch(AssignmentStatus.valueOf(rs.getString(2))){case ASSIGNED->x[0]+=n;case IN_PROGRESS->x[1]+=n;case SUBMITTED->x[2]+=n;case COMPLETED->x[3]+=n;case REWORK_REQUIRED->x[4]+=n;}},familyId,childId);jdbc.query("""
        SELECT c.subject_code,
        SUM(CASE WHEN s.event_type IN ('HELP_REQUESTED','INCORRECT_OBSERVED') AND NOT EXISTS(SELECT 1 FROM learning_support_event x WHERE x.parent_event_id=s.id AND x.event_type='MISCONCEPTION_CLASSIFIED') THEN 1 ELSE 0 END),
        SUM(CASE WHEN s.event_type='REVISIT_SCHEDULED' AND NOT EXISTS(SELECT 1 FROM learning_support_event x WHERE x.parent_event_id=s.id AND x.event_type='REVISIT_COMPLETED') THEN 1 ELSE 0 END),
        SUM(CASE WHEN s.event_type='REVISIT_SCHEDULED' AND s.revisit_at<=? AND NOT EXISTS(SELECT 1 FROM learning_support_event x WHERE x.parent_event_id=s.id AND x.event_type='REVISIT_COMPLETED') THEN 1 ELSE 0 END)
        FROM learning_support_event s JOIN lesson_assignment a ON a.id=s.assignment_id JOIN teaching_course_version v ON v.id=a.course_version_id JOIN teaching_course c ON c.id=v.course_id
        WHERE s.family_id=? AND s.child_id=? AND c.school_stage='SENIOR_HIGH' GROUP BY c.subject_code ORDER BY c.subject_code
        """,rs->{long[] x=out.computeIfAbsent(rs.getString(1),v->new long[8]);x[5]=rs.getLong(2);x[6]=rs.getLong(3);x[7]=rs.getLong(4);},Timestamp.from(now),familyId,childId);return out.entrySet().stream().map(e->{long[]x=e.getValue();return new SubjectLearningFacts(e.getKey(),x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7]);}).toList();}
    @Override public long recordedLearningMinutes(UUID familyId,UUID childId,Instant from,Instant to){requireChild(familyId,childId);Long v=jdbc.queryForObject("SELECT COALESCE(SUM(minutes),0) FROM usage_event WHERE family_id=? AND child_id=? AND event_type='LEARNING' AND occurred_at>=? AND occurred_at<?",Long.class,familyId,childId,Timestamp.from(from),Timestamp.from(to));return v==null?0:v;}
    @Override public long countGoals(UUID familyId,UUID childId,GoalStatus status){return jdbc.queryForObject("SELECT COUNT(*) FROM senior_weekly_goal WHERE family_id=? AND child_id=? AND status=?",Long.class,familyId,childId,status.name());}
    @Override public long countReflections(UUID familyId,UUID childId,Instant from,boolean support){return jdbc.queryForObject("SELECT COUNT(*) FROM senior_reflection WHERE family_id=? AND child_id=? AND created_at>=?"+(support?" AND support_requested=TRUE":""),Long.class,familyId,childId,Timestamp.from(from));}
    private void ensureConfig(UUID familyId,UUID childId,Instant now){if(jdbc.queryForObject("SELECT COUNT(*) FROM senior_module_config WHERE family_id=? AND child_id=?",Integer.class,familyId,childId)>0)return;try{jdbc.update("INSERT INTO senior_module_config(child_id,family_id,revision,updated_at) VALUES(?,?,0,?)",childId,familyId,Timestamp.from(now));}catch(DuplicateKeyException ignored){}}
    private long lockConfig(UUID familyId,UUID childId){return jdbc.query("SELECT revision FROM senior_module_config WHERE family_id=? AND child_id=? FOR UPDATE",(rs,row)->rs.getLong(1),familyId,childId).stream().findFirst().orElseThrow(FamilyGrowthService.NotFoundException::new);}
    private ModuleConfiguration readModules(UUID familyId,UUID childId){Object[] h=jdbc.query("SELECT revision,updated_at FROM senior_module_config WHERE family_id=? AND child_id=?",(rs,row)->new Object[]{rs.getLong(1),rs.getTimestamp(2).toInstant()},familyId,childId).stream().findFirst().orElseThrow(FamilyGrowthService.NotFoundException::new);return new ModuleConfiguration(childId,(Long)h[0],readSelections(familyId,childId),(Instant)h[1]);}
    private List<ModuleSelection> readSelections(UUID familyId,UUID childId){return jdbc.query("SELECT subject_code,module_type FROM senior_module_selection WHERE family_id=? AND child_id=? ORDER BY subject_code,module_type",(rs,row)->new ModuleSelection(rs.getString(1),ModuleType.valueOf(rs.getString(2))),familyId,childId);}
    private String snapshot(List<ModuleSelection> list){return list.stream().map(v->v.subjectCode()+":"+v.moduleType().name()).sorted().collect(java.util.stream.Collectors.joining(","));}
    private WeeklyGoal goal(UUID familyId,UUID childId,UUID id){return goals(familyId,childId).stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(FamilyGrowthService.NotFoundException::new);}
    private void goalAction(UUID familyId,UUID childId,UUID goal,UUID actor,String type,long old,long next,String key,String hash,Instant now){jdbc.update("INSERT INTO senior_goal_action(id,family_id,child_id,goal_id,actor_id,action_type,old_revision,new_revision,idempotency_key,payload_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),familyId,childId,goal,actor,type,old,next,key,hash,Timestamp.from(now));}
    private void requireChanged(int changed,UUID familyId,UUID childId,UUID id){if(changed==1)return;if(jdbc.queryForObject("SELECT COUNT(*) FROM senior_weekly_goal WHERE family_id=? AND child_id=? AND id=?",Integer.class,familyId,childId,id)==0)throw new FamilyGrowthService.NotFoundException();throw new Stage3Service.ConflictException("Senior goal revision or status conflict");}
    private void requireAssignment(UUID familyId,UUID childId,UUID id){if(id==null)return;if(jdbc.queryForObject("SELECT COUNT(*) FROM lesson_assignment a JOIN teaching_course_version v ON v.id=a.course_version_id JOIN teaching_course c ON c.id=v.course_id WHERE a.family_id=? AND a.child_id=? AND a.id=? AND c.school_stage='SENIOR_HIGH'",Integer.class,familyId,childId,id)!=1)throw new FamilyGrowthService.NotFoundException();}
    private void requireChild(UUID familyId,UUID childId){if(jdbc.queryForObject("SELECT COUNT(*) FROM child_profile WHERE family_id=? AND id=?",Integer.class,familyId,childId)!=1)throw new FamilyGrowthService.NotFoundException();}
}
