CREATE TABLE family_sync_checkpoint (
 cursor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 family_id UUID NOT NULL REFERENCES family(id),child_id UUID NOT NULL REFERENCES child_profile(id),actor_id UUID NOT NULL,
 client_id VARCHAR(100) NOT NULL,idempotency_key VARCHAR(100) NOT NULL,request_hash VARCHAR(64) NOT NULL,projection_hash VARCHAR(64) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT uq_family_sync_request UNIQUE(family_id,actor_id,client_id,idempotency_key)
);
CREATE INDEX idx_family_sync_cursor ON family_sync_checkpoint(family_id,child_id,cursor);
