package com.familygrowth.application;
import com.familygrowth.domain.Stage28RewardModels.*;import com.familygrowth.domain.Stage3Models.*;import com.familygrowth.domain.Stage5Models.ExchangeOrder;import java.math.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class Stage28RewardService{
 private final Stage3Service auth;private final Stage28RewardStore store;private final Stage5Service exchange;private final Clock clock;public Stage28RewardService(Stage3Service auth,Stage28RewardStore store,Stage5Service exchange,Clock clock){this.auth=auth;this.store=store;this.exchange=exchange;this.clock=clock;}
 public BudgetRule createBudgetRule(Actor a,UUID f,UUID c,String zone,BigDecimal daily,BigDecimal weekly,BigDecimal monthly,OverflowPolicy policy,BigDecimal coinRate,BigDecimal xpRate,String key){parent(a,f,c);String z=zone(zone),k=key(key);BigDecimal d=money(daily),w=money(weekly),m=money(monthly),cr=rate(coinRate),xr=rate(xpRate);if(d.signum()<0||w.compareTo(d)<0||m.compareTo(w)<0)throw new IllegalArgumentException("Reward budget limits must satisfy 0 <= daily <= weekly <= monthly");if(policy==OverflowPolicy.CONVERT_TO_COIN&&cr.signum()<=0)throw new IllegalArgumentException("Coin conversion rate must be positive");if(policy==OverflowPolicy.CONVERT_TO_XP&&xr.signum()<=0)throw new IllegalArgumentException("XP conversion rate must be positive");String h=hash(c+"|"+z+"|"+d+"|"+w+"|"+m+"|"+policy+"|"+cr+"|"+xr);var replay=store.budgetRuleReplay(f,k);if(replay.isPresent()){BudgetRule r=replay.get();if(!r.childId().equals(c)||!r.zoneId().equals(z)||r.dailyMoneyLimit().compareTo(d)!=0||r.weeklyMoneyLimit().compareTo(w)!=0||r.monthlyMoneyLimit().compareTo(m)!=0||r.overflowPolicy()!=policy||r.excessCoinPerMoney().compareTo(cr)!=0||r.excessXpPerMoney().compareTo(xr)!=0)throw new Stage3Service.ConflictException("Idempotency-Key payload mismatch");return r;}return store.createBudgetRule(f,c,z,d,w,m,Objects.requireNonNull(policy),cr,xr,a.actorId(),k,h,clock.instant());}
 @Transactional(readOnly=true)public Optional<BudgetRule> activeBudgetRule(Actor a,UUID f,UUID c){parent(a,f,c);return store.activeBudgetRule(f,c);}@Transactional(readOnly=true)public BudgetSummary budgetSummary(Actor a,UUID f,UUID c){parent(a,f,c);return store.budgetSummary(f,c,clock.instant());}
 public BudgetOverride createOverride(Actor a,UUID f,UUID c,UUID completion,RewardGrant proposed,String reason,String key){parent(a,f,c);String why=text(reason,"reason",500),k=key(key),h=hash(c+"|"+completion+"|"+proposed.money()+"|"+proposed.coin()+"|"+proposed.xp()+"|"+why);var replay=store.overrideReplay(f,k);if(replay.isPresent()){var r=replay.get();if(!r.childId().equals(c)||!r.completionId().equals(completion)||!r.proposed().equals(proposed)||!r.reason().equals(why))throw new Stage3Service.ConflictException("Idempotency-Key payload mismatch");return r;}return store.createOverride(f,c,completion,proposed,why,a.actorId(),k,h,clock.instant());}
 public ExchangeControlRule createExchangeControl(Actor a,UUID f,boolean m2c,boolean c2m,BigDecimal md,BigDecimal mm,BigDecimal cd,BigDecimal cm,boolean approval,String zone,String key){auth.requireParent(a,f);String z=zone(zone),k=key(key);BigDecimal a1=money(md),a2=money(mm),a3=money(cd),a4=money(cm);if(a1.signum()<0||a2.compareTo(a1)<0||a3.signum()<0||a4.compareTo(a3)<0)throw new IllegalArgumentException("Exchange limits must satisfy 0 <= daily <= monthly");String h=hash(m2c+"|"+c2m+"|"+a1+"|"+a2+"|"+a3+"|"+a4+"|"+approval+"|"+z);var replay=store.exchangeControlReplay(f,k);if(replay.isPresent()){var r=replay.get();if(r.moneyToCoinEnabled()!=m2c||r.coinToMoneyEnabled()!=c2m||r.moneyToCoinDailyLimit().compareTo(a1)!=0||r.moneyToCoinMonthlyLimit().compareTo(a2)!=0||r.coinToMoneyDailyLimit().compareTo(a3)!=0||r.coinToMoneyMonthlyLimit().compareTo(a4)!=0||r.childRequiresParentApproval()!=approval||!r.zoneId().equals(z))throw new Stage3Service.ConflictException("Idempotency-Key payload mismatch");return r;}return store.createExchangeControl(f,m2c,c2m,a1,a2,a3,a4,approval,z,a.actorId(),k,h,clock.instant());}
 @Transactional(readOnly=true)public Optional<ExchangeControlRule> activeExchangeControl(Actor a,UUID f){if(a.role()==ActorRole.CHILD)auth.requireChildOrParent(a,f,a.childId());else auth.requireParent(a,f);return store.activeExchangeControl(f);}
 @Transactional(readOnly=true)public List<ExchangeApproval> exchangeApprovals(Actor a,UUID f,UUID c){auth.requireChildOrParent(a,f,c);return store.approvals(f,c);}
 public ExchangeApproval requestExchangeApproval(Actor a,UUID f,UUID c,UUID preview,String key){auth.requireChildOrParent(a,f,c);if(a.role()!=ActorRole.CHILD)throw new Stage3Service.ForbiddenException();String k=key(key);var replay=store.approvalReplay(f,k);if(replay.isPresent()){var r=replay.get();if(!r.childId().equals(c)||!r.previewId().equals(preview))throw new Stage3Service.ConflictException("Idempotency-Key payload mismatch");return r;}return store.submitApproval(f,c,preview,a.actorId(),k,clock.instant());}
 public ExchangeApproval reviewExchangeApproval(Actor a,UUID f,UUID id,boolean approve,String note,String key){auth.requireParent(a,f);String k=key(key),n=optional(note,500);ExchangeApproval current=store.approval(f,id).orElseThrow(FamilyGrowthService.NotFoundException::new);if(current.status()!=ApprovalStatus.PENDING){if(Objects.equals(current.reviewKey(),k)&&current.status()==(approve?ApprovalStatus.APPROVED:ApprovalStatus.REJECTED))return current;throw new Stage3Service.ConflictException("Exchange approval was already reviewed");}UUID order=null;if(approve){ExchangeOrder confirmed=exchange.confirm(a,f,current.previewId(),k);order=confirmed.id();}return store.finishApproval(f,id,approve,n,order,a.actorId(),k,clock.instant());}
 public Fulfillment fulfill(Actor a,UUID f,UUID order,String note,String key){auth.requireParent(a,f);String k=key(key),n=text(note,"fulfillmentNote",500);var replay=store.fulfillmentReplay(f,k);if(replay.isPresent()){if(!replay.get().orderId().equals(order)||!replay.get().note().equals(n))throw new Stage3Service.ConflictException("Idempotency-Key payload mismatch");return replay.get();}return store.fulfill(f,order,n,a.actorId(),k,clock.instant());}
 private void parent(Actor a,UUID f,UUID c){auth.requireParent(a,f);auth.requireChildOrParent(a,f,c);}private static String key(String v){return text(v,"Idempotency-Key",100);}private static String text(String v,String n,int max){String s=v==null?"":v.trim();if(s.isBlank()||s.length()>max)throw new IllegalArgumentException(n+" is required");return s;}private static String optional(String v,int max){String s=v==null?"":v.trim();if(s.length()>max)throw new IllegalArgumentException("Text is too long");return s;}private static String zone(String v){String z=text(v,"zoneId",64);ZoneId.of(z);return z;}private static BigDecimal money(BigDecimal v){return Objects.requireNonNull(v).setScale(2,RoundingMode.UNNECESSARY);}private static BigDecimal rate(BigDecimal v){return Objects.requireNonNull(v).setScale(6,RoundingMode.UNNECESSARY);}private static String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
