package com.familygrowth.application;
import com.familygrowth.domain.Stage27GrowthModels;import com.familygrowth.domain.Stage27GrowthModels.*;import com.familygrowth.domain.Stage3Models.Actor;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class Stage27GrowthService{
 private static final int MAX_IMAGE=5*1024*1024;private final Stage3Service auth;private final Stage27GrowthStore store;private final Clock clock;
 public Stage27GrowthService(Stage3Service auth,Stage27GrowthStore store,Clock clock){this.auth=auth;this.store=store;this.clock=clock;}
 public List<Plan> plans(Actor a,UUID f,UUID c){parent(a,f,c);return store.plans(f,c);}public List<Goal> goals(Actor a,UUID f,UUID c,UUID p){parent(a,f,c);return store.goals(f,c,p);}public List<Milestone> milestones(Actor a,UUID f,UUID c){parent(a,f,c);return store.milestones(f,c);}
 public Plan createPlan(Actor a,UUID f,UUID c,String title,String desc,GrowthCategory cat,String age,String target,LocalDate start,LocalDate end,PlanStatus status,String key){parent(a,f,c);PlanStatus initial=status==null?PlanStatus.DRAFT:status;if(initial!=PlanStatus.DRAFT&&initial!=PlanStatus.ACTIVE)throw new IllegalArgumentException("A growth plan can only start as DRAFT or ACTIVE");String k=key(key),payload=hash(c+"|PLAN_CREATE|"+title+"|"+desc+"|"+cat+"|"+age+"|"+target+"|"+start+"|"+end+"|"+initial);var replay=store.planReplay(f,k);if(replay.isPresent())return replayPlan(replay.get(),c,"CREATE",payload,f);return store.createPlan(f,c,text(title,"title",120),optional(desc,1000),Objects.requireNonNull(cat),text(age,"ageStage",32),optional(target,500),Objects.requireNonNull(start),end,initial,a.actorId(),k,payload,clock.instant());}
 public Plan transitionPlan(Actor a,UUID f,UUID c,UUID id,PlanStatus to,long revision,String reason,String key){parent(a,f,c);Plan current=store.plan(f,c,id).orElseThrow(FamilyGrowthService.NotFoundException::new);Stage27GrowthModels.requireTransition(current.status(),to);String why=text(reason,"reason",500),k=key(key),payload=hash(c+"|PLAN_TRANSITION|"+id+"|"+to+"|"+revision+"|"+why);var replay=store.planReplay(f,k);if(replay.isPresent())return replayPlan(replay.get(),c,"TRANSITION",payload,f);return store.transitionPlan(f,c,id,current.status(),to,revision,why,a.actorId(),k,payload,clock.instant());}
 public Goal createGoal(Actor a,UUID f,UUID c,UUID p,String title,String desc,String target,String key){parent(a,f,c);Plan plan=store.plan(f,c,p).orElseThrow(FamilyGrowthService.NotFoundException::new);if(plan.status()==PlanStatus.COMPLETED||plan.status()==PlanStatus.CANCELED)throw new Stage3Service.ConflictException("Terminal growth plan cannot accept goals");String k=key(key),payload=hash(c+"|GOAL_CREATE|"+p+"|"+title+"|"+desc+"|"+target);var replay=store.goalReplay(f,k);if(replay.isPresent())return replayGoal(replay.get(),c,"CREATE",payload,f);return store.createGoal(f,c,p,text(title,"title",120),optional(desc,1000),optional(target,500),a.actorId(),k,payload,clock.instant());}
 public Goal transitionGoal(Actor a,UUID f,UUID c,UUID id,GoalStatus to,long revision,String reason,String key){parent(a,f,c);Goal current=store.goal(f,c,id).orElseThrow(FamilyGrowthService.NotFoundException::new);Stage27GrowthModels.requireTransition(current.status(),to);String why=text(reason,"reason",500),k=key(key),payload=hash(c+"|GOAL_TRANSITION|"+id+"|"+to+"|"+revision+"|"+why);var replay=store.goalReplay(f,k);if(replay.isPresent())return replayGoal(replay.get(),c,"TRANSITION",payload,f);return store.transitionGoal(f,c,id,current.status(),to,revision,why,a.actorId(),k,payload,clock.instant());}
 public Milestone createMilestone(Actor a,UUID f,UUID c,UUID p,UUID g,LocalDate day,MilestoneCategory cat,String title,String observation,String key){parent(a,f,c);validRefs(f,c,p,g);validDay(day);String k=key(key),payload=hash(c+"|MILESTONE_CREATE|"+p+"|"+g+"|"+day+"|"+cat+"|"+title+"|"+observation);var replay=store.milestoneReplay(f,k);if(replay.isPresent())return replayMilestone(replay.get(),c,"CREATE",payload,f);return store.createMilestone(f,c,p,g,day,Objects.requireNonNull(cat),text(title,"title",160),text(observation,"observation",1500),a.actorId(),k,payload,clock.instant());}
 public Milestone updateMilestone(Actor a,UUID f,UUID c,UUID id,LocalDate day,MilestoneCategory cat,String title,String observation,long revision,String key){parent(a,f,c);store.milestone(f,c,id).orElseThrow(FamilyGrowthService.NotFoundException::new);validDay(day);String k=key(key),payload=hash(c+"|MILESTONE_UPDATE|"+id+"|"+day+"|"+cat+"|"+title+"|"+observation+"|"+revision);var replay=store.milestoneReplay(f,k);if(replay.isPresent())return replayMilestone(replay.get(),c,"UPDATE",payload,f);return store.updateMilestone(f,c,id,day,Objects.requireNonNull(cat),text(title,"title",160),text(observation,"observation",1500),revision,a.actorId(),k,payload,clock.instant());}
 public ArtifactMetadata addArtifact(Actor a,UUID f,UUID c,UUID milestone,String type,byte[] bytes,String alt,String key){parent(a,f,c);store.milestone(f,c,milestone).orElseThrow(FamilyGrowthService.NotFoundException::new);byte[] content=bytes==null?new byte[0]:bytes.clone();String normalized=validateImage(type,content),sha=hashBytes(content),k=key(key),payload=hash(c+"|ARTIFACT|"+milestone+"|"+normalized+"|"+sha+"|"+alt);var replay=store.artifactReplay(f,k);if(replay.isPresent()){same(replay.get(),c,"CREATE",payload);return store.artifact(f,c,replay.get().resultId()).orElseThrow(FamilyGrowthService.NotFoundException::new).metadata();}return store.createArtifact(f,c,milestone,normalized,content,sha,text(alt,"altText",300),a.actorId(),k,payload,clock.instant());}
 @Transactional(readOnly=true)public Artifact artifact(Actor a,UUID f,UUID c,UUID id){parent(a,f,c);return store.artifact(f,c,id).orElseThrow(FamilyGrowthService.NotFoundException::new);}
 public List<ParentRecordTemplate> templates(Actor a,UUID f,UUID c){parent(a,f,c);return List.of(new ParentRecordTemplate("READ_TOGETHER","一起读过一本书","记录孩子看向、指认或回应的具体动作",MilestoneCategory.PARENT_CHILD_READING),new ParentRecordTemplate("MOVE_TOGETHER","一起动一动","记录孩子完成的现实动作，不比较速度",MilestoneCategory.MOVEMENT),new ParentRecordTemplate("LANGUAGE_MOMENT","今天说了什么","记录一个真实词语、声音或交流回应",MilestoneCategory.LANGUAGE),new ParentRecordTemplate("SELF_CARE_STEP","自己多做了一步","记录穿衣、整理、洗手或用餐中的具体一步",MilestoneCategory.SELF_CARE),new ParentRecordTemplate("CONNECTED_MOMENT","我们互相回应了","记录一次安慰、表达或共同平静的时刻",MilestoneCategory.EMOTIONAL_CONNECTION));}
 public GrowthReport report(Actor a,UUID f,UUID c){parent(a,f,c);return store.report(f,c,clock.instant());}
 private void validRefs(UUID f,UUID c,UUID p,UUID g){if(p!=null)store.plan(f,c,p).orElseThrow(FamilyGrowthService.NotFoundException::new);if(g!=null){Goal goal=store.goal(f,c,g).orElseThrow(FamilyGrowthService.NotFoundException::new);if(p!=null&&!goal.planId().equals(p))throw new FamilyGrowthService.NotFoundException();}}
 private void validDay(LocalDate d){if(d==null||d.isAfter(LocalDate.now(clock)))throw new IllegalArgumentException("occurredOn must not be in the future");}
 private Plan replayPlan(Stage27GrowthStore.Replay r,UUID c,String type,String hash,UUID f){same(r,c,type,hash);return store.plan(f,c,r.resultId()).orElseThrow(FamilyGrowthService.NotFoundException::new);}private Goal replayGoal(Stage27GrowthStore.Replay r,UUID c,String type,String hash,UUID f){same(r,c,type,hash);return store.goal(f,c,r.resultId()).orElseThrow(FamilyGrowthService.NotFoundException::new);}private Milestone replayMilestone(Stage27GrowthStore.Replay r,UUID c,String type,String hash,UUID f){same(r,c,type,hash);return store.milestone(f,c,r.resultId()).orElseThrow(FamilyGrowthService.NotFoundException::new);}
 private static void same(Stage27GrowthStore.Replay r,UUID c,String type,String hash){if(!r.childId().equals(c)||!r.actionType().equals(type)||!r.payloadHash().equals(hash))throw new Stage3Service.ConflictException("Idempotency-Key payload mismatch");}
 private void parent(Actor a,UUID f,UUID c){auth.requireParent(a,f);auth.requireChildOrParent(a,f,c);}private static String key(String v){return text(v,"Idempotency-Key",100);}private static String text(String v,String n,int max){String s=v==null?"":v.trim();if(s.isBlank()||s.length()>max)throw new IllegalArgumentException(n+" is required and must be at most "+max);return s;}private static String optional(String v,int max){String s=v==null?"":v.trim();if(s.length()>max)throw new IllegalArgumentException("Text is too long");return s;}
 private static String validateImage(String type,byte[] b){if(b.length<4||b.length>MAX_IMAGE)throw new IllegalArgumentException("Image must be between 1 byte and 5 MiB");String t=type==null?"":type.toLowerCase(Locale.ROOT).trim();boolean jpeg=b.length>=3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255,png=b.length>=8&&(b[0]&255)==137&&b[1]==80&&b[2]==78&&b[3]==71&&b[4]==13&&b[5]==10&&b[6]==26&&b[7]==10,webp=b.length>=12&&new String(b,0,4,StandardCharsets.US_ASCII).equals("RIFF")&&new String(b,8,4,StandardCharsets.US_ASCII).equals("WEBP");if((t.equals("image/jpeg")&&jpeg)||(t.equals("image/png")&&png)||(t.equals("image/webp")&&webp))return t;throw new IllegalArgumentException("Only genuine JPEG, PNG or WebP images are allowed");}
 private static String hash(String v){return hashBytes(v.getBytes(StandardCharsets.UTF_8));}private static String hashBytes(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}
}
