package com.familygrowth.application;import com.familygrowth.domain.Stage3Models.Actor;import com.familygrowth.domain.Stage9Models.*;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.UUID;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class Stage9Service{private final Stage3Service auth;private final Stage9Store store;private final Clock clock;public Stage9Service(Stage3Service auth,Stage9Store store,Clock clock){this.auth=auth;this.store=store;this.clock=clock;}
 public UsagePolicy configure(Actor actor,UUID family,UUID child,String zone,int daily,int session){return configure(actor,family,child,zone,daily,session,LocalTime.of(21,30),LocalTime.of(6,30));}
 public UsagePolicy configure(Actor actor,UUID family,UUID child,String zone,int daily,int session,LocalTime quietStart,LocalTime quietEnd){auth.requireParent(actor,family);auth.requireChildOrParent(actor,family,child);ZoneId.of(zone);if(daily<10||daily>480||session<5||session>240||session>daily||quietStart==null||quietEnd==null||quietStart.equals(quietEnd))throw new IllegalArgumentException("Usage policy is invalid");return store.upsertPolicy(family,child,zone,daily,session,quietStart,quietEnd,actor.actorId(),clock.instant());}
 @Transactional(readOnly=true)public UsagePolicy policy(Actor actor,UUID family,UUID child){auth.requireChildOrParent(actor,family,child);return store.policy(family,child);}
 public UsageEvent addEvent(Actor actor,UUID family,UUID child,UsageEventType type,int minutes,Instant occurred,String key){auth.requireChildOrParent(actor,family,child);key(key);if(minutes<1||minutes>60)throw new IllegalArgumentException("Usage minutes are invalid");Instant now=clock.instant();if(occurred==null||occurred.isAfter(now.plusSeconds(300))||occurred.isBefore(now.minus(Duration.ofDays(31))))throw new IllegalArgumentException("Usage event time is invalid");occurred=occurred.truncatedTo(ChronoUnit.MICROS);var existing=store.eventByKey(family,key);if(existing.isPresent())return same(existing.get(),child,type,minutes,occurred);return same(store.addEvent(family,child,type,minutes,occurred,key,actor.actorId(),now),child,type,minutes,occurred);}
 @Transactional(readOnly=true)public TodayReport today(Actor actor,UUID family,UUID child,LocalDate date){auth.requireChildOrParent(actor,family,child);UsagePolicy p=store.policy(family,child);ZoneId zone=ZoneId.of(p.zoneId());LocalDate day=date==null?LocalDate.now(clock.withZone(zone)):date;return store.today(family,child,p,day,day.atStartOfDay(zone).toInstant(),day.plusDays(1).atStartOfDay(zone).toInstant());}
 @Transactional(readOnly=true)public MonthlyReport month(Actor actor,UUID family,UUID child,YearMonth month){auth.requireParent(actor,family);auth.requireChildOrParent(actor,family,child);UsagePolicy p=store.policy(family,child);ZoneId zone=ZoneId.of(p.zoneId());YearMonth selected=month==null?YearMonth.now(clock.withZone(zone)):month;return store.month(family,child,p,selected.toString(),selected.atDay(1).atStartOfDay(zone).toInstant(),selected.plusMonths(1).atDay(1).atStartOfDay(zone).toInstant());}
 public TemporaryAllowance allow(Actor actor,UUID family,UUID child,int minutes,String reason,String key){auth.requireParent(actor,family);auth.requireChildOrParent(actor,family,child);key(key);String text=reason==null?"":reason.trim();if(minutes<1||minutes>60||text.isBlank()||text.length()>240)throw new IllegalArgumentException("Temporary allowance is invalid");Instant now=clock.instant().truncatedTo(ChronoUnit.MICROS);String hash=hash(child+"|"+minutes+"|"+text);var existing=store.allowanceByKey(family,key);if(existing.isPresent()){TemporaryAllowance a=existing.get();if(!a.childId().equals(child)||!hash.equals(hash(a.childId()+"|"+Duration.between(a.startsAt(),a.expiresAt()).toMinutes()+"|"+a.reason())))throw new Stage3Service.ConflictException("Idempotency-Key was used for another allowance");return a;}return store.addAllowance(family,child,text,now,now.plus(Duration.ofMinutes(minutes)),key,hash,actor.actorId(),now);}
 @Transactional(readOnly=true)public UsageAccessState access(Actor actor,UUID family,UUID child){auth.requireChildOrParent(actor,family,child);UsagePolicy p=store.policy(family,child);Instant now=clock.instant();ZoneId zone=ZoneId.of(p.zoneId());LocalDate day=LocalDate.now(clock.withZone(zone));int used=store.appMinutes(family,child,day.atStartOfDay(zone).toInstant(),day.plusDays(1).atStartOfDay(zone).toInstant());var allowance=store.activeAllowance(family,child,now);if(allowance.isPresent())return new UsageAccessState(true,"TEMPORARY_ALLOWANCE","家长已临时允许使用，到时会自动结束。",used,p.dailyLimitMinutes(),allowance.get().expiresAt(),now);LocalTime local=LocalTime.now(clock.withZone(zone));boolean quiet=p.quietStart().isBefore(p.quietEnd())?(local.compareTo(p.quietStart())>=0&&local.isBefore(p.quietEnd())):(local.compareTo(p.quietStart())>=0||local.isBefore(p.quietEnd()));if(quiet)return new UsageAccessState(false,"QUIET_HOURS","现在是休息时间。可以阅读、整理或和家人说说今天。",used,p.dailyLimitMinutes(),null,now);if(used>=p.dailyLimitMinutes())return new UsageAccessState(false,"DAILY_LIMIT","今天的屏幕时间到了。先去做一件现实中的事。",used,p.dailyLimitMinutes(),null,now);return new UsageAccessState(true,"AVAILABLE","现在可以使用。记得每段结束后离开屏幕休息。",used,p.dailyLimitMinutes(),null,now);}
 private static String hash(String value){try{byte[] out=java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(out);}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private static UsageEvent same(UsageEvent event,UUID child,UsageEventType type,int minutes,Instant occurred){if(!event.childId().equals(child)||event.type()!=type||event.minutes()!=minutes||!event.occurredAt().equals(occurred))throw new Stage3Service.ConflictException("Idempotency-Key was used for another usage event");return event;}private static void key(String k){if(k==null||k.isBlank()||k.length()>100)throw new IllegalArgumentException("Valid Idempotency-Key is required");}}
