package com.familygrowth.android.remote

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.io.IOException
import java.time.Instant
import java.util.UUID
import java.time.LocalDate
import com.familygrowth.android.core.SchoolStage
import com.familygrowth.android.core.PrimaryGradeBand

data class RemoteTeachingCourseDraft(
 val stage:String,
 val subject:String="FAMILY",
 val courseTitle:String,
 val lessonTitle:String,
 val lessonSummary:String,
 val activityType:String,
 val activityTitle:String,
 val instruction:String,
 val contentRef:String?=null,
 val expectedMinutes:Int=8,
 val rightsBasis:String="家庭原创学习活动",
 val kindergartenAgeBand:String?=null,
 val kindergartenDomains:List<String> = emptyList(),
 val chapterTitle:String?=null,
 val knowledgePoints:List<String> = emptyList(),
 val learningGoal:String?=null,
 val safetyNote:String?=null,
 val seniorModuleType:String?=null,
 val topicTitle:String?=null,
 val inquiryQuestion:String?=null,
 val expectedEvidence:String?=null,
 val seniorSafetyNote:String?=null,
)

interface FamilyApiTransport{
 suspend fun acceptParentPairing(base:String,code:String,deviceName:String):RemoteResult<RemotePairedParent> = RemoteResult.Failure("设备配对暂不可用")
 suspend fun familyChildren(base:String,parentToken:String,family:String):RemoteResult<List<RemoteFamilyChild>> = RemoteResult.Failure("孩子列表暂不可用")
 suspend fun login(base:String,family:String,parent:String,pin:String):RemoteResult<String>
 suspend fun childSession(base:String,parentToken:String,child:String):RemoteResult<String>
 suspend fun snapshot(base:String,token:String,family:String,child:String):RemoteResult<RemoteSnapshot>
 suspend fun experience(base:String,token:String,family:String,child:String):RemoteResult<RemoteExperienceProfile>
 suspend fun updateExperience(base:String,token:String,family:String,child:String,birthDate:LocalDate,stageOverride:SchoolStage?,primaryBandOverride:PrimaryGradeBand?,overrideReason:String,hapticsEnabled:Boolean,expectedVersion:Long):RemoteResult<RemoteExperienceProfile>
 suspend fun educationSources(base:String,token:String,family:String):RemoteResult<List<RemoteEducationSource>>
 suspend fun createEducationSource(base:String,token:String,family:String,title:String,sourceUrl:String,stages:List<SchoolStage>,usageNote:String,key:String):RemoteResult<RemoteEducationSource>
 suspend fun educationSourceAction(base:String,token:String,family:String,source:String,action:String,key:String):RemoteResult<RemoteEducationSource>
 suspend fun childEducationCatalog(base:String,token:String,family:String,child:String):RemoteResult<List<RemoteChildEducationSource>>
 suspend fun learningAssignments(base:String,token:String,family:String,child:String):RemoteResult<List<RemoteLearningAssignment>> = RemoteResult.Failure("课程同步暂不可用")
 suspend fun syncAutonomousLearning(base:String,token:String,family:String,child:String,key:String):RemoteResult<List<RemoteLearningAssignment>> = learningAssignments(base,token,family,child)
 suspend fun learningRewardPolicy(base:String,token:String,family:String,child:String):RemoteResult<RemoteRewardPolicy> = RemoteResult.Failure("奖励规则同步暂不可用")
 suspend fun primaryLearningReport(base:String,token:String,family:String,child:String):RemoteResult<RemotePrimaryLearningReport> = RemoteResult.Failure("小学学习报告暂不可用")
 suspend fun juniorLearningPlan(base:String,token:String,family:String,child:String):RemoteResult<RemoteJuniorPlan> = RemoteResult.Failure("初中计划暂不可用")
 suspend fun juniorLearningReport(base:String,token:String,family:String,child:String):RemoteResult<RemoteJuniorLearningReport> = RemoteResult.Failure("初中学习报告暂不可用")
 suspend fun moveJuniorLearning(base:String,token:String,family:String,child:String,assignment:String,direction:String,revision:Long,key:String):RemoteResult<RemoteJuniorPlan> = RemoteResult.Failure("初中计划调整暂不可用")
 suspend fun seniorModules(base:String,token:String,family:String,child:String):RemoteResult<RemoteSeniorModuleConfiguration> = RemoteResult.Failure("高中模块暂不可用")
 suspend fun updateSeniorModules(base:String,token:String,family:String,child:String,selections:List<RemoteSeniorModule>,revision:Long,key:String):RemoteResult<RemoteSeniorModuleConfiguration> = RemoteResult.Failure("高中模块保存暂不可用")
 suspend fun seniorGoals(base:String,token:String,family:String,child:String):RemoteResult<List<RemoteSeniorGoal>> = RemoteResult.Failure("高中目标暂不可用")
 suspend fun createSeniorGoal(base:String,token:String,family:String,child:String,module:RemoteSeniorModule,assignment:String?,weekStart:String,title:String,evidence:String,next:String,key:String):RemoteResult<RemoteSeniorGoal> = RemoteResult.Failure("高中目标保存暂不可用")
 suspend fun updateSeniorGoal(base:String,token:String,family:String,child:String,goal:String,title:String,evidence:String,next:String,revision:Long,key:String):RemoteResult<RemoteSeniorGoal> = RemoteResult.Failure("高中目标更新暂不可用")
 suspend fun archiveSeniorGoal(base:String,token:String,family:String,child:String,goal:String,revision:Long,key:String):RemoteResult<RemoteSeniorGoal> = RemoteResult.Failure("高中目标归档暂不可用")
 suspend fun seniorReflections(base:String,token:String,family:String,child:String):RemoteResult<List<RemoteSeniorReflection>> = RemoteResult.Failure("高中复盘暂不可用")
 suspend fun createSeniorReflection(base:String,token:String,family:String,child:String,goal:String?,assignment:String?,evidence:String,strategy:String,next:String,support:Boolean,key:String):RemoteResult<RemoteSeniorReflection> = RemoteResult.Failure("高中复盘保存暂不可用")
 suspend fun seniorReport(base:String,token:String,family:String,child:String):RemoteResult<RemoteSeniorLearningReport> = RemoteResult.Failure("高中报告暂不可用")
 suspend fun configureUsage(base:String,token:String,family:String,child:String,daily:Int,session:Int,quietStart:String,quietEnd:String):RemoteResult<RemoteUsagePolicy> = RemoteResult.Failure("防沉迷配置暂不可用")
 suspend fun usageAccess(base:String,token:String,family:String,child:String):RemoteResult<RemoteUsageAccess> = RemoteResult.Failure("使用状态暂不可用")
 suspend fun createUsageAllowance(base:String,token:String,family:String,child:String,minutes:Int,reason:String,key:String):RemoteResult<Unit> = RemoteResult.Failure("临时放行暂不可用")
 suspend fun exportChildData(base:String,token:String,family:String,child:String,key:String):RemoteResult<RemoteChildDataExport> = RemoteResult.Failure("数据导出暂不可用")
 suspend fun erasurePreview(base:String,token:String,family:String,child:String,key:String):RemoteResult<RemoteErasurePreview> = RemoteResult.Failure("删除预览暂不可用")
 suspend fun confirmErasure(base:String,token:String,family:String,child:String,request:String,confirmation:String,pin:String):RemoteResult<RemoteErasureResult> = RemoteResult.Failure("删除确认暂不可用")
 suspend fun stageTransitionPreview(base:String,token:String,family:String,child:String,birthDate:String,override:String?):RemoteResult<RemoteStageTransitionPreview> = RemoteResult.Failure("学段迁移预览暂不可用")
 suspend fun updateLearningRewardPolicy(base:String,token:String,family:String,child:String,money:String,coin:Long,xp:Long,expectedVersion:Long):RemoteResult<RemoteRewardPolicy> = RemoteResult.Failure("奖励规则保存暂不可用")
 suspend fun learningAttempt(base:String,token:String,family:String,child:String,assignment:String,activity:String,response:String,playedSeconds:Int?,durationSeconds:Int?,key:String):RemoteResult<RemoteLearningAssignment> = RemoteResult.Failure("活动提交暂不可用")
 suspend fun learningHelp(base:String,token:String,family:String,child:String,assignment:String,activity:String,message:String,key:String):RemoteResult<RemoteLearningAssignment> = RemoteResult.Failure("求助同步暂不可用")
 suspend fun learningSupportEvents(base:String,token:String,family:String,child:String,assignment:String):RemoteResult<List<RemoteSupportEvent>> = RemoteResult.Failure("学习支持记录暂不可用")
 suspend fun classifyLearningSupport(base:String,token:String,family:String,child:String,assignment:String,source:String,category:String,privateNote:String,revisitAt:String?,key:String):RemoteResult<List<RemoteSupportEvent>> = RemoteResult.Failure("再练安排暂不可用")
 suspend fun learningSubmit(base:String,token:String,family:String,child:String,assignment:String,expectedVersion:Long,key:String):RemoteResult<RemoteLearningAssignment> = RemoteResult.Failure("课节提交暂不可用")
 suspend fun learningReview(base:String,token:String,family:String,child:String,assignment:String,decision:String,note:String,expectedVersion:Long,key:String):RemoteResult<RemoteLearningAssignment> = RemoteResult.Failure("课程审核暂不可用")
 suspend fun teachingCourses(base:String,token:String,family:String):RemoteResult<List<RemoteCourseSummary>> = RemoteResult.Failure("课程工作台暂不可用")
 suspend fun teachingVersion(base:String,token:String,family:String,version:String):RemoteResult<RemoteTeachingVersion> = RemoteResult.Failure("课程版本暂不可用")
 suspend fun createTeachingCourse(base:String,token:String,family:String,draft:RemoteTeachingCourseDraft,key:String):RemoteResult<RemoteTeachingVersion> = RemoteResult.Failure("建课暂不可用")
 suspend fun publishTeachingVersion(base:String,token:String,family:String,version:String,key:String):RemoteResult<RemoteTeachingVersion> = RemoteResult.Failure("课程发布暂不可用")
 suspend fun withdrawTeachingVersion(base:String,token:String,family:String,version:String,reason:String,key:String):RemoteResult<Unit> = RemoteResult.Failure("课程撤回暂不可用")
 suspend fun assignTeachingLesson(base:String,token:String,family:String,child:String,version:String,lesson:String,key:String):RemoteResult<RemoteLearningAssignment> = RemoteResult.Failure("课程分配暂不可用")
 suspend fun submit(base:String,childToken:String,family:String,child:String,task:String,key:String):RemoteResult<Unit>
 suspend fun review(base:String,parentToken:String,family:String,completion:String,key:String):RemoteResult<Unit>
 suspend fun usage(base:String,childToken:String,family:String,child:String,key:String,occurredAt:Instant):RemoteResult<Unit>
}

class HttpFamilyApiTransport:FamilyApiTransport{
 override suspend fun acceptParentPairing(base:String,code:String,deviceName:String)=request(base,"/api/v1/auth/device-pairings/accept","POST",null,JSONObject().put("code",code).put("deviceName",deviceName)){root->val d=root.getJSONObject("data");val session=d.getJSONObject("session");val actor=session.getJSONObject("actor");val children=d.getJSONArray("children");RemotePairedParent(actor.getString("familyId"),actor.getString("actorId"),session.getString("token"),buildList{for(i in 0 until children.length()){val c=children.getJSONObject(i);add(RemoteFamilyChild(c.getString("id"),c.getString("displayName"),c.getString("birthDate"),c.getString("effectiveStage")))}})}
 override suspend fun familyChildren(base:String,parentToken:String,family:String)=request(base,"/api/v1/families/$family/children","GET",parentToken,null){root->val a=root.getJSONArray("data");buildList{for(i in 0 until a.length()){val c=a.getJSONObject(i);add(RemoteFamilyChild(c.getString("id"),c.getString("displayName"),c.getString("birthDate"),c.getString("effectiveStage")))}}}
 override suspend fun login(base:String,family:String,parent:String,pin:String)=request(base,"/api/v1/auth/login","POST",null,JSONObject().put("familyId",family).put("parentId",parent).put("pin",pin)){it.getJSONObject("data").getString("token")}
 override suspend fun childSession(base:String,parentToken:String,child:String)=request(base,"/api/v1/auth/child-sessions","POST",parentToken,JSONObject().put("childId",child)){it.getJSONObject("data").getString("token")}
 override suspend fun snapshot(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/sync","GET",token,null){root->val d=root.getJSONObject("data");val w=d.getJSONObject("wallet");val a=d.getJSONArray("tasks");RemoteSnapshot(d.getString("familyId"),d.getString("childId"),d.getString("childName"),w.getString("moneyBalance").toBigDecimal(),w.getInt("coinBalance"),buildList{for(i in 0 until a.length()){val t=a.getJSONObject(i);add(RemoteTask(t.getString("id"),t.getString("title"),t.getInt("expectedMinutes"),t.getString("status"),if(t.isNull("latestCompletionId"))null else t.getString("latestCompletionId"))) }},d.getInt("pendingReviews"),d.getInt("approvedToday"))}
 override suspend fun experience(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/experience-profile","GET",token,null){decodeExperience(it.getJSONObject("data"))}
 override suspend fun updateExperience(base:String,token:String,family:String,child:String,birthDate:LocalDate,stageOverride:SchoolStage?,primaryBandOverride:PrimaryGradeBand?,overrideReason:String,hapticsEnabled:Boolean,expectedVersion:Long)=request(base,"/api/v1/families/$family/children/$child/experience-profile","PUT",token,JSONObject().put("birthDate",birthDate.toString()).put("stageOverride",stageOverride?.name ?: JSONObject.NULL).put("primaryBandOverride",primaryBandOverride?.name ?: JSONObject.NULL).put("overrideReason",overrideReason).put("hapticsEnabled",hapticsEnabled).put("expectedVersion",expectedVersion).put("auditReason","家长在 Android 端更新学习阶段和小学分段")){decodeExperience(it.getJSONObject("data"))}
 override suspend fun educationSources(base:String,token:String,family:String)=request(base,"/api/v1/families/$family/education-resource-sources","GET",token,null){root->decodeEducationSources(root.getJSONArray("data"))}
 override suspend fun createEducationSource(base:String,token:String,family:String,title:String,sourceUrl:String,stages:List<SchoolStage>,usageNote:String,key:String)=request(base,"/api/v1/families/$family/education-resource-sources","POST",token,JSONObject().put("title",title).put("sourceUrl",sourceUrl).put("schoolStages",org.json.JSONArray(stages.map{it.name})).put("usageNote",usageNote),key){decodeEducationSource(it.getJSONObject("data"))}
 override suspend fun educationSourceAction(base:String,token:String,family:String,source:String,action:String,key:String)=request(base,"/api/v1/families/$family/education-resource-sources/$source/$action","POST",token,null,key){decodeEducationSource(it.getJSONObject("data"))}
 override suspend fun childEducationCatalog(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/education-resource-catalog","GET",token,null){root->val a=root.getJSONArray("data");buildList{for(i in 0 until a.length()){val d=a.getJSONObject(i);add(RemoteChildEducationSource(d.getString("id"),d.getString("title"),decodeCategories(d.getJSONArray("categories"),false),if(d.isNull("lastRefreshedAt"))null else d.getString("lastRefreshedAt"),d.getBoolean("parentActionRequired")))}}}
 override suspend fun learningAssignments(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/learning/assignments","GET",token,null){root->decodeLearningAssignments(root.getJSONArray("data"))}
 override suspend fun syncAutonomousLearning(base:String,token:String,family:String,child:String,key:String)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/sync","POST",token,null,key){root->decodeLearningAssignments(root.getJSONArray("data"))}
 override suspend fun learningRewardPolicy(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/reward-policy","GET",token,null){root->decodeRewardPolicy(root.getJSONObject("data"))}
 override suspend fun primaryLearningReport(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/primary-report","GET",token,null){root->decodePrimaryReport(root.getJSONObject("data"))}
 override suspend fun juniorLearningPlan(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/junior-learning/plan","GET",token,null){decodeJuniorPlan(it.getJSONObject("data"))}
 override suspend fun juniorLearningReport(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/junior-learning/report","GET",token,null){decodeJuniorReport(it.getJSONObject("data"))}
 override suspend fun moveJuniorLearning(base:String,token:String,family:String,child:String,assignment:String,direction:String,revision:Long,key:String)=request(base,"/api/v1/families/$family/children/$child/junior-learning/plan/move","POST",token,JSONObject().put("assignmentId",assignment).put("direction",direction).put("expectedRevision",revision),key){decodeJuniorPlan(it.getJSONObject("data"))}
 override suspend fun seniorModules(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/modules","GET",token,null){decodeSeniorModules(it.getJSONObject("data"))}
 override suspend fun updateSeniorModules(base:String,token:String,family:String,child:String,selections:List<RemoteSeniorModule>,revision:Long,key:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/modules","PUT",token,JSONObject().put("selections",org.json.JSONArray(selections.map{JSONObject().put("subjectCode",it.subjectCode).put("moduleType",it.moduleType)})).put("expectedRevision",revision).put("reason","家长在 Android 端按当前真实课程组合配置"),key){decodeSeniorModules(it.getJSONObject("data"))}
 override suspend fun seniorGoals(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/goals","GET",token,null){decodeSeniorGoals(it.getJSONArray("data"))}
 override suspend fun createSeniorGoal(base:String,token:String,family:String,child:String,module:RemoteSeniorModule,assignment:String?,weekStart:String,title:String,evidence:String,next:String,key:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/goals","POST",token,JSONObject().put("assignmentId",assignment?:JSONObject.NULL).put("module",JSONObject().put("subjectCode",module.subjectCode).put("moduleType",module.moduleType)).put("weekStart",weekStart).put("title",title).put("evidenceTarget",evidence).put("nextAction",next),key){decodeSeniorGoal(it.getJSONObject("data"))}
 override suspend fun updateSeniorGoal(base:String,token:String,family:String,child:String,goal:String,title:String,evidence:String,next:String,revision:Long,key:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/goals/$goal","PUT",token,JSONObject().put("title",title).put("evidenceTarget",evidence).put("nextAction",next).put("expectedRevision",revision),key){decodeSeniorGoal(it.getJSONObject("data"))}
 override suspend fun archiveSeniorGoal(base:String,token:String,family:String,child:String,goal:String,revision:Long,key:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/goals/$goal/archive","POST",token,JSONObject().put("expectedRevision",revision),key){decodeSeniorGoal(it.getJSONObject("data"))}
 override suspend fun seniorReflections(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/reflections","GET",token,null){decodeSeniorReflections(it.getJSONArray("data"))}
 override suspend fun createSeniorReflection(base:String,token:String,family:String,child:String,goal:String?,assignment:String?,evidence:String,strategy:String,next:String,support:Boolean,key:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/reflections","POST",token,JSONObject().put("goalId",goal?:JSONObject.NULL).put("assignmentId",assignment?:JSONObject.NULL).put("evidenceSummary",evidence).put("strategy",strategy).put("nextAction",next).put("supportRequested",support),key){decodeSeniorReflection(it.getJSONObject("data"))}
 override suspend fun seniorReport(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/senior-learning/report","GET",token,null){decodeSeniorReport(it.getJSONObject("data"))}
 override suspend fun configureUsage(base:String,token:String,family:String,child:String,daily:Int,session:Int,quietStart:String,quietEnd:String)=request(base,"/api/v1/families/$family/children/$child/usage-policy","PUT",token,JSONObject().put("zoneId","Asia/Shanghai").put("dailyLimitMinutes",daily).put("sessionLimitMinutes",session).put("quietStart",quietStart).put("quietEnd",quietEnd)){val d=it.getJSONObject("data");RemoteUsagePolicy(d.getString("zoneId"),d.getInt("dailyLimitMinutes"),d.getInt("sessionLimitMinutes"),d.getString("quietStart"),d.getString("quietEnd"),d.getLong("version"))}
 override suspend fun usageAccess(base:String,token:String,family:String,child:String)=request(base,"/api/v1/families/$family/children/$child/usage-access","GET",token,null){val d=it.getJSONObject("data");RemoteUsageAccess(d.getBoolean("allowed"),d.getString("reasonCode"),d.getString("message"),d.getInt("usedTodayMinutes"),d.getInt("dailyLimitMinutes"),d.nullableString("allowanceExpiresAt"),d.optInt("sessionUsedMinutes"),d.optInt("sessionLimitMinutes"),d.optInt("restMinutes"),d.nullableString("restUntil"))}
 override suspend fun createUsageAllowance(base:String,token:String,family:String,child:String,minutes:Int,reason:String,key:String)=request(base,"/api/v1/families/$family/children/$child/usage-allowances","POST",token,JSONObject().put("minutes",minutes).put("reason",reason),key){Unit}
 override suspend fun exportChildData(base:String,token:String,family:String,child:String,key:String)=request(base,"/api/v1/families/$family/children/$child/data-rights/exports","POST",token,JSONObject(),key){val d=it.getJSONObject("data");RemoteChildDataExport(d.getString("generatedAt"),d.toString(2))}
 override suspend fun erasurePreview(base:String,token:String,family:String,child:String,key:String)=request(base,"/api/v1/families/$family/children/$child/data-rights/erasure-preview","POST",token,JSONObject(),key){val d=it.getJSONObject("data");RemoteErasurePreview(d.getString("requestId"),d.getString("confirmationToken"),d.getString("confirmationExpiresAt"),d.strings("deletedOrRedacted"),d.strings("retained"))}
 override suspend fun confirmErasure(base:String,token:String,family:String,child:String,requestId:String,confirmation:String,pin:String)=request(base,"/api/v1/families/$family/children/$child/data-rights/erasures/$requestId/confirm","POST",token,JSONObject().put("confirmationToken",confirmation).put("pin",pin)){val d=it.getJSONObject("data");RemoteErasureResult(d.getString("requestId"),d.getString("status"),d.getString("completedAt"))}
 override suspend fun stageTransitionPreview(base:String,token:String,family:String,child:String,birthDate:String,override:String?):RemoteResult<RemoteStageTransitionPreview>{val query="?birthDate="+java.net.URLEncoder.encode(birthDate,"UTF-8")+(override?.let{"&stageOverride="+java.net.URLEncoder.encode(it,"UTF-8")}.orEmpty());return request(base,"/api/v1/families/$family/children/$child/experience-profile/transition-preview$query","GET",token,null){val d=it.getJSONObject("data");RemoteStageTransitionPreview(d.getString("oldStage"),d.getString("newStage"),d.getInt("willArchiveUnstartedAutonomous"),d.getInt("willRestorePreviouslyArchived"),d.getString("message"))}}
 override suspend fun updateLearningRewardPolicy(base:String,token:String,family:String,child:String,money:String,coin:Long,xp:Long,expectedVersion:Long)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/reward-policy","PUT",token,JSONObject().put("moneyReward",money).put("coinReward",coin).put("xpReward",xp).put("expectedVersion",expectedVersion).put("auditReason","家长在 Android 端设置固定自主学习奖励")){root->decodeRewardPolicy(root.getJSONObject("data"))}
 override suspend fun learningAttempt(base:String,token:String,family:String,child:String,assignment:String,activity:String,response:String,playedSeconds:Int?,durationSeconds:Int?,key:String)=request(base,"/api/v1/families/$family/children/$child/learning/assignments/$assignment/activities/$activity/attempts","POST",token,JSONObject().put("responseText",response).put("playedSeconds",playedSeconds?:JSONObject.NULL).put("durationSeconds",durationSeconds?:JSONObject.NULL),key){decodeLearningAssignment(it.getJSONObject("data"))}
 override suspend fun learningHelp(base:String,token:String,family:String,child:String,assignment:String,activity:String,message:String,key:String)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/assignments/$assignment/activities/$activity/help","POST",token,JSONObject().put("message",message),key){decodeLearningAssignment(it.getJSONObject("data"))}
 override suspend fun learningSupportEvents(base:String,token:String,family:String,child:String,assignment:String)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/assignments/$assignment/support-events","GET",token,null){decodeSupportEvents(it.getJSONArray("data"))}
 override suspend fun classifyLearningSupport(base:String,token:String,family:String,child:String,assignment:String,source:String,category:String,privateNote:String,revisitAt:String?,key:String)=request(base,"/api/v1/families/$family/children/$child/autonomous-learning/assignments/$assignment/support-events/classify","POST",token,JSONObject().put("sourceEventId",source).put("category",category).put("privateNote",privateNote).put("revisitAt",revisitAt?:JSONObject.NULL),key){decodeSupportEvents(it.getJSONArray("data"))}
 override suspend fun learningSubmit(base:String,token:String,family:String,child:String,assignment:String,expectedVersion:Long,key:String)=request(base,"/api/v1/families/$family/children/$child/learning/assignments/$assignment/submit","POST",token,JSONObject().put("expectedVersion",expectedVersion),key){decodeLearningAssignment(it.getJSONObject("data"))}
 override suspend fun learningReview(base:String,token:String,family:String,child:String,assignment:String,decision:String,note:String,expectedVersion:Long,key:String)=request(base,"/api/v1/families/$family/children/$child/learning/assignments/$assignment/review","POST",token,JSONObject().put("decision",decision).put("note",note).put("expectedVersion",expectedVersion),key){decodeLearningAssignment(it.getJSONObject("data"))}
 override suspend fun teachingCourses(base:String,token:String,family:String)=request(base,"/api/v1/families/$family/teaching/courses","GET",token,null){root->decodeCourseSummaries(root.getJSONArray("data"))}
 override suspend fun teachingVersion(base:String,token:String,family:String,version:String)=request(base,"/api/v1/families/$family/teaching/course-versions/$version","GET",token,null){decodeTeachingVersion(it.getJSONObject("data"))}
 override suspend fun createTeachingCourse(base:String,token:String,family:String,draft:RemoteTeachingCourseDraft,key:String):RemoteResult<RemoteTeachingVersion>{
  val activity=JSONObject().put("type",draft.activityType).put("title",draft.activityTitle).put("instruction",draft.instruction).put("expectedMinutes",draft.expectedMinutes)
  if(draft.contentRef!=null)activity.put("contentRef",draft.contentRef)
  val lesson=JSONObject().put("title",draft.lessonTitle).put("summary",draft.lessonSummary).put("activities",org.json.JSONArray().put(activity))
  draft.chapterTitle?.let { lesson.put("chapterTitle",it) }
  if(draft.knowledgePoints.isNotEmpty()) lesson.put("knowledgePoints",org.json.JSONArray(draft.knowledgePoints))
  draft.learningGoal?.let { lesson.put("learningGoal",it) }
  draft.safetyNote?.let { lesson.put("safetyNote",it) }
  draft.seniorModuleType?.let { lesson.put("moduleType",it) }
  draft.topicTitle?.let { lesson.put("topicTitle",it) }
  draft.inquiryQuestion?.let { lesson.put("inquiryQuestion",it) }
  draft.expectedEvidence?.let { lesson.put("expectedEvidence",it) }
  draft.seniorSafetyNote?.let { lesson.put("seniorSafetyNote",it) }
  val unit=JSONObject().put("title","家庭学习夹").put("lessons",org.json.JSONArray().put(lesson))
  val version=JSONObject().put("summary",draft.lessonSummary).put("rightsBasis",draft.rightsBasis).put("units",org.json.JSONArray().put(unit))
  draft.kindergartenAgeBand?.let { version.put("kindergartenAgeBand",it) }
  if(draft.kindergartenDomains.isNotEmpty()) version.put("kindergartenDomains",org.json.JSONArray(draft.kindergartenDomains))
  val body=JSONObject().put("schoolStage",draft.stage).put("subjectCode",draft.subject).put("title",draft.courseTitle).put("version",version)
  return request(base,"/api/v1/families/$family/teaching/courses","POST",token,body,key){decodeTeachingVersion(it.getJSONObject("data"))}
 }
 override suspend fun publishTeachingVersion(base:String,token:String,family:String,version:String,key:String)=request(base,"/api/v1/families/$family/teaching/course-versions/$version/publish","POST",token,null,key){decodeTeachingVersion(it.getJSONObject("data"))}
 override suspend fun withdrawTeachingVersion(base:String,token:String,family:String,version:String,reason:String,key:String)=request(base,"/api/v1/families/$family/teaching/course-versions/$version/withdraw","POST",token,JSONObject().put("reason",reason),key){Unit}
 override suspend fun assignTeachingLesson(base:String,token:String,family:String,child:String,version:String,lesson:String,key:String)=request(base,"/api/v1/families/$family/children/$child/learning/assignments","POST",token,JSONObject().put("courseVersionId",version).put("lessonId",lesson),key){decodeLearningAssignment(it.getJSONObject("data"))}
 override suspend fun submit(base:String,childToken:String,family:String,child:String,task:String,key:String)=request(base,"/api/v1/families/$family/children/$child/tasks/$task/completions","POST",childToken,JSONObject().put("evidenceNote","在孩子端确认完成"),key){Unit}
 override suspend fun review(base:String,parentToken:String,family:String,completion:String,key:String)=request(base,"/api/v1/families/$family/completions/$completion/review","POST",parentToken,JSONObject().put("approved",true).put("xpReward",10).put("coinReward",10).put("moneyReward",0).put("reviewNote","家长端确认"),key){Unit}
 override suspend fun usage(base:String,childToken:String,family:String,child:String,key:String,occurredAt:Instant)=request(base,"/api/v1/families/$family/children/$child/usage-events","POST",childToken,JSONObject().put("type","APP_ACTIVE").put("minutes",1).put("occurredAt",occurredAt.toString()),key){Unit}
 private suspend fun <T> request(base:String,path:String,method:String,token:String?,body:JSONObject?,key:String?=null,decode:(JSONObject)->T):RemoteResult<T> = withContext(Dispatchers.IO){
  try{val connection=(URL(base+path).openConnection() as HttpURLConnection).apply{requestMethod=method;connectTimeout=8_000;readTimeout=10_000;setRequestProperty("Accept","application/json");if(token!=null)setRequestProperty("Authorization","Bearer $token");if(key!=null)setRequestProperty("Idempotency-Key",key);if(body!=null){doOutput=true;setRequestProperty("Content-Type","application/json");outputStream.use{it.write(body.toString().toByteArray(Charsets.UTF_8))}}};val code=connection.responseCode;if(code==401){connection.disconnect();return@withContext RemoteResult.Unauthorized};val stream=if(code in 200..299)connection.inputStream else connection.errorStream;val text=stream?.bufferedReader()?.use{it.readText()}.orEmpty();connection.disconnect();if(code !in 200..299)return@withContext remoteFailureForStatus(code);RemoteResult.Ok(decode(JSONObject(text)))}catch(_:IOException){RemoteResult.Failure("无法连接家庭服务，记录已安全保留",RemoteFailureKind.RETRYABLE)}catch(_:Exception){RemoteResult.Failure("家庭服务返回了无法识别的数据")}
 }
 private fun decodeExperience(d:JSONObject)=RemoteExperienceProfile(d.getString("birthDate"),d.getString("recommendedStage"),if(d.isNull("stageOverride"))null else d.getString("stageOverride"),d.getString("effectiveStage"),d.nullableString("recommendedPrimaryBand"),d.nullableString("primaryBandOverride"),d.nullableString("effectivePrimaryBand"),d.optString("overrideReason"),d.getBoolean("hapticsEnabled"),d.getLong("version"))
 private fun decodeEducationSources(a:org.json.JSONArray)=buildList{for(i in 0 until a.length())add(decodeEducationSource(a.getJSONObject(i)))}
 private fun decodeEducationSource(d:JSONObject):RemoteEducationSource{val stages=d.getJSONArray("schoolStages");return RemoteEducationSource(d.getString("id"),d.getString("title"),d.getString("sourceUrl"),buildList{for(i in 0 until stages.length())add(stages.getString(i))},d.getString("usageNote"),d.getString("status"),d.getString("refreshStatus"),d.optString("refreshError"),if(d.isNull("lastRefreshedAt"))null else d.getString("lastRefreshedAt"),decodeCategories(d.getJSONArray("categories"),true))}
 private fun decodeCategories(a:org.json.JSONArray,parent:Boolean)=buildList{for(i in 0 until a.length()){val d=a.getJSONObject(i);add(RemoteResourceCategory(d.getString("id"),d.getString("title"),d.getInt("displayOrder"),if(parent&&!d.isNull("categoryUrl"))d.getString("categoryUrl") else null))}}
 private fun decodeLearningAssignments(a:org.json.JSONArray)=buildList{for(i in 0 until a.length())add(decodeLearningAssignment(a.getJSONObject(i)))}
 private fun decodeLearningAssignment(d:JSONObject):RemoteLearningAssignment{val activities=d.getJSONArray("activities");val reward=d.optJSONObject("reward");val jm=d.optJSONObject("juniorMetadata");val sm=d.optJSONObject("seniorMetadata");return RemoteLearningAssignment(d.getString("id"),d.getString("courseTitle"),d.getString("unitTitle"),d.getString("lessonTitle"),d.getString("lessonSummary"),d.getString("schoolStage"),d.getString("subjectCode"),d.getString("status"),d.getLong("version"),buildList{for(i in 0 until activities.length()){val a=activities.getJSONObject(i);val options=a.getJSONArray("options");val evidence=a.getJSONArray("evidence");add(RemoteLearningActivity(a.getString("id"),a.getString("type"),a.getString("title"),a.getString("instruction"),a.optString("contentRef"),a.getInt("expectedMinutes"),a.optString("prompt"),a.optString("hint"),buildList{for(j in 0 until options.length()){val o=options.getJSONObject(j);add(RemoteQuestionOption(o.getString("value"),o.getString("label")))}},a.getString("requiredEvidence"),buildSet{for(j in 0 until evidence.length())add(evidence.getString(j))},if(a.isNull("checkedCorrect"))null else a.getBoolean("checkedCorrect"))) }},d.optString("reviewNote"),d.optString("assignmentSource","PARENT"),if(reward==null)RemoteRewardSnapshot()else RemoteRewardSnapshot(reward.getString("money"),reward.getLong("coin"),reward.getLong("xp"),reward.nullableString("settledAt")),if(jm==null)null else RemoteJuniorMetadata(jm.getString("chapterTitle"),buildList{val k=jm.getJSONArray("knowledgePoints");for(i in 0 until k.length())add(k.getString(i))},jm.getString("learningGoal"),jm.getString("safetyNote")),if(sm==null)null else RemoteSeniorMetadata(sm.getString("moduleType"),sm.getString("topicTitle"),sm.getString("inquiryQuestion"),sm.getString("expectedEvidence"),sm.getString("safetyNote")))}
 private fun decodeRewardPolicy(d:JSONObject)=RemoteRewardPolicy(d.getString("moneyReward"),d.getLong("coinReward"),d.getLong("xpReward"),d.getLong("version"))
 private fun decodePrimaryReport(d:JSONObject):RemotePrimaryLearningReport{val a=d.getJSONArray("subjects");return RemotePrimaryLearningReport(d.getString("effectiveStage"),d.nullableString("effectivePrimaryBand"),d.getLong("recordedLearningMinutes"),buildList{for(i in 0 until a.length()){val s=a.getJSONObject(i);add(RemoteSubjectLearningFacts(s.getString("subjectCode"),s.getLong("assigned"),s.getLong("inProgress"),s.getLong("submitted"),s.getLong("completed"),s.getLong("reworkRequired"),s.getLong("openSupport"),s.getLong("scheduledRevisits"),s.getLong("dueRevisits")))}})}
 private fun decodeJuniorPlan(d:JSONObject):RemoteJuniorPlan{val a=d.getJSONArray("items");return RemoteJuniorPlan(d.getLong("revision"),buildList{for(i in 0 until a.length()){val v=a.getJSONObject(i);add(RemoteJuniorPlanItem(v.getString("assignmentId"),v.getString("subjectCode"),v.getString("courseTitle"),v.getString("lessonTitle"),v.getString("status"),v.getInt("position")))}})}
 private fun decodeJuniorReport(d:JSONObject):RemoteJuniorLearningReport{val a=d.getJSONArray("subjects");return RemoteJuniorLearningReport(d.getLong("recordedLearningMinutes"),buildList{for(i in 0 until a.length()){val s=a.getJSONObject(i);add(RemoteSubjectLearningFacts(s.getString("subjectCode"),s.getLong("assigned"),s.getLong("inProgress"),s.getLong("submitted"),s.getLong("completed"),s.getLong("reworkRequired"),s.getLong("openSupport"),s.getLong("scheduledRevisits"),s.getLong("dueRevisits")))}},d.getLong("planRevision"))}
 private fun decodeSeniorModules(d:JSONObject):RemoteSeniorModuleConfiguration{val a=d.getJSONArray("selections");return RemoteSeniorModuleConfiguration(d.getLong("revision"),buildList{for(i in 0 until a.length()){val v=a.getJSONObject(i);add(RemoteSeniorModule(v.getString("subjectCode"),v.getString("moduleType")))}})}
 private fun decodeSeniorGoal(d:JSONObject):RemoteSeniorGoal{val m=d.getJSONObject("module");return RemoteSeniorGoal(d.getString("id"),d.nullableString("assignmentId"),RemoteSeniorModule(m.getString("subjectCode"),m.getString("moduleType")),d.getString("weekStart"),d.getString("title"),d.getString("evidenceTarget"),d.getString("nextAction"),d.getString("status"),d.getLong("revision"))}
 private fun decodeSeniorGoals(a:org.json.JSONArray)=buildList{for(i in 0 until a.length())add(decodeSeniorGoal(a.getJSONObject(i)))}
 private fun decodeSeniorReflection(d:JSONObject)=RemoteSeniorReflection(d.getString("id"),d.nullableString("goalId"),d.nullableString("assignmentId"),d.getString("evidenceSummary"),d.getString("strategy"),d.getString("nextAction"),d.getBoolean("supportRequested"),d.getString("createdAt"))
 private fun decodeSeniorReflections(a:org.json.JSONArray)=buildList{for(i in 0 until a.length())add(decodeSeniorReflection(a.getJSONObject(i)))}
 private fun decodeSeniorReport(d:JSONObject):RemoteSeniorLearningReport{val a=d.getJSONArray("subjects");return RemoteSeniorLearningReport(d.getLong("recordedLearningMinutes"),buildList{for(i in 0 until a.length()){val s=a.getJSONObject(i);add(RemoteSubjectLearningFacts(s.getString("subjectCode"),s.getLong("assigned"),s.getLong("inProgress"),s.getLong("submitted"),s.getLong("completed"),s.getLong("reworkRequired"),s.getLong("openSupport"),s.getLong("scheduledRevisits"),s.getLong("dueRevisits")))}},d.getLong("activeGoals"),d.getLong("archivedGoals"),d.getLong("reflections"),d.getLong("supportRequests"))}
 private fun decodeSupportEvents(a:org.json.JSONArray)=buildList{for(i in 0 until a.length()){val d=a.getJSONObject(i);add(RemoteSupportEvent(d.getString("id"),d.getString("assignmentId"),d.nullableString("activityId"),d.getString("type"),d.nullableString("category"),d.optString("childMessage"),d.optString("privateNote"),d.nullableString("revisitAt"),d.nullableString("parentEventId"),d.getString("createdAt")))}}
 private fun decodeCourseSummaries(a:org.json.JSONArray)=buildList{for(i in 0 until a.length()){val d=a.getJSONObject(i);add(RemoteCourseSummary(d.getString("courseId"),d.getString("title"),d.getString("schoolStage"),d.getString("subjectCode"),d.getString("versionId"),d.getInt("versionNumber"),d.getString("status"),d.getInt("lessonCount")))}}
 private fun decodeTeachingVersion(d:JSONObject):RemoteTeachingVersion{val lessons=buildList{val units=d.getJSONArray("units");for(i in 0 until units.length()){val ls=units.getJSONObject(i).getJSONArray("lessons");for(j in 0 until ls.length())add(ls.getJSONObject(j).getString("id"))}};return RemoteTeachingVersion(d.getString("courseId"),d.getString("versionId"),d.getString("title"),d.getString("schoolStage"),d.getString("subjectCode"),d.getInt("versionNumber"),d.getString("status"),lessons)}
}

internal fun remoteFailureForStatus(code:Int):RemoteResult.Failure = when(code){
 409->RemoteResult.Failure("数据已变化，请刷新后重试",RemoteFailureKind.CONFLICT)
  408,425,429->RemoteResult.Failure("家庭服务暂时忙碌（$code）",RemoteFailureKind.RETRYABLE)
 in 500..599->RemoteResult.Failure("家庭服务暂时不可用（$code）",RemoteFailureKind.RETRYABLE)
 403->RemoteResult.Failure("当前角色无权执行")
 else->RemoteResult.Failure("服务请求失败（$code）")
}

class RemoteFamilyRepository(private val transport:FamilyApiTransport,private val sessions:MemorySessionStore,private val allowPrivateHttp:Boolean){
 suspend fun pairParent(rawBase:String,code:String,deviceName:String):RemoteResult<RemoteSnapshot>{val base=ServiceUrlPolicy.normalize(rawBase,allowPrivateHttp).getOrElse{return RemoteResult.Failure(it.message?:"服务地址无效")};if(code.filter(Char::isLetterOrDigit).length<10||deviceName.isBlank())return RemoteResult.Failure("请输入有效配对码和设备名称");val paired=when(val r=transport.acceptParentPairing(base,code,deviceName.trim())){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return RemoteResult.Unauthorized;is RemoteResult.Failure->return r};val child=paired.children.firstOrNull()?:return RemoteResult.Failure("家庭中还没有可使用的孩子档案");val childToken=when(val r=transport.childSession(base,paired.token,child.id)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return RemoteResult.Unauthorized;is RemoteResult.Failure->return r};sessions.set(RemoteSession(base,paired.familyId,paired.parentId,child.id,paired.token,childToken));return refresh()}
 suspend fun children():RemoteResult<List<RemoteFamilyChild>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.familyChildren(s.baseUrl,s.parentToken,s.familyId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun switchChild(childId:String):RemoteResult<RemoteSnapshot>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");runCatching{UUID.fromString(childId)}.getOrElse{return RemoteResult.Failure("孩子 ID 无效")};val allowed=when(val r=transport.familyChildren(s.baseUrl,s.parentToken,s.familyId)){is RemoteResult.Ok->r.value.any{it.id==childId};RemoteResult.Unauthorized->return expired();is RemoteResult.Failure->return r};if(!allowed)return RemoteResult.Failure("该孩子不属于当前家庭");val childToken=when(val r=transport.childSession(s.baseUrl,s.parentToken,childId)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return expired();is RemoteResult.Failure->return r};sessions.set(s.copy(childId=childId,childToken=childToken));return refresh()}
 suspend fun connect(rawBase:String,family:String,parent:String,child:String,pin:String):RemoteResult<RemoteSnapshot>{val base=ServiceUrlPolicy.normalize(rawBase,allowPrivateHttp).getOrElse{return RemoteResult.Failure(it.message?:"服务地址无效")};runCatching{validateConnectionIds(family,parent,child)}.getOrElse{return RemoteResult.Failure("家庭、家长或孩子 ID 格式无效")};val parentToken=when(val r=transport.login(base,family,parent,pin)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return RemoteResult.Unauthorized;is RemoteResult.Failure->return r};val childToken=when(val r=transport.childSession(base,parentToken,child)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return expired();is RemoteResult.Failure->return r};val session=RemoteSession(base,family,parent,child,parentToken,childToken);sessions.set(session);return refresh()}
 suspend fun refresh():RemoteResult<RemoteSnapshot>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");val snapshot=when(val r=transport.snapshot(s.baseUrl,s.parentToken,s.familyId,s.childId)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return expired();is RemoteResult.Failure->return r};return when(val p=transport.experience(s.baseUrl,s.parentToken,s.familyId,s.childId)){is RemoteResult.Ok->RemoteResult.Ok(snapshot.copy(experience=p.value));RemoteResult.Unauthorized->expired();is RemoteResult.Failure->p}}
 suspend fun updateExperience(birthDate:LocalDate,stageOverride:SchoolStage?,primaryBandOverride:PrimaryGradeBand?,overrideReason:String,hapticsEnabled:Boolean,expectedVersion:Long):RemoteResult<RemoteSnapshot>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.updateExperience(s.baseUrl,s.parentToken,s.familyId,s.childId,birthDate,stageOverride,primaryBandOverride,overrideReason,hapticsEnabled,expectedVersion)){is RemoteResult.Ok->refresh();RemoteResult.Unauthorized->expired();is RemoteResult.Failure->r}}
 suspend fun educationSources():RemoteResult<List<RemoteEducationSource>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.educationSources(s.baseUrl,s.parentToken,s.familyId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun childEducationCatalog():RemoteResult<List<RemoteChildEducationSource>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.childEducationCatalog(s.baseUrl,s.childToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun learningAssignments():RemoteResult<List<RemoteLearningAssignment>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.syncAutonomousLearning(s.baseUrl,s.childToken,s.familyId,s.childId,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun updateLearningReward(money:String,coin:Long,xp:Long):RemoteResult<RemoteRewardPolicy>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");val current=when(val r=transport.learningRewardPolicy(s.baseUrl,s.parentToken,s.familyId,s.childId)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return expired();is RemoteResult.Failure->return r};return when(val r=transport.updateLearningRewardPolicy(s.baseUrl,s.parentToken,s.familyId,s.childId,money,coin,xp,current.version)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun primaryLearningReport():RemoteResult<RemotePrimaryLearningReport>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.primaryLearningReport(s.baseUrl,s.parentToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun juniorLearningPlan():RemoteResult<RemoteJuniorPlan>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.juniorLearningPlan(s.baseUrl,s.childToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun juniorLearningReport():RemoteResult<RemoteJuniorLearningReport>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.juniorLearningReport(s.baseUrl,s.parentToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun moveJuniorLearning(assignment:String,direction:String,revision:Long):RemoteResult<RemoteJuniorPlan>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.moveJuniorLearning(s.baseUrl,s.childToken,s.familyId,s.childId,assignment,direction,revision,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun seniorModules():RemoteResult<RemoteSeniorModuleConfiguration>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.seniorModules(s.baseUrl,s.parentToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun updateSeniorModules(values:List<RemoteSeniorModule>,revision:Long):RemoteResult<RemoteSeniorModuleConfiguration>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.updateSeniorModules(s.baseUrl,s.parentToken,s.familyId,s.childId,values,revision,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun seniorGoals():RemoteResult<List<RemoteSeniorGoal>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.seniorGoals(s.baseUrl,s.childToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun createSeniorGoal(module:RemoteSeniorModule,assignment:String?,week:String,title:String,evidence:String,next:String):RemoteResult<RemoteSeniorGoal>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.createSeniorGoal(s.baseUrl,s.childToken,s.familyId,s.childId,module,assignment,week,title,evidence,next,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun updateSeniorGoal(goal:RemoteSeniorGoal,title:String,evidence:String,next:String):RemoteResult<RemoteSeniorGoal>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.updateSeniorGoal(s.baseUrl,s.childToken,s.familyId,s.childId,goal.id,title,evidence,next,goal.revision,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun archiveSeniorGoal(goal:RemoteSeniorGoal):RemoteResult<RemoteSeniorGoal>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.archiveSeniorGoal(s.baseUrl,s.childToken,s.familyId,s.childId,goal.id,goal.revision,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun seniorReflections():RemoteResult<List<RemoteSeniorReflection>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.seniorReflections(s.baseUrl,s.childToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun createSeniorReflection(goal:String?,assignment:String?,evidence:String,strategy:String,next:String,support:Boolean):RemoteResult<RemoteSeniorReflection>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.createSeniorReflection(s.baseUrl,s.childToken,s.familyId,s.childId,goal,assignment,evidence,strategy,next,support,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun seniorReport():RemoteResult<RemoteSeniorLearningReport>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.seniorReport(s.baseUrl,s.parentToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun configureUsage(daily:Int,session:Int,quietStart:String,quietEnd:String):RemoteResult<RemoteUsagePolicy>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.configureUsage(s.baseUrl,s.parentToken,s.familyId,s.childId,daily,session,quietStart,quietEnd)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun usageAccess():RemoteResult<RemoteUsageAccess>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.usageAccess(s.baseUrl,s.childToken,s.familyId,s.childId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun createUsageAllowance(minutes:Int,reason:String):RemoteResult<Unit>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.createUsageAllowance(s.baseUrl,s.parentToken,s.familyId,s.childId,minutes,reason,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun exportChildData():RemoteResult<RemoteChildDataExport>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.exportChildData(s.baseUrl,s.parentToken,s.familyId,s.childId,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun erasurePreview():RemoteResult<RemoteErasurePreview>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.erasurePreview(s.baseUrl,s.parentToken,s.familyId,s.childId,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun confirmErasure(preview:RemoteErasurePreview,pin:String):RemoteResult<RemoteErasureResult>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.confirmErasure(s.baseUrl,s.parentToken,s.familyId,s.childId,preview.requestId,preview.confirmationToken,pin)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun stageTransitionPreview(birthDate:String,override:String?):RemoteResult<RemoteStageTransitionPreview>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.stageTransitionPreview(s.baseUrl,s.parentToken,s.familyId,s.childId,birthDate,override)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun learningSupportEvents(assignment:String):RemoteResult<List<RemoteSupportEvent>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.learningSupportEvents(s.baseUrl,s.parentToken,s.familyId,s.childId,assignment)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun scheduleLearningRevisit(assignment:String,source:String,category:String,note:String,revisitAt:String):RemoteResult<List<RemoteSupportEvent>>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.classifyLearningSupport(s.baseUrl,s.parentToken,s.familyId,s.childId,assignment,source,category,note,revisitAt,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun executeLearning(action:PendingLearningAction):RemoteResult<RemoteLearningAssignment>{val s=sessions.get()?:return RemoteResult.Failure("请家长重新连接后同步",RemoteFailureKind.RETRYABLE);if(s.familyId!=action.familyId||s.childId!=action.childId)return RemoteResult.Failure("待同步记录属于另一个家庭或孩子");val result=when(action.type){LearningActionType.ATTEMPT->transport.learningAttempt(s.baseUrl,s.childToken,s.familyId,s.childId,action.assignmentId,action.activityId,action.responseText,action.playedSeconds,action.durationSeconds,action.idempotencyKey);LearningActionType.HELP->transport.learningHelp(s.baseUrl,s.childToken,s.familyId,s.childId,action.assignmentId,action.activityId,action.note,action.idempotencyKey);LearningActionType.SUBMIT->transport.learningSubmit(s.baseUrl,s.childToken,s.familyId,s.childId,action.assignmentId,action.expectedVersion?:return RemoteResult.Failure("待提交版本缺失"),action.idempotencyKey);LearningActionType.REVIEW->transport.learningReview(s.baseUrl,s.parentToken,s.familyId,s.childId,action.assignmentId,action.decision,action.note,action.expectedVersion?:return RemoteResult.Failure("待审核版本缺失"),action.idempotencyKey)};return when(result){RemoteResult.Unauthorized->expired();else->result}}
 suspend fun teachingCourses():RemoteResult<List<RemoteCourseSummary>>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");return when(val r=transport.teachingCourses(s.baseUrl,s.parentToken,s.familyId)){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun createTeachingCourse(draft:RemoteTeachingCourseDraft):RemoteResult<RemoteTeachingVersion>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");return when(val r=transport.createTeachingCourse(s.baseUrl,s.parentToken,s.familyId,draft,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun publishTeachingVersion(version:String):RemoteResult<RemoteTeachingVersion>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");return when(val r=transport.publishTeachingVersion(s.baseUrl,s.parentToken,s.familyId,version,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun withdrawTeachingVersion(version:String):RemoteResult<Unit>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");return when(val r=transport.withdrawTeachingVersion(s.baseUrl,s.parentToken,s.familyId,version,"家长撤回该版，停止后续自动加入；历史学习记录保留",UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun assignTeachingVersion(version:String):RemoteResult<RemoteLearningAssignment>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");val detail=when(val r=transport.teachingVersion(s.baseUrl,s.parentToken,s.familyId,version)){is RemoteResult.Ok->r.value;RemoteResult.Unauthorized->return expired();is RemoteResult.Failure->return r};val lesson=detail.lessonIds.firstOrNull()?:return RemoteResult.Failure("课程版本没有可分配课节");return when(val r=transport.assignTeachingLesson(s.baseUrl,s.parentToken,s.familyId,s.childId,version,lesson,UUID.randomUUID().toString())){RemoteResult.Unauthorized->expired();else->r}}
 suspend fun createEducationSource(title:String,url:String,stages:List<SchoolStage>,note:String):RemoteResult<List<RemoteEducationSource>>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");return when(val r=transport.createEducationSource(s.baseUrl,s.parentToken,s.familyId,title,url,stages,note,UUID.randomUUID().toString())){is RemoteResult.Ok->educationSources();RemoteResult.Unauthorized->expired();is RemoteResult.Failure->r}}
 suspend fun educationSourceAction(source:String,action:String):RemoteResult<List<RemoteEducationSource>>{val s=sessions.get()?:return RemoteResult.Failure("请先连接家庭服务");return when(val r=transport.educationSourceAction(s.baseUrl,s.parentToken,s.familyId,source,action,UUID.randomUUID().toString())){is RemoteResult.Ok->educationSources();RemoteResult.Unauthorized->expired();is RemoteResult.Failure->r}}
 suspend fun submitTask(taskId:String):RemoteResult<RemoteSnapshot>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.submit(s.baseUrl,s.childToken,s.familyId,s.childId,taskId,UUID.randomUUID().toString())){is RemoteResult.Ok->refresh();RemoteResult.Unauthorized->expired();is RemoteResult.Failure->r}}
 suspend fun approveTask(completionId:String):RemoteResult<RemoteSnapshot>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.review(s.baseUrl,s.parentToken,s.familyId,completionId,UUID.randomUUID().toString())){is RemoteResult.Ok->refresh();RemoteResult.Unauthorized->expired();is RemoteResult.Failure->r}}
 suspend fun recordUsage(key:String,occurredAt:Instant):RemoteResult<Unit>{val s=sessions.get()?:return RemoteResult.Failure("尚未连接家庭服务");return when(val r=transport.usage(s.baseUrl,s.childToken,s.familyId,s.childId,key,occurredAt)){RemoteResult.Unauthorized->expired();else->r}}
 fun learningScope():Pair<String,String>?=sessions.get()?.let{it.familyId to it.childId}
 fun currentParentId():String?=sessions.get()?.parentId
 fun disconnect(){sessions.clear()} fun hasSession()=sessions.get()!=null
 private fun <T> expired():RemoteResult<T>{sessions.clear();return RemoteResult.Unauthorized}
}

private fun JSONObject.nullableString(name:String):String? = if(!has(name)||isNull(name)) null else getString(name)
private fun JSONObject.strings(name:String):List<String>{val a=getJSONArray(name);return buildList{for(i in 0 until a.length())add(a.getString(i))}}
