package com.familygrowth.android.remote

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import java.math.BigDecimal
import java.net.HttpURLConnection
import java.net.URL
import java.time.LocalDate
import java.util.UUID

data class RemoteExchangePreview(val id:String,val sourceAmount:BigDecimal,val fee:BigDecimal,val targetAmount:BigDecimal,val notice:String)
data class RemoteWithdrawalQuote(val id:String,val moneyAmount:BigDecimal,val gross:BigDecimal,val fee:BigDecimal,val net:BigDecimal,val notice:String)
data class RemoteWithdrawal(val id:String,val gross:BigDecimal,val fee:BigDecimal,val net:BigDecimal,val status:String,val requestedAt:String)
data class RemoteRewardProduct(val id:String,val title:String,val coinCost:Int)
data class RemoteRewardOrder(val id:String,val title:String,val coinCost:Int,val status:String)
data class RemoteRewardBudget(val dailyLimit:BigDecimal,val weeklyLimit:BigDecimal,val monthlyLimit:BigDecimal,val dailySpent:BigDecimal,val weeklySpent:BigDecimal,val monthlySpent:BigDecimal,val remaining:BigDecimal,val overflowPolicy:String)
data class RemoteExchangeControl(val moneyToCoinEnabled:Boolean,val coinToMoneyEnabled:Boolean,val moneyDailyLimit:BigDecimal,val moneyMonthlyLimit:BigDecimal,val coinDailyLimit:BigDecimal,val coinMonthlyLimit:BigDecimal,val childRequiresApproval:Boolean)
data class RemoteExchangeApproval(val id:String,val previewId:String,val status:String,val note:String)
data class RemoteWish(val id:String,val title:String,val target:BigDecimal,val allocated:BigDecimal)
data class RemoteFund(val id:String,val name:String)
data class RemoteFundPosition(val nav:BigDecimal,val shares:BigDecimal)
data class RemoteFundTradePreview(val id:String,val side:String,val gross:BigDecimal,val fee:BigDecimal,val net:BigDecimal,val shares:BigDecimal,val nav:BigDecimal,val notice:String,val holdingDays:Int=0,val earlyFeeRate:BigDecimal=BigDecimal.ZERO,val earlyFee:BigDecimal=BigDecimal.ZERO)
data class RemoteSavingRule(val periodicRate:BigDecimal,val minimumBalance:BigDecimal,val version:Long)
data class RemoteEconomyLab(val savingRule:RemoteSavingRule?,val marketRuleCount:Int,val holdingRuleCount:Int,val notice:String)
data class RemoteUsageReport(val period:String,val appMinutes:Int,val learningMinutes:Int,val submittedTasks:Int,val approvedTasks:Int)
data class RemoteRetentionPolicy(val usageDetailDays:Int,val version:Long)
data class RemoteRetentionRun(val usageEventsDeleted:Int,val allowancesRedacted:Int,val confirmationsCleared:Int)
data class RemoteGrowthPlan(val id:String,val title:String,val category:String,val target:String,val status:String,val revision:Long,val startDate:String)
data class RemoteGrowthArtifact(val id:String,val contentType:String,val byteSize:Long,val altText:String)
data class RemoteGrowthMilestone(val id:String,val occurredOn:String,val category:String,val title:String,val observation:String,val revision:Long,val artifacts:List<RemoteGrowthArtifact>)
data class RemoteGrowthReport(val activePlans:Long,val completedPlans:Long,val milestones:Long,val artifacts:Long,val generatedAt:String)

/** Production-only adapter for the Stage 5–7/17/9 APIs. It never falls back to local success. */
class ProductionFamilyApi(private val sessions:MemorySessionStore) {
    private fun session()=sessions.get()
    suspend fun gift(amount:BigDecimal):RemoteResult<Unit> = parent("/children/{child}/gift-money","POST",JSONObject().put("amount",amount).put("note","家长在 Android 端登记压岁钱"),true){Unit}
    suspend fun exchangePreview(amount:BigDecimal,asChild:Boolean=false):RemoteResult<RemoteExchangePreview> = member(asChild,"/children/{child}/exchange-previews","POST",JSONObject().put("direction","MONEY_TO_COIN").put("sourceAmount",amount),decode=::decodeExchangePreview)
    suspend fun confirmExchange(preview:String,asChild:Boolean=false):RemoteResult<Unit> = member(asChild,"/exchange-previews/$preview/confirm","POST",null,true){Unit}
    suspend fun rewardBudgetSummary():RemoteResult<RemoteRewardBudget> = parent("/children/{child}/reward-budget-summary","GET",null){root->val d=root.getJSONObject("data");val rule=d.getJSONObject("rule");RemoteRewardBudget(rule.decimal("dailyMoneyLimit"),rule.decimal("weeklyMoneyLimit"),rule.decimal("monthlyMoneyLimit"),d.decimal("spentToday"),d.decimal("spentThisWeek"),d.decimal("spentThisMonth"),d.decimal("remainingMoney"),rule.getString("overflowPolicy"))}
    suspend fun configureRewardBudget(daily:BigDecimal,weekly:BigDecimal,monthly:BigDecimal,policy:String):RemoteResult<Unit> = parent("/children/{child}/reward-budget-rules","POST",JSONObject().put("zoneId","Asia/Shanghai").put("dailyMoneyLimit",daily).put("weeklyMoneyLimit",weekly).put("monthlyMoneyLimit",monthly).put("overflowPolicy",policy).put("excessCoinPerMoney","1.000000").put("excessXpPerMoney","10.000000"),true){Unit}
    suspend fun activeExchangeControl(asChild:Boolean=false):RemoteResult<RemoteExchangeControl?> = member(asChild,"/exchange-control-rules/active","GET",null){root->if(root.isNull("data"))null else root.getJSONObject("data").let{d->RemoteExchangeControl(d.getBoolean("moneyToCoinEnabled"),d.getBoolean("coinToMoneyEnabled"),d.decimal("moneyToCoinDailyLimit"),d.decimal("moneyToCoinMonthlyLimit"),d.decimal("coinToMoneyDailyLimit"),d.decimal("coinToMoneyMonthlyLimit"),d.getBoolean("childRequiresParentApproval"))}}
    suspend fun configureExchangeControl(moneyDaily:BigDecimal,moneyMonthly:BigDecimal,coinDaily:BigDecimal,coinMonthly:BigDecimal,approval:Boolean):RemoteResult<Unit> = parent("/exchange-control-rules","POST",JSONObject().put("moneyToCoinEnabled",true).put("coinToMoneyEnabled",true).put("moneyToCoinDailyLimit",moneyDaily).put("moneyToCoinMonthlyLimit",moneyMonthly).put("coinToMoneyDailyLimit",coinDaily).put("coinToMoneyMonthlyLimit",coinMonthly).put("childRequiresParentApproval",approval).put("zoneId","Asia/Shanghai"),true){Unit}
    suspend fun requestExchangeApproval(preview:String):RemoteResult<RemoteExchangeApproval> = child("/children/{child}/exchange-approval-requests","POST",JSONObject().put("previewId",preview),true){decodeExchangeApproval(it.getJSONObject("data"))}
    suspend fun exchangeApprovals(asChild:Boolean=false):RemoteResult<List<RemoteExchangeApproval>> = member(asChild,"/children/{child}/exchange-approval-requests","GET",null){root->root.getJSONArray("data").objects(::decodeExchangeApproval)}
    suspend fun reviewExchangeApproval(id:String,approved:Boolean):RemoteResult<RemoteExchangeApproval> = parent("/exchange-approval-requests/$id/review","POST",JSONObject().put("approved",approved).put("note",if(approved)"家长同意本次家庭兑换" else "本次先不兑换"),true){decodeExchangeApproval(it.getJSONObject("data"))}
    suspend fun withdrawalQuote(amount:BigDecimal):RemoteResult<RemoteWithdrawalQuote> = parent("/children/{child}/withdrawal-quotes","POST",JSONObject().put("moneyAmount",amount),true){root->
        val d=root.getJSONObject("data");RemoteWithdrawalQuote(d.getString("id"),d.decimal("moneyAmount"),d.decimal("grossPayout"),d.decimal("feeAmount"),d.decimal("netPayout"),d.getString("notice"))
    }
    suspend fun requestWithdrawal(quote:String):RemoteResult<RemoteWithdrawal> = parent("/children/{child}/withdrawal-requests","POST",JSONObject().put("quoteId",quote),true){decodeWithdrawal(it.getJSONObject("data"))}
    suspend fun withdrawals():RemoteResult<List<RemoteWithdrawal>> = parent("/children/{child}/withdrawal-requests","GET",null){root->root.getJSONArray("data").objects(::decodeWithdrawal)}
    suspend fun approveWithdrawal(id:String):RemoteResult<RemoteWithdrawal> = parent("/withdrawal-requests/$id/approve","POST",null,true){decodeWithdrawal(it.getJSONObject("data"))}
    suspend fun rejectWithdrawal(id:String):RemoteResult<RemoteWithdrawal> = parent("/withdrawal-requests/$id/reject","POST",null,true){decodeWithdrawal(it.getJSONObject("data"))}
    suspend fun cancelWithdrawalRequest(id:String):RemoteResult<RemoteWithdrawal> = child("/withdrawal-requests/$id/cancel","POST",null,true){decodeWithdrawal(it.getJSONObject("data"))}
    suspend fun markWithdrawalPaid(id:String):RemoteResult<RemoteWithdrawal> = parent("/withdrawal-requests/$id/paid","POST",null,true){decodeWithdrawal(it.getJSONObject("data"))}
    suspend fun products():RemoteResult<List<RemoteRewardProduct>> = parent("/reward-products?activeOnly=true","GET",null){root->root.getJSONArray("data").objects{d->RemoteRewardProduct(d.getString("id"),d.getString("title"),d.getInt("coinCost"))}}
    suspend fun createProduct(title:String,price:Int):RemoteResult<RemoteRewardProduct> = parent("/reward-products","POST",JSONObject().put("title",title).put("coinCost",price).put("stockCount",1000000).put("active",true)){root->val d=root.getJSONObject("data");RemoteRewardProduct(d.getString("id"),d.getString("title"),d.getInt("coinCost"))}
    suspend fun orderReward(product:String):RemoteResult<RemoteRewardOrder> = child("/children/{child}/reward-orders","POST",JSONObject().put("productId",product),true){decodeRewardOrder(it.getJSONObject("data"))}
    suspend fun rewardOrders():RemoteResult<List<RemoteRewardOrder>> = parent("/children/{child}/reward-orders","GET",null){root->root.getJSONArray("data").objects(::decodeRewardOrder)}
    suspend fun reviewReward(order:String,approved:Boolean):RemoteResult<RemoteRewardOrder> = parent("/reward-orders/$order/review","POST",JSONObject().put("approved",approved),true){decodeRewardOrder(it.getJSONObject("data"))}
    suspend fun fulfillReward(order:String,note:String):RemoteResult<Unit> = parent("/reward-orders/$order/fulfill","POST",JSONObject().put("note",note),true){Unit}
    suspend fun savingDeposit(amount:BigDecimal):RemoteResult<Unit> = parent("/children/{child}/saving/transfers","POST",JSONObject().put("direction","DEPOSIT").put("amount",amount),true){Unit}
    suspend fun savingBalance():RemoteResult<BigDecimal> = parent("/children/{child}/saving","GET",null){it.getJSONObject("data").decimal("balance")}
    suspend fun wishes():RemoteResult<List<RemoteWish>> = parent("/children/{child}/wishes","GET",null){root->root.getJSONArray("data").objects{d->RemoteWish(d.getString("id"),d.getString("title"),d.decimal("targetAmount"),d.decimal("allocatedAmount"))}}
    suspend fun createWish(title:String,target:BigDecimal):RemoteResult<RemoteWish> = parent("/children/{child}/wishes","POST",JSONObject().put("title",title).put("targetAmount",target)){root->val d=root.getJSONObject("data");RemoteWish(d.getString("id"),d.getString("title"),d.decimal("targetAmount"),d.decimal("allocatedAmount"))}
    suspend fun allocateWish(id:String,amount:BigDecimal):RemoteResult<RemoteWish> = parent("/wishes/$id/allocation","POST",JSONObject().put("amount",amount),true){root->val d=root.getJSONObject("data");RemoteWish(d.getString("id"),d.getString("title"),d.decimal("targetAmount"),d.decimal("allocatedAmount"))}
    suspend fun funds():RemoteResult<List<RemoteFund>> = parent("/funds","GET",null){root->root.getJSONArray("data").objects{d->RemoteFund(d.getString("id"),d.getString("name"))}}
    suspend fun createFund():RemoteResult<RemoteFund> = parent("/funds","POST",JSONObject().put("name","家庭成长模拟基金").put("riskLabel","纯模拟，可涨可跌")){root->val d=root.getJSONObject("data");RemoteFund(d.getString("id"),d.getString("name"))}
    suspend fun updateNav(fund:String,nav:BigDecimal):RemoteResult<Unit> = parent("/funds/$fund/nav","POST",JSONObject().put("navDate",LocalDate.now().toString()).put("nav",nav)){Unit}
    suspend fun configureFundFees(fund:String):RemoteResult<Unit> = parent("/funds/$fund/fee-rules","POST",JSONObject().put("buyFeeRate","0.000000").put("sellFeeRate","0.000000")){Unit}
    suspend fun tradePreview(fund:String,side:String,input:BigDecimal):RemoteResult<RemoteFundTradePreview> = parent("/children/{child}/funds/$fund/trade-previews","POST",JSONObject().put("side",side).put("inputAmount",input)){root->val d=root.getJSONObject("data");RemoteFundTradePreview(d.getString("id"),d.getString("side"),d.decimal("grossMoney"),d.decimal("feeAmount"),d.decimal("netMoney"),d.decimal("shares"),d.decimal("nav"),d.getString("notice"),d.optInt("holdingDays"),d.optString("earlyFeeRate","0").toBigDecimal(),d.optString("earlyFeeAmount","0").toBigDecimal())}
    suspend fun confirmTrade(preview:String):RemoteResult<Unit> = parent("/fund-trade-previews/$preview/confirm","POST",null,true){Unit}
    suspend fun fundPosition(fund:String):RemoteResult<RemoteFundPosition> = parent("/children/{child}/funds/$fund/position","GET",null){root->val d=root.getJSONObject("data");RemoteFundPosition(d.decimal("nav"),d.decimal("shares"))}
    suspend fun economyLab():RemoteResult<RemoteEconomyLab> = parent("/economy-lab","GET",null){root->val d=root.getJSONObject("data");val s=if(d.isNull("savingRule"))null else d.getJSONObject("savingRule").let{RemoteSavingRule(it.decimal("periodicRate"),it.decimal("minimumBalance"),it.getLong("version"))};RemoteEconomyLab(s,d.getJSONArray("marketRules").length(),d.getJSONArray("holdingRules").length(),d.getString("notice"))}
    suspend fun configureSavingReward(rate:BigDecimal,minimum:BigDecimal):RemoteResult<Unit> = parent("/economy-lab/saving-rule","PUT",JSONObject().put("periodicRate",rate).put("minimumBalance",minimum)){Unit}
    suspend fun settleSavingReward():RemoteResult<Unit> = parent("/economy-lab/children/{child}/saving-awards","POST",JSONObject().put("cycleKey",LocalDate.now().toString().substring(0,7)),true){Unit}
    suspend fun configureMarket(fund:String):RemoteResult<Unit> = parent("/economy-lab/funds/$fund/market-rule","PUT",JSONObject().put("seedLabel","家庭学习固定种子").put("maximumDailyBps",300)){Unit}
    suspend fun configureHoldingFee(fund:String):RemoteResult<Unit> = parent("/economy-lab/funds/$fund/holding-fee-rule","PUT",JSONObject().put("minimumHoldingDays",30).put("earlyFeeRate","0.020000")){Unit}
    suspend fun advanceMarket(fund:String):RemoteResult<Unit> = parent("/economy-lab/funds/$fund/ticks","POST",JSONObject().put("tickDate",LocalDate.now().toString()),true){Unit}
    suspend fun createCosmetic(title:String,cost:Int):RemoteResult<Unit> = parent("/economy-lab/cosmetics","POST",JSONObject().put("title",title).put("coinCost",cost).put("stockCount",100)){Unit}
    suspend fun todayReport():RemoteResult<RemoteUsageReport> = parent("/children/{child}/reports/today","GET",null){root->val d=root.getJSONObject("data");RemoteUsageReport(d.getString("date"),d.getInt("appMinutes"),d.getInt("learningMinutes"),d.getInt("submittedTasks"),d.getInt("approvedTasks"))}
    suspend fun monthlyReport():RemoteResult<RemoteUsageReport> = parent("/children/{child}/reports/monthly?month=${LocalDate.now().toString().substring(0,7)}","GET",null){root->val d=root.getJSONObject("data");RemoteUsageReport(d.getString("month"),d.getInt("appMinutes"),d.getInt("learningMinutes"),d.getInt("submittedTasks"),d.getInt("approvedTasks"))}
    suspend fun retentionPolicy():RemoteResult<RemoteRetentionPolicy> = parent("/children/{child}/data-rights/retention-policy","GET",null){root->val d=root.getJSONObject("data");RemoteRetentionPolicy(d.getInt("usageDetailDays"),d.getLong("version"))}
    suspend fun updateRetentionPolicy(days:Int,version:Long):RemoteResult<RemoteRetentionPolicy> = parent("/children/{child}/data-rights/retention-policy","PUT",JSONObject().put("usageDetailDays",days).put("expectedVersion",version).put("reason","家长在 Android 隐私中心调整使用明细保留期")){root->val d=root.getJSONObject("data");RemoteRetentionPolicy(d.getInt("usageDetailDays"),d.getLong("version"))}
    suspend fun runRetention():RemoteResult<RemoteRetentionRun> = parent("/children/{child}/data-rights/retention-runs","POST",null){root->val d=root.getJSONObject("data");RemoteRetentionRun(d.getInt("usageEventsDeleted"),d.getInt("allowancesRedacted"),d.getInt("confirmationsCleared"))}
    suspend fun growthPlans():RemoteResult<List<RemoteGrowthPlan>> = parent("/children/{child}/growth-archive/plans","GET",null){root->root.getJSONArray("data").objects(::decodeGrowthPlan)}
    suspend fun createGrowthPlan(title:String,category:String,target:String):RemoteResult<RemoteGrowthPlan> = parent("/children/{child}/growth-archive/plans","POST",JSONObject().put("title",title).put("description","").put("category",category).put("ageStage","FAMILY").put("target",target).put("startDate",LocalDate.now().toString()).put("status","ACTIVE"),true){decodeGrowthPlan(it.getJSONObject("data"))}
    suspend fun transitionGrowthPlan(plan:RemoteGrowthPlan,status:String):RemoteResult<RemoteGrowthPlan> = parent("/children/{child}/growth-archive/plans/${plan.id}/transition","POST",JSONObject().put("status",status).put("expectedRevision",plan.revision).put("reason","家长在 Android 成长年轮中更新计划"),true){decodeGrowthPlan(it.getJSONObject("data"))}
    suspend fun growthMilestones():RemoteResult<List<RemoteGrowthMilestone>> = parent("/children/{child}/growth-archive/milestones","GET",null){root->root.getJSONArray("data").objects(::decodeGrowthMilestone)}
    suspend fun createGrowthMilestone(planId:String?,title:String,observation:String,category:String):RemoteResult<RemoteGrowthMilestone> = parent("/children/{child}/growth-archive/milestones","POST",JSONObject().put("planId",planId?:JSONObject.NULL).put("goalId",JSONObject.NULL).put("occurredOn",LocalDate.now().toString()).put("category",category).put("title",title).put("observation",observation),true){decodeGrowthMilestone(it.getJSONObject("data"))}
    suspend fun growthReport():RemoteResult<RemoteGrowthReport> = parent("/children/{child}/growth-archive/report","GET",null){root->val d=root.getJSONObject("data");RemoteGrowthReport(d.getLong("activePlans"),d.getLong("completedPlans"),d.getLong("milestones"),d.getLong("artifacts"),d.getString("generatedAt"))}
    suspend fun familyMembers():RemoteResult<List<RemoteFamilyMember>> = parent("/members","GET",null){root->root.getJSONArray("data").objects{d->RemoteFamilyMember(d.getString("id"),d.getString("displayName"),d.getString("role"),d.getString("status"))}}
    suspend fun resetMemberPin(memberId:String,pin:String):RemoteResult<Unit> = parent("/members/$memberId/reset-pin","POST",JSONObject().put("pin",pin)){Unit}
    suspend fun revokeMember(memberId:String):RemoteResult<Unit> = parent("/members/$memberId/revoke","POST",null){Unit}
    suspend fun inviteGuardian(name:String):RemoteResult<RemoteOneTimeCode> = parent("/parent-invitations","POST",JSONObject().put("invitedName",name),true){root->val d=root.getJSONObject("data");val i=d.getJSONObject("invitation");RemoteOneTimeCode(i.getString("id"),if(d.isNull("oneTimeCode"))null else d.getString("oneTimeCode"),i.getString("expiresAt"))}
    suspend fun createParentPairing():RemoteResult<RemoteOneTimeCode> = parent("/device-pairings","POST",JSONObject().put("role","PARENT").put("childId",JSONObject.NULL),true){root->val d=root.getJSONObject("data");val p=d.getJSONObject("pairing");RemoteOneTimeCode(p.getString("id"),if(d.isNull("oneTimeCode"))null else d.getString("oneTimeCode"),p.getString("expiresAt"))}
    suspend fun createChildPairing(childId:String):RemoteResult<RemoteOneTimeCode> = parent("/device-pairings","POST",JSONObject().put("role","CHILD").put("childId",childId),true){root->val d=root.getJSONObject("data");val p=d.getJSONObject("pairing");RemoteOneTimeCode(p.getString("id"),if(d.isNull("oneTimeCode"))null else d.getString("oneTimeCode"),p.getString("expiresAt"))}
    suspend fun pairedDevices():RemoteResult<List<RemotePairedDevice>> = parent("/devices","GET",null){root->root.getJSONArray("data").objects{d->RemotePairedDevice(d.getString("id"),d.getString("deviceName"),d.getString("actorRole"),if(d.isNull("childId"))null else d.getString("childId"),d.getString("status"),d.getString("lastSeenAt"))}}
    suspend fun revokeDevice(deviceId:String):RemoteResult<RemotePairedDevice> = parent("/devices/$deviceId/revoke","POST",null){root->val d=root.getJSONObject("data");RemotePairedDevice(d.getString("id"),d.getString("deviceName"),d.getString("actorRole"),if(d.isNull("childId"))null else d.getString("childId"),d.getString("status"),d.getString("lastSeenAt"))}
    suspend fun familyNotifications():RemoteResult<List<RemoteFamilyNotification>> = parent("/notifications","GET",null){root->root.getJSONArray("data").objects{d->RemoteFamilyNotification(d.getString("id"),if(d.isNull("childId"))null else d.getString("childId"),d.getString("type"),d.getString("title"),d.getString("body"),d.getString("status"),d.getString("createdAt"))}}
    suspend fun readNotification(notificationId:String):RemoteResult<RemoteFamilyNotification> = parent("/notifications/$notificationId/read","POST",null){root->val d=root.getJSONObject("data");RemoteFamilyNotification(d.getString("id"),if(d.isNull("childId"))null else d.getString("childId"),d.getString("type"),d.getString("title"),d.getString("body"),d.getString("status"),d.getString("createdAt"))}
    suspend fun uploadGrowthArtifact(milestoneId:String,bytes:ByteArray,mime:String,altText:String):RemoteResult<RemoteGrowthArtifact>{
        val s=session()?:return RemoteResult.Failure("请先连接家庭服务")
        return multipart(s,"/children/{child}/growth-archive/milestones/$milestoneId/artifacts",s.parentToken,bytes,mime,altText){decodeGrowthArtifact(it.getJSONObject("data"))}
    }

    private suspend fun <T> parent(path:String,method:String,body:JSONObject?,key:Boolean=false,decode:(JSONObject)->T):RemoteResult<T>{val s=session()?:return RemoteResult.Failure("请先连接家庭服务");return request(s,path,method,s.parentToken,body,key,decode)}
    private suspend fun <T> child(path:String,method:String,body:JSONObject?,key:Boolean=false,decode:(JSONObject)->T):RemoteResult<T>{val s=session()?:return RemoteResult.Failure("请先连接家庭服务");return request(s,path,method,s.childToken,body,key,decode)}
    private suspend fun <T> member(asChild:Boolean,path:String,method:String,body:JSONObject?,key:Boolean=false,decode:(JSONObject)->T):RemoteResult<T> = if(asChild) child(path,method,body,key,decode) else parent(path,method,body,key,decode)
    private suspend fun <T> request(s:RemoteSession,path:String,method:String,token:String,body:JSONObject?,key:Boolean,decode:(JSONObject)->T):RemoteResult<T> = withContext(Dispatchers.IO){
        try { val target=path.replace("{child}",s.childId);val c=(URL(s.baseUrl+"/api/v1/families/${s.familyId}"+target).openConnection() as HttpURLConnection).apply{requestMethod=method;connectTimeout=8_000;readTimeout=10_000;setRequestProperty("Accept","application/json");setRequestProperty("Authorization","Bearer $token");if(key)setRequestProperty("Idempotency-Key",UUID.randomUUID().toString());if(body!=null){doOutput=true;setRequestProperty("Content-Type","application/json");outputStream.use{it.write(body.toString().toByteArray())}}};val code=c.responseCode;if(code==401){c.disconnect();sessions.clear();return@withContext RemoteResult.Unauthorized};val stream=if(code in 200..299)c.inputStream else c.errorStream;val text=stream?.bufferedReader()?.use{it.readText()}.orEmpty();c.disconnect();if(code !in 200..299)return@withContext remoteFailureForStatus(code);RemoteResult.Ok(decode(JSONObject(text))) } catch(_:IOException){RemoteResult.Failure("无法连接家庭服务，本次操作没有记为成功",RemoteFailureKind.RETRYABLE)} catch(_:Exception){RemoteResult.Failure("家庭服务返回了无法识别的数据")}
    }
    private suspend fun <T> multipart(s:RemoteSession,path:String,token:String,bytes:ByteArray,mime:String,altText:String,decode:(JSONObject)->T):RemoteResult<T> = withContext(Dispatchers.IO){
        if(bytes.isEmpty()||bytes.size>5*1024*1024||mime !in setOf("image/jpeg","image/png","image/webp"))return@withContext RemoteResult.Failure("照片需为不超过 5 MiB 的 JPEG、PNG 或 WebP")
        val boundary="FamilyGrowth-${UUID.randomUUID()}"
        try{val target=path.replace("{child}",s.childId);val c=(URL(s.baseUrl+"/api/v1/families/${s.familyId}"+target).openConnection() as HttpURLConnection).apply{requestMethod="POST";connectTimeout=8_000;readTimeout=15_000;doOutput=true;setRequestProperty("Accept","application/json");setRequestProperty("Authorization","Bearer $token");setRequestProperty("Idempotency-Key",UUID.randomUUID().toString());setRequestProperty("Content-Type","multipart/form-data; boundary=$boundary")};c.outputStream.buffered().use{out->fun line(v:String){out.write(v.toByteArray());out.write("\r\n".toByteArray())};line("--$boundary");line("Content-Disposition: form-data; name=\"altText\"");line("");line(altText);line("--$boundary");line("Content-Disposition: form-data; name=\"file\"; filename=\"growth-image\"");line("Content-Type: $mime");line("");out.write(bytes);line("");line("--$boundary--")};val code=c.responseCode;if(code==401){c.disconnect();sessions.clear();return@withContext RemoteResult.Unauthorized};val stream=if(code in 200..299)c.inputStream else c.errorStream;val text=stream?.bufferedReader()?.use{it.readText()}.orEmpty();c.disconnect();if(code !in 200..299)return@withContext remoteFailureForStatus(code);RemoteResult.Ok(decode(JSONObject(text)))}catch(_:IOException){RemoteResult.Failure("照片上传中断，本次没有记为成功",RemoteFailureKind.RETRYABLE)}catch(_:Exception){RemoteResult.Failure("成长档案返回了无法识别的数据")}
    }
    private fun decodeWithdrawal(d:JSONObject)=RemoteWithdrawal(d.getString("id"),d.decimal("grossPayout"),d.decimal("feeAmount"),d.decimal("netPayout"),d.getString("status"),d.getString("requestedAt"))
    private fun decodeRewardOrder(d:JSONObject)=RemoteRewardOrder(d.getString("id"),d.getString("productTitle"),d.getInt("coinCost"),d.getString("status"))
    private fun decodeExchangeApproval(d:JSONObject)=RemoteExchangeApproval(d.getString("id"),d.getString("previewId"),d.getString("status"),d.optString("reviewNote"))
    private fun decodeGrowthPlan(d:JSONObject)=RemoteGrowthPlan(d.getString("id"),d.getString("title"),d.getString("category"),d.optString("target"),d.getString("status"),d.getLong("revision"),d.getString("startDate"))
    private fun decodeGrowthArtifact(d:JSONObject)=RemoteGrowthArtifact(d.getString("id"),d.getString("contentType"),d.getLong("byteSize"),d.optString("altText"))
    private fun decodeGrowthMilestone(d:JSONObject)=RemoteGrowthMilestone(d.getString("id"),d.getString("occurredOn"),d.getString("category"),d.getString("title"),d.optString("observation"),d.getLong("revision"),d.getJSONArray("artifacts").objects(::decodeGrowthArtifact))
}

private fun JSONObject.decimal(name:String)=getString(name).toBigDecimal()
private fun <T> JSONArray.objects(decode:(JSONObject)->T)=buildList{for(i in 0 until length())add(decode(getJSONObject(i)))}
internal fun decodeExchangePreview(root:JSONObject):RemoteExchangePreview{val d=root.getJSONObject("data");return remoteExchangePreview(d.getString("id"),d.getString("sourceAmount"),d.getString("sourceFee"),d.getString("targetAmount"),d.getString("educationNotice"))}
internal fun remoteExchangePreview(id:String,source:String,fee:String,target:String,notice:String)=RemoteExchangePreview(id,source.toBigDecimal(),fee.toBigDecimal(),target.toBigDecimal(),notice)
